window.SCAM_CONTENT = window.SCAM_CONTENT || {};

window.SCAM_CONTENT["distraction-theft-scam"] = {
  raw_html: `
    <section class="card">
      <h2 data-sr="Uvod: distraction theft" data-en="Introduction: distraction theft">Uvod: distraction theft</h2>
      <p data-sr="Distraction theft koristi više izvršilaca: jedan drži tvoju pažnju, drugi uzima predmet. Često se dešava na stanicama, turističkim mestima, bankomatima i ulazima u prevoz." data-en="Distraction theft uses multiple actors: one holds your attention while another takes an item. It often happens at stations, tourist spots, ATMs, and transit entrances.">Distraction theft koristi više izvršilaca: jedan drži tvoju pažnju, drugi uzima predmet. Često se dešava na stanicama, turističkim mestima, bankomatima i ulazima u prevoz.</p>
      <div class="callout" data-sr="<strong>Model:</strong> kontakt → odvlačenje → krađa → brz izlaz → zloupotreba" data-en="<strong>Model:</strong> contact → distraction → theft → fast exit → abuse"><strong>Model:</strong> kontakt → odvlačenje → krađa → brz izlaz → zloupotreba</div>
    </section>
    <section class="card">
      <h2 data-sr="Hronološki tok (faze + grananja)" data-en="Timeline (phases + branching)">Hronološki tok (faze + grananja)</h2>
      
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 1 — Inicijalni kontakt na gužvi" data-en="Phase 1 — Initial contact in a crowd">Faza 1 — Inicijalni kontakt na gužvi</h3>
        <p data-sr="Stranac započinje prijateljski razgovor, pita za put, pomaže sa kartom ili traži potpis, dok si fokusiran na lice koje govori." data-en="A stranger starts a friendly chat, asks directions, helps with a map, or asks for a signature while you focus on the speaker.">Stranac započinje prijateljski razgovor, pita za put, pomaže sa kartom ili traži potpis, dok si fokusiran na lice koje govori.</p>
        <ul class="bullets"><li data-sr="Kontakt deluje pristojan i kratko traje da ne podigneš odbranu." data-en="Contact seems polite and brief so you lower your guard.">Kontakt deluje pristojan i kratko traje da ne podigneš odbranu.</li><li data-sr="Druga osoba je blizu torbe ili džepa dok gledaš napred." data-en="Another person is near your bag or pocket while you look ahead.">Druga osoba je blizu torbe ili džepa dok gledaš napred.</li><li data-sr="Gužva na ulazu u autobus, tramvaj ili lift povećava šansu za džeparenje." data-en="Crowding at bus, tram, or lift entry increases pickpocket chance.">Gužva na ulazu u autobus, tramvaj ili lift povećava šansu za džeparenje.</li><li data-sr="Može postojati treći član koji filmuje ili signalizuje." data-en="A third member may film or signal.">Može postojati treći član koji filmuje ili signalizuje.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta usmeri pažnju na razgovor i smanji kontrolu nad prtljagom." data-en="<strong>Phase threshold:</strong> The target focuses on talk and reduces control of belongings."><strong>Prag faze:</strong> Meta usmeri pažnju na razgovor i smanji kontrolu nad prtljagom.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="pigeon-drop-scam.html" data-sr="Pigeon drop — srodna ulična šema poverenja" data-en="Pigeon drop — related street confidence scheme">Pigeon drop — srodna ulična šema poverenja</a></li><li><a href="impersonation-scam.html" data-sr="Lažno predstavljanje u ulogama pomoći" data-en="Impersonation in a help role">Lažno predstavljanje u ulogama pomoći</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 2 — Odvlačenje pažnje aktivnostima" data-en="Phase 2 — Distraction activities">Faza 2 — Odvlačenje pažnje aktivnostima</h3>
        <p data-sr="Peticija, anketa, igra ili nagradna kartica zahtevaju da koristiš obe ruke ili da odložiš torbu." data-en="A petition, survey, game, or prize card needs both hands or makes you set the bag down.">Peticija, anketa, igra ili nagradna kartica zahtevaju da koristiš obe ruke ili da odložiš torbu.</p>
        <ul class="bullets"><li data-sr="Traže da potpišeš na tabli dok torba stoji iza tebe." data-en="They ask you to sign on a clipboard while your bag is behind you.">Traže da potpišeš na tabli dok torba stoji iza tebe.</li><li data-sr="Izlijevanje kafe ili vode odvlači pogled nadole." data-en="A coffee or water spill draws your gaze downward.">Izlijevanje kafe ili vode odvlači pogled nadole.</li><li data-sr="Pokazivanje telefona sa mapom drži tvoj ekran okrenut od torbe." data-en="Showing a phone map keeps your screen turned away from the bag.">Pokazivanje telefona sa mapom drži tvoj ekran okrenut od torbe.</li><li data-sr="Deca ili životinja mogu biti deo scene da se smekša." data-en="Children or animals may be part of the scene to soften you.">Deca ili životinja mogu biti deo scene da se smekša.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta odvoji pogled od vrednosti koje nosi." data-en="<strong>Phase threshold:</strong> The target looks away from what they carry."><strong>Prag faze:</strong> Meta odvoji pogled od vrednosti koje nosi.</div>
        
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 3 — Fizički potez" data-en="Phase 3 — Physical move">Faza 3 — Fizički potez</h3>
        <p data-sr="Džeparoš ili član ekipe otvara torbu, seče kaiš torbe ili izvlači novčanik tokom gužve." data-en="A pickpocket or team member opens a bag, cuts a strap, or pulls a wallet during crowding.">Džeparoš ili član ekipe otvara torbu, seče kaiš torbe ili izvlači novčanik tokom gužve.</p>
        <ul class="bullets"><li data-sr="Krađa traje sekundu dok si okrenut." data-en="The theft lasts a second while you are turned.">Krađa traje sekundu dok si okrenut.</li><li data-sr="Kartice se odmah koriste za brze kupovine ili podizanje." data-en="Cards may be used quickly for purchases or withdrawals.">Kartice se odmah koriste za brze kupovine ili podizanje.</li><li data-sr="Telefon se gasi ili izlazi iz Bluetooth dometa da ga ne pronađeš mapom." data-en="The phone is powered off or taken out of Bluetooth range so find-my fails.">Telefon se gasi ili izlazi iz Bluetooth dometa da ga ne pronađeš mapom.</li><li data-sr="Novčanik se baca nakon uzimanja kartica." data-en="The wallet is discarded after cards are taken.">Novčanik se baca nakon uzimanja kartica.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta oseti da nešto nedostaje ili kasnije primećuje prazan džep." data-en="<strong>Phase threshold:</strong> The target feels something missing or later notices an empty pocket."><strong>Prag faze:</strong> Meta oseti da nešto nedostaje ili kasnije primećuje prazan džep.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="card-skimming.html" data-sr="Kartice posle krađe — zloupotreba na POS ili onlajn" data-en="After card theft — misuse at POS or online">Kartice posle krađe — zloupotreba na POS ili onlajn</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 4 — Brz izlazak" data-en="Phase 4 — Fast exit">Faza 4 — Brz izlazak</h3>
        <p data-sr="Učesnici se razilaze u različitim pravcima, ulaze u prevoz ili menjaju odeću." data-en="Participants split directions, enter transit, or change clothing.">Učesnici se razilaze u različitim pravcima, ulaze u prevoz ili menjaju odeću.</p>
        <ul class="bullets"><li data-sr="Nestaju pre nego što shvatiš šta se desilo." data-en="They vanish before you understand what happened.">Nestaju pre nego što shvatiš šta se desilo.</li><li data-sr="Može ostati jedan dobar samaritanin koji odvlači krivicu." data-en="One good Samaritan may remain to misdirect blame.">Može ostati jedan dobar samaritanin koji odvlači krivicu.</li><li data-sr="Žrtva često ne prijavljuje odmah jer nije sigurna šta se desilo." data-en="The victim often delays reporting because they are unsure what happened.">Žrtva često ne prijavljuje odmah jer nije sigurna šta se desilo.</li><li data-sr="Video nadzor na stanicama ponekad hvata scenu." data-en="Station CCTV sometimes captures the scene.">Video nadzor na stanicama ponekad hvata scenu.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva potvrđuje gubitak predmeta ili sredstava." data-en="<strong>Phase threshold:</strong> The victim confirms loss of item or funds."><strong>Prag faze:</strong> Žrtva potvrđuje gubitak predmeta ili sredstava.</div>
        
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 5 — Zloupotreba ukradenog" data-en="Phase 5 — Abuse of stolen items">Faza 5 — Zloupotreba ukradenog</h3>
        <p data-sr="Kartice, telefon i lična dokumenta koriste se za kupovine, prevare ili pristup nalozima." data-en="Cards, phone, and ID are used for purchases, scams, or account access.">Kartice, telefon i lična dokumenta koriste se za kupovine, prevare ili pristup nalozima.</p>
        <ul class="bullets"><li data-sr="Brzi OTP ili biometrijski otključaj ako je telefon ostao otključan." data-en="Fast OTP or biometric unlock if the phone was left unlocked.">Brzi OTP ili biometrijski otključaj ako je telefon ostao otključan.</li><li data-sr="Lažni pozivi kontaktima sa tvog telefona." data-en="Fake calls to contacts from your phone.">Lažni pozivi kontaktima sa tvog telefona.</li><li data-sr="Pokušaj resetovanja lozinki preko SMS-a." data-en="Password reset attempts via SMS.">Pokušaj resetovanja lozinki preko SMS-a.</li><li data-sr="Krađa identiteta ako su uzeti dokumenti." data-en="Identity theft if documents were taken.">Krađa identiteta ako su uzeti dokumenti.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Počinju neovlašćene transakcije ili prijave naloga." data-en="<strong>Phase threshold:</strong> Unauthorized transactions or account alerts begin."><strong>Prag faze:</strong> Počinju neovlašćene transakcije ili prijave naloga.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="identity-theft.html" data-sr="Krađa identiteta" data-en="Identity theft">Krađa identiteta</a></li><li><a href="account-takeover.html" data-sr="Preuzimanje naloga" data-en="Account takeover">Preuzimanje naloga</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 6 — Prijava i zaštita" data-en="Phase 6 — Reporting and protection">Faza 6 — Prijava i zaštita</h3>
        <p data-sr="Blokiranje kartica, prijava policiji, promena lozinki i obaveštavanje operatera smanjuje štetu." data-en="Blocking cards, police report, password changes, and carrier notice limit damage.">Blokiranje kartica, prijava policiji, promena lozinki i obaveštavanje operatera smanjuje štetu.</p>
        <ul class="bullets"><li data-sr="Kontaktiraj banku odmah za stop na karticama." data-en="Contact the bank immediately for card stops.">Kontaktiraj banku odmah za stop na karticama.</li><li data-sr="Prijavi krađu telefona operateru i ukloni uređaj sa naloga." data-en="Report phone theft to the carrier and remove the device from accounts.">Prijavi krađu telefona operateru i ukloni uređaj sa naloga.</li><li data-sr="Promeni lozinke sa drugog uređaja ako je moguće." data-en="Change passwords from another device if possible.">Promeni lozinke sa drugog uređaja ako je moguće.</li><li data-sr="Sačuvaj vreme i mesto za prijavu i osiguranje." data-en="Save time and place for reporting and insurance.">Sačuvaj vreme i mesto za prijavu i osiguranje.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva aktivira sve kanale zaštite i dokumentuje slučaj." data-en="<strong>Phase threshold:</strong> The victim activates all protection channels and documents the case."><strong>Prag faze:</strong> Žrtva aktivira sve kanale zaštite i dokumentuje slučaj.</div>
        
      </article>
    </section>
    <section class="card">
      <h2 data-sr="Crvene zastavice" data-en="Red flags">Crvene zastavice</h2>
      <ul class="bullets"><li data-sr="Više stranaca koordinisano prilazi na mestu gde je gužva." data-en="Several strangers approach in a coordinated way in a crowded place.">Više stranaca koordinisano prilazi na mestu gde je gužva.</li><li data-sr="Jedna osoba priča dok drugi slučajno stoji iza tebe." data-en="One person talks while another accidentally stands behind you.">Jedna osoba priča dok drugi slučajno stoji iza tebe.</li><li data-sr="Traže da držiš njihov predmet, torbu ili nalaz dok oni telefoniraju." data-en="They ask you to hold their item, bag, or find while they make a call. ">Traže da držiš njihov predmet, torbu ili nalaz dok oni telefoniraju.</li><li data-sr="Pokušaj fizičkog kontakta ili pomoći sa jaknom ili šalom." data-en="Attempts at physical contact or help with a jacket or scarf.">Pokušaj fizičkog kontakta ili pomoći sa jaknom ili šalom.</li><li data-sr="Odvlačenje pažnje mapom, anketom ili potpisom peticije." data-en="Distraction with a map, survey, or petition signature.">Odvlačenje pažnje mapom, anketom ili potpisom peticije.</li><li data-sr="Hitna priča o detetu, bolesti ili policiji koja traži dokument." data-en="Urgent story about a child, illness, or police needing a document.">Hitna priča o detetu, bolesti ili policiji koja traži dokument.</li><li data-sr="Traže da pokažeš novčanik da vide valutu." data-en="They ask to see your wallet to check the currency. ">Traže da pokažeš novčanik da vide valutu.</li><li data-sr="Grupa okružava tebe na ulazu u prevoz ili bankomat." data-en="A group surrounds you at transit entry or an ATM.">Grupa okružava tebe na ulazu u prevoz ili bankomat.</li><li data-sr="Jedan član slučajno prospe tečnost na tebe." data-en="One member accidentally spills liquid on you.">Jedan član slučajno prospe tečnost na tebe.</li><li data-sr="Nakon incidenta primećuješ da su telefon ili novčanik nestali." data-en="After the incident you notice phone or wallet is missing.">Nakon incidenta primećuješ da su telefon ili novčanik nestali.</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Provere: 8 brzih provera" data-en="Checks: 8 quick checks">Provere: 8 brzih provera</h2>
      <ul class="bullets"><li data-sr="Da li neko stoji u tvom slepom uglu dok razgovaraš?" data-en="Is someone in your blind spot while you talk?">Da li neko stoji u tvom slepom uglu dok razgovaraš?</li><li data-sr="Da li te više osoba istovremeno okružuje?" data-en="Are several people surrounding you at once?">Da li te više osoba istovremeno okružuje?</li><li data-sr="Da li si ostavio torbu bez nadzora na sekundu?" data-en="Did you leave a bag unattended even for a second?">Da li si ostavio torbu bez nadzora na sekundu?</li><li data-sr="Da li traže da držiš njihovu torbu ili novac?" data-en="Do they ask you to hold their bag or cash?">Da li traže da držiš njihovu torbu ili novac?</li><li data-sr="Da li osećaš dodir ili pomeranje torbe bez tvog odobrenja?" data-en="Do you feel touching or bag movement without consent?">Da li osećaš dodir ili pomeranje torbe bez tvog odobrenja?</li><li data-sr="Da li bi prava policija tražila novčanik na ulici bez legitimacije?" data-en="Would real police ask for your wallet on the street without ID?">Da li bi prava policija tražila novčanik na ulici bez legitimacije?</li><li data-sr="Da li možeš prvo ući u bezbedan prostor pre nego što nastaviš razgovor?" data-en="Can you enter a safe space before continuing the conversation?">Da li možeš prvo ući u bezbedan prostor pre nego što nastaviš razgovor?</li><li data-sr="Da li je predmet koji prodaju jeftiniji nego što bi koštala provera u zlatari?" data-en="Is the item sold cheaper than a jeweller would charge to verify it?">Da li je predmet koji prodaju jeftiniji nego što bi koštala provera u zlatari?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Checklista: 12 pitanja" data-en="Checklist: 12 questions">Checklista: 12 pitanja</h2>
      <ul class="bullets"><li data-sr="Da li sam nezavisno proverio identitet pre bilo kakve uplate?" data-en="Have I independently verified identity before any payment?">Da li sam nezavisno proverio identitet pre bilo kakve uplate?</li><li data-sr="Da li sam razgovarao sa nekim od poverenja?" data-en="Have I spoken to someone I trust?">Da li sam razgovarao sa nekim od poverenja?</li><li data-sr="Da li postoji pritisak za odluku istog dana?" data-en="Is there same-day decision pressure?">Da li postoji pritisak za odluku istog dana?</li><li data-sr="Da li je plaćanje traženo na način koji je teško otkazati?" data-en="Is payment requested in a hard-to-reverse way?">Da li je plaćanje traženo na način koji je teško otkazati?</li><li data-sr="Da li dokumenti imaju očigledne greške ili generičke šablone?" data-en="Do documents have obvious errors or generic templates?">Da li dokumenti imaju očigledne greške ili generičke šablone?</li><li data-sr="Da li mogu da sačekam 24 sata pre uplate?" data-en="Can I wait 24 hours before paying?">Da li mogu da sačekam 24 sata pre uplate?</li><li data-sr="Da li znam tačnu adresu i pravni subjekt primaoca?" data-en="Do I know the exact address and legal entity of the recipient?">Da li znam tačnu adresu i pravni subjekt primaoca?</li><li data-sr="Da li je cena daleko ispod tržišne bez razloga?" data-en="Is the price far below market with no explanation?">Da li je cena daleko ispod tržišne bez razloga?</li><li data-sr="Da li su svi učesnici stranci bez prethodnog konteksta?" data-en="Are all participants strangers with no prior context?">Da li su svi učesnici stranci bez prethodnog konteksta?</li><li data-sr="Da li osećam stid ili strah da pitam za pauzu?" data-en="Do I feel shame or fear to ask for a pause?">Da li osećam stid ili strah da pitam za pauzu?</li><li data-sr="Da li bih savetovao prijatelju da prihvati isti scenario?" data-en="Would I advise a friend to accept the same scenario?">Da li bih savetovao prijatelju da prihvati isti scenario?</li><li data-sr="Da li postoji alternativa preko zvaničnog portala ili poziva službi?" data-en="Is there an alternative via an official portal or service call?">Da li postoji alternativa preko zvaničnog portala ili poziva službi?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Ako sumnja krene: redosled poteza" data-en="If suspicion starts: order of steps">Ako sumnja krene: redosled poteza</h2>
      <ol class="steps">
        
        <li data-sr="Prekini interakciju i udalji se ka zatvorenom javnom mestu sa osobljem." data-en="End the interaction and move toward a staffed indoor public place.">Prekini interakciju i udalji se ka zatvorenom javnom mestu sa osobljem.</li>
        <li data-sr="Drži torbu i novčanik pred sobom i ne daj telefon strancu da pozove." data-en="Keep bag and wallet in front of you and do not give your phone to a stranger to call.">Drži torbu i novčanik pred sobom i ne daj telefon strancu da pozove.</li>
        <li data-sr="Ne izvlači novac na ulici i ne pokazuj sadržaj novčanika." data-en="Do not withdraw or display cash on the street.">Ne izvlači novac na ulici i ne pokazuj sadržaj novčanika.</li>
        <li data-sr="Ako si u grupi, dogovorite se da jedna osoba uvek pazi na prtljag." data-en="In a group, agree one person always watches the luggage.">Ako si u grupi, dogovorite se da jedna osoba uvek pazi na prtljag.</li>
        <li data-sr="Prijavi incident policiji sa opisom lica i pravca odlaska." data-en="Report the incident to police with a description and direction of travel.">Prijavi incident policiji sa opisom lica i pravca odlaska.</li>
      </ol>
    </section>
    <section class="card">
      <h2 data-sr="Ako pokušavaš da pomogneš nekome" data-en="If you are trying to help someone">Ako pokušavaš da pomogneš nekome</h2>
      <div class="grid-2">
        <div class="phase">
          <div class="label" data-sr="Pitanja koja pomažu" data-en="Helpful questions">Pitanja koja pomažu</div>
          <ul class="bullets">
            <li data-sr="Da li je osoba već platila ili pustila nekoga unutra?" data-en="Has the person already paid or let someone inside?">Da li je osoba već platila ili pustila nekoga unutra?</li>
            <li data-sr="Da li postoji pritisak da se odmah odluči bez konsultacije?" data-en="Is there pressure to decide immediately without consulting anyone?">Da li postoji pritisak da se odmah odluči bez konsultacije?</li>
            <li data-sr="Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?" data-en="Did they ask for cash, vouchers, or payment to a third-party account?">Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?</li>
            <li data-sr="Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?" data-en="Can identity be verified via an official number from the agency or company website?">Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?</li>
          </ul>
        </div>
        <div class="phase">
          <div class="label" data-sr="Rečenice koje rade" data-en="Phrases that work">Rečenice koje rade</div>
          <ul class="bullets">
            <li data-sr="Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno." data-en="Let us first close the door and call the official number together.">Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno.</li>
            <li data-sr="Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja." data-en="A real agency or firm allows a pause and written appointment confirmation.">Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja.</li>
            <li data-sr="Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno." data-en="We pay nothing until identity and authority are verified independently.">Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno.</li>
            <li data-sr="Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja." data-en="If you feel street pressure, enter a shop or bank and ask staff for help.">Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja.</li>
          </ul>
        </div>
      </div>
    </section>
`
};
