window.SCAM_CONTENT = window.SCAM_CONTENT || {};

window.SCAM_CONTENT["doorstep-paving-scam"] = {
  raw_html: `
    <section class="card">
      <h2 data-sr="Uvod: Prevara asfaltiranjem na vratima" data-en="Introduction: Doorstep paving scam">Uvod: Prevara asfaltiranjem na vratima</h2>
      <p data-sr="Ekipa nudi jeftino asfaltiranje uz priču o višku materijala i pritisak za gotovinu." data-en="A crew offers cheap tarmac with a leftover-material story and cash pressure.">Ekipa nudi jeftino asfaltiranje uz priču o višku materijala i pritisak za gotovinu.</p>
      <div class="callout" data-sr="<strong>Model:</strong> hladni poziv → usmeni dogovor → avans → loš rad → pritisak ili nestanak" data-en="<strong>Model:</strong> cold call → verbal deal → advance → poor work → pressure or vanish"><strong>Model:</strong> hladni poziv → usmeni dogovor → avans → loš rad → pritisak ili nestanak</div>
    </section>
    <section class="card">
      <h2 data-sr="Hronološki tok (faze + grananja)" data-en="Timeline (phases + branching)">Hronološki tok (faze + grananja)</h2>
      
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 1 — Hladni kontakt" data-en="Phase 1 — Cold contact">Faza 1 — Hladni kontakt</h3>
        <p data-sr="Ekipa dolazi na vrata sa pričom o višku asfalta ili ploča i nudi posao bez tvog upita." data-en="A crew arrives at the door with a story about leftover asphalt or pavers and offers work you did not request.">Ekipa dolazi na vrata sa pričom o višku asfalta ili ploča i nudi posao bez tvog upita.</p>
        <ul class="bullets"><li data-sr="Nema poziva ili pisma koje si očekivao." data-en="There is no call or letter you expected.">Nema poziva ili pisma koje si očekivao.</li><li data-sr="Cena je znatno ispod tržišne jer imaju višak materijala." data-en="Price is far below market because they have leftover materials. ">Cena je znatno ispod tržišne jer imaju višak materijala.</li><li data-sr="Kamion ili tablice nisu lokalne ili se menjaju." data-en="Truck or plates are not local or keep changing.">Kamion ili tablice nisu lokalne ili se menjaju.</li><li data-sr="Pokazuju fotografije radova koje ne možeš proveriti." data-en="They show photos of jobs you cannot verify.">Pokazuju fotografije radova koje ne možeš proveriti.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta pristaje da čuje ponudu ili pusti ekipu u dvorište." data-en="<strong>Phase threshold:</strong> The target agrees to hear an offer or lets the crew into the yard."><strong>Prag faze:</strong> Meta pristaje da čuje ponudu ili pusti ekipu u dvorište.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="home-improvement-scam.html" data-sr="Prevara sa adaptacijom stana — širi obrazac izvođača" data-en="Home improvement scam — broader contractor pattern">Prevara sa adaptacijom stana — širi obrazac izvođača</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 2 — Pregled i verbalni dogovor" data-en="Phase 2 — Inspection and verbal deal">Faza 2 — Pregled i verbalni dogovor</h3>
        <p data-sr="Brzo procenjuju radove i daju usmenu cenu bez detaljnog opisa obima." data-en="They quickly assess work and give a verbal price without a detailed scope.">Brzo procenjuju radove i daju usmenu cenu bez detaljnog opisa obima.</p>
        <ul class="bullets"><li data-sr="Ne meraju tačno površinu ili debljinu sloja." data-en="They do not accurately measure area or layer thickness.">Ne meraju tačno površinu ili debljinu sloja.</li><li data-sr="Izbegavaju pisanu specifikaciju materijala." data-en="They avoid a written material specification.">Izbegavaju pisanu specifikaciju materijala.</li><li data-sr="Dogovor je pod pritiskom samo danas." data-en="The deal is under today only pressure.">Dogovor je pod pritiskom samo danas.</li><li data-sr="Ne daju adresu sedišta firme koja se može proveriti." data-en="They give no verifiable company address.">Ne daju adresu sedišta firme koja se može proveriti.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta prihvata usmeni dogovor bez pisanog ugovora." data-en="<strong>Phase threshold:</strong> The target accepts a verbal deal with no written contract."><strong>Prag faze:</strong> Meta prihvata usmeni dogovor bez pisanog ugovora.</div>
        
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 3 — Početak rada i zahtev za avans" data-en="Phase 3 — Work starts and advance demand">Faza 3 — Početak rada i zahtev za avans</h3>
        <p data-sr="Kreću radovi uz traženje velikog avansa za gorivo, materijal ili rezervaciju ekipe." data-en="Work starts with a large advance for fuel, materials, or crew booking.">Kreću radovi uz traženje velikog avansa za gorivo, materijal ili rezervaciju ekipe.</p>
        <ul class="bullets"><li data-sr="Traže pun avans pre značajnog napretka." data-en="They want full advance before meaningful progress.">Traže pun avans pre značajnog napretka.</li><li data-sr="Gotovina je jedini prihvatljiv način." data-en="Cash is the only acceptable method.">Gotovina je jedini prihvatljiv način.</li><li data-sr="Ne izdaju predračun sa PIB-om." data-en="They issue no quote with a tax ID.">Ne izdaju predračun sa PIB-om.</li><li data-sr="Rad zapravo traje kratko ili je samo pozornica." data-en="Work is short or only for show.">Rad zapravo traje kratko ili je samo pozornica.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta plaća avans ili potpisuje obavezu plaćanja." data-en="<strong>Phase threshold:</strong> The target pays an advance or signs a payment obligation."><strong>Prag faze:</strong> Meta plaća avans ili potpisuje obavezu plaćanja.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="deposit-scam.html" data-sr="Prevara sa depozitom" data-en="Deposit scam">Prevara sa depozitom</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 4 — Loš kvalitet ili nedovršeno" data-en="Phase 4 — Poor quality or unfinished">Faza 4 — Loš kvalitet ili nedovršeno</h3>
        <p data-sr="Materijal je razređen, sloj je tanak ili krov je samo zakrpljen privremenim trakama." data-en="Material is thin, the layer is shallow, or the roof is only patched with temporary strips.">Materijal je razređen, sloj je tanak ili krov je samo zakrpljen privremenim trakama.</p>
        <ul class="bullets"><li data-sr="Posle kiše problem se vraća." data-en="After rain the problem returns.">Posle kiše problem se vraća.</li><li data-sr="Odbijaju ispravke bez dodatne uplate." data-en="They refuse fixes without extra payment.">Odbijaju ispravke bez dodatne uplate.</li><li data-sr="Nestaju sa gradilišta po hitnom pozivu." data-en="They vanish from the site on an urgent call. ">Nestaju sa gradilišta po hitnom pozivu.</li><li data-sr="Koriste otpadni ili pogrešan materijal." data-en="They use waste or wrong materials.">Koriste otpadni ili pogrešan materijal.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva vidi da rad ne odgovara obećanom." data-en="<strong>Phase threshold:</strong> The victim sees work does not match what was promised."><strong>Prag faze:</strong> Žrtva vidi da rad ne odgovara obećanom.</div>
        
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 5 — Pritisak za još novca ili nestanak" data-en="Phase 5 — Pressure for more money or disappearance">Faza 5 — Pritisak za još novca ili nestanak</h3>
        <p data-sr="Traže dodatne stavke koje nisu bile uključene ili potpuno prekidaju kontakt." data-en="They ask for add-ons not included or cut contact completely.">Traže dodatne stavke koje nisu bile uključene ili potpuno prekidaju kontakt.</p>
        <ul class="bullets"><li data-sr="Svaki novi problem zahteva novu uplatu." data-en="Every new problem needs a new payment.">Svaki novi problem zahteva novu uplatu.</li><li data-sr="Prete tužbom ili zadržavanjem opreme." data-en="They threaten suit or holding equipment.">Prete tužbom ili zadržavanjem opreme.</li><li data-sr="Brojevi i sajt nestaju." data-en="Numbers and websites disappear.">Brojevi i sajt nestaju.</li><li data-sr="Recovery prevarant može kasnije ponuditi pomoć." data-en="Recovery scammers may later offer help. ">Recovery prevarant može kasnije ponuditi pomoć.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva prestaje da dobija odgovore ili plaća više uz strah." data-en="<strong>Phase threshold:</strong> The victim stops getting replies or pays more out of fear."><strong>Prag faze:</strong> Žrtva prestaje da dobija odgovore ili plaća više uz strah.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="recovery-scam.html" data-sr="Prevara povraćaja" data-en="Recovery scam">Prevara povraćaja</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 6 — Pravne i potrošačke opcije" data-en="Phase 6 — Legal and consumer options">Faza 6 — Pravne i potrošačke opcije</h3>
        <p data-sr="Prijava policiji, potrošačkoj organizaciji i lokalnoj inspekciji; fotografije i ugovor su dokaz." data-en="Reports to police, consumer bodies, and local inspection; photos and contracts are evidence.">Prijava policiji, potrošačkoj organizaciji i lokalnoj inspekciji; fotografije i ugovor su dokaz.</p>
        <ul class="bullets"><li data-sr="Fotografiši stanje pre i posle rada." data-en="Photograph the state before and after work.">Fotografiši stanje pre i posle rada.</li><li data-sr="Zatraži drugo mišljenje licenciranog izvođača." data-en="Ask a second opinion from a licensed contractor.">Zatraži drugo mišljenje licenciranog izvođača.</li><li data-sr="Proveri firmu u poslovnom registru pre bilo kakve preostale uplate." data-en="Check the firm in a business register before any remaining payment.">Proveri firmu u poslovnom registru pre bilo kakve preostale uplate.</li><li data-sr="Deli upozorenje u lokalnoj zajednici." data-en="Share a warning in the local community.">Deli upozorenje u lokalnoj zajednici.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva dokumentuje štetu i traži savet nezavisnog stručnjaka." data-en="<strong>Phase threshold:</strong> The victim documents damage and seeks independent expert advice."><strong>Prag faze:</strong> Žrtva dokumentuje štetu i traži savet nezavisnog stručnjaka.</div>
        
      </article>
    </section>
    <section class="card">
      <h2 data-sr="Crvene zastavice" data-en="Red flags">Crvene zastavice</h2>
      <ul class="bullets"><li data-sr="Nepozvan posetilac traži hitan ulazak ili uplatu odmah." data-en="Unsolicited visitor demands urgent entry or immediate payment.">Nepozvan posetilac traži hitan ulazak ili uplatu odmah.</li><li data-sr="Plaćanje isključivo gotovinom na pragu." data-en="Payment only as cash on the doorstep.">Plaćanje isključivo gotovinom na pragu.</li><li data-sr="Kartica identifikacije izgleda samostalno štampana ili bez holograma." data-en="ID card looks self-printed or lacks normal security features.">Kartica identifikacije izgleda samostalno štampana ili bez holograma.</li><li data-sr="Odbijaju da sačekaju dok ti proveriš broj na zvaničnom sajtu." data-en="They refuse to wait while you verify a number on the official website.">Odbijaju da sačekaju dok ti proveriš broj na zvaničnom sajtu.</li><li data-sr="Pritisak zbog curenja, opasnosti ili kazne ako ne pustiš unutra." data-en="Pressure about a leak, danger, or penalty if you do not let them in.">Pritisak zbog curenja, opasnosti ili kazne ako ne pustiš unutra.</li><li data-sr="Nude popust ako platiš danas, bez pisanog ugovora." data-en="They offer a discount if you pay today with no written contract.">Nude popust ako platiš danas, bez pisanog ugovora.</li><li data-sr="Ne mogu da navedu broj zakazivanja koji se poklapa sa evidencijom kompanije." data-en="They cannot give an appointment number that matches company records.">Ne mogu da navedu broj zakazivanja koji se poklapa sa evidencijom kompanije.</li><li data-sr="Traže da potpišeš punomoćje ili pristup brojilu bez objašnjenja." data-en="They ask you to sign a mandate or grant meter access without explanation.">Traže da potpišeš punomoćje ili pristup brojilu bez objašnjenja.</li><li data-sr="Kombinuju tehnički žargon da zbune i ubrzaju odluku." data-en="They mix technical jargon to confuse and speed the decision.">Kombinuju tehnički žargon da zbune i ubrzaju odluku.</li><li data-sr="Više osoba dolazi ne najavljeno i menja uloge u razgovoru." data-en="Several people arrive unannounced and swap roles in the conversation.">Više osoba dolazi ne najavljeno i menja uloge u razgovoru.</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Provere: 8 brzih provera" data-en="Checks: 8 quick checks">Provere: 8 brzih provera</h2>
      <ul class="bullets"><li data-sr="Da li postoji zakazivanje koje možeš potvrditi kod kompanije?" data-en="Is there an appointment you can confirm with the company?">Da li postoji zakazivanje koje možeš potvrditi kod kompanije?</li><li data-sr="Da li broj na kartici odgovara broju na zvaničnom sajtu?" data-en="Does the card number match the number on the official website?">Da li broj na kartici odgovara broju na zvaničnom sajtu?</li><li data-sr="Da li bi prava služba tražila uplatu isključivo gotovinom na pragu?" data-en="Would a real agency demand only cash on the doorstep?">Da li bi prava služba tražila uplatu isključivo gotovinom na pragu?</li><li data-sr="Da li možeš odložiti ulazak do dolaska člana porodice ili komšije?" data-en="Can you delay entry until a family member or neighbour arrives?">Da li možeš odložiti ulazak do dolaska člana porodice ili komšije?</li><li data-sr="Da li rad zahteva dozvolu koju možeš proveriti kod nadležnog tela?" data-en="Does the work require a permit verifiable with the competent authority?">Da li rad zahteva dozvolu koju možeš proveriti kod nadležnog tela?</li><li data-sr="Da li postoji drugi stanovnik u zgradi sa istim hitnim obaveštenjem?" data-en="Is another resident in the building reporting the same urgent notice?">Da li postoji drugi stanovnik u zgradi sa istim hitnim obaveštenjem?</li><li data-sr="Da li ugovor ima jasnu adresu firme i PIB ili registarski broj?" data-en="Does the contract show a clear company address and tax or registry ID?">Da li ugovor ima jasnu adresu firme i PIB ili registarski broj?</li><li data-sr="Da li bi legitimni izvođač tražio pun avans pre bilo kakvog pisanog ugovora?" data-en="Would a legitimate contractor demand full advance before any written contract?">Da li bi legitimni izvođač tražio pun avans pre bilo kakvog pisanog ugovora?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Checklista: 12 pitanja" data-en="Checklist: 12 questions">Checklista: 12 pitanja</h2>
      <ul class="bullets"><li data-sr="Da li sam nezavisno proverio identitet pre bilo kakve uplate?" data-en="Have I independently verified identity before any payment?">Da li sam nezavisno proverio identitet pre bilo kakve uplate?</li><li data-sr="Da li sam razgovarao sa nekim od poverenja?" data-en="Have I spoken to someone I trust?">Da li sam razgovarao sa nekim od poverenja?</li><li data-sr="Da li postoji pritisak za odluku istog dana?" data-en="Is there same-day decision pressure?">Da li postoji pritisak za odluku istog dana?</li><li data-sr="Da li je plaćanje traženo na način koji je teško otkazati?" data-en="Is payment requested in a hard-to-reverse way?">Da li je plaćanje traženo na način koji je teško otkazati?</li><li data-sr="Da li dokumenti imaju očigledne greške ili generičke šablone?" data-en="Do documents have obvious errors or generic templates?">Da li dokumenti imaju očigledne greške ili generičke šablone?</li><li data-sr="Da li mogu da sačekam 24 sata pre uplate?" data-en="Can I wait 24 hours before paying?">Da li mogu da sačekam 24 sata pre uplate?</li><li data-sr="Da li znam tačnu adresu i pravni subjekt primaoca?" data-en="Do I know the exact address and legal entity of the recipient?">Da li znam tačnu adresu i pravni subjekt primaoca?</li><li data-sr="Da li je cena daleko ispod tržišne bez razloga?" data-en="Is the price far below market with no explanation?">Da li je cena daleko ispod tržišne bez razloga?</li><li data-sr="Da li su svi učesnici stranci bez prethodnog konteksta?" data-en="Are all participants strangers with no prior context?">Da li su svi učesnici stranci bez prethodnog konteksta?</li><li data-sr="Da li osećam stid ili strah da pitam za pauzu?" data-en="Do I feel shame or fear to ask for a pause?">Da li osećam stid ili strah da pitam za pauzu?</li><li data-sr="Da li bih savetovao prijatelju da prihvati isti scenario?" data-en="Would I advise a friend to accept the same scenario?">Da li bih savetovao prijatelju da prihvati isti scenario?</li><li data-sr="Da li postoji alternativa preko zvaničnog portala ili poziva službi?" data-en="Is there an alternative via an official portal or service call?">Da li postoji alternativa preko zvaničnog portala ili poziva službi?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Ako sumnja krene: redosled poteza" data-en="If suspicion starts: order of steps">Ako sumnja krene: redosled poteza</h2>
      <ol class="steps">
        
        <li data-sr="Zaključaj vrata i razgovaraj kroz interfon ili špijunku bez otvaranja." data-en="Keep the door locked and speak through the intercom or viewer without opening.">Zaključaj vrata i razgovaraj kroz interfon ili špijunku bez otvaranja.</li>
        <li data-sr="Pozovi zvanični broj kompanije ili institucije sa njihovog sajta, ne broj sa kartice posetioca." data-en="Call the official company or agency number from their website, not from the visitor's card.">Pozovi zvanični broj kompanije ili institucije sa njihovog sajta, ne broj sa kartice posetioca.</li>
        <li data-sr="Zatraži pisano obaveštenje ili ID koji možeš nezavisno proveriti pre ulaska." data-en="Ask for written notice or ID you can verify independently before entry.">Zatraži pisano obaveštenje ili ID koji možeš nezavisno proveriti pre ulaska.</li>
        <li data-sr="Ne plaćaj gotovinu na pragu i ne potpisuj ugovor pod pritiskom istog dana." data-en="Do not pay cash on the doorstep or sign a contract under same-day pressure.">Ne plaćaj gotovinu na pragu i ne potpisuj ugovor pod pritiskom istog dana.</li>
        <li data-sr="Prijavi sumnjivu posetu policiji i, gde postoji, potrošačkoj organizaciji." data-en="Report a suspicious visit to police and, where available, a consumer organisation.">Prijavi sumnjivu posetu policiji i, gde postoji, potrošačkoj organizaciji.</li>
      </ol>
    </section>
    <section class="card">
      <h2 data-sr="Ako pokušavaš da pomogneš nekome" data-en="If you are trying to help someone">Ako pokušavaš da pomogneš nekome</h2>
      <div class="grid-2">
        <div class="phase">
          <div class="label" data-sr="Pitanja koja pomažu" data-en="Helpful questions">Pitanja koja pomažu</div>
          <ul class="bullets">
            <li data-sr="Da li je osoba već platila ili pustila nekoga unutra?" data-en="Has the person already paid or let someone inside?">Da li je osoba već platila ili pustila nekoga unutra?</li>
            <li data-sr="Da li postoji pritisak da se odmah odluči bez konsultacije?" data-en="Is there pressure to decide immediately without consulting anyone?">Da li postoji pritisak da se odmah odluči bez konsultacije?</li>
            <li data-sr="Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?" data-en="Did they ask for cash, vouchers, or payment to a third-party account?">Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?</li>
            <li data-sr="Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?" data-en="Can identity be verified via an official number from the agency or company website?">Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?</li>
          </ul>
        </div>
        <div class="phase">
          <div class="label" data-sr="Rečenice koje rade" data-en="Phrases that work">Rečenice koje rade</div>
          <ul class="bullets">
            <li data-sr="Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno." data-en="Let us first close the door and call the official number together.">Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno.</li>
            <li data-sr="Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja." data-en="A real agency or firm allows a pause and written appointment confirmation.">Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja.</li>
            <li data-sr="Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno." data-en="We pay nothing until identity and authority are verified independently.">Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno.</li>
            <li data-sr="Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja." data-en="If you feel street pressure, enter a shop or bank and ask staff for help.">Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja.</li>
          </ul>
        </div>
      </div>
    </section>
`
};
