window.SCAM_CONTENT = window.SCAM_CONTENT || {};

window.SCAM_CONTENT["equipment-reimbursement-scam"] = {
  raw_html: `
    <section class="card">
      <h2 data-sr="Uvod: naknada za opremu" data-en="Introduction: equipment reimbursement">Uvod: naknada za opremu</h2>
      <p data-sr="Žrtva kupuje skupu opremu prema uputstvu lažnog poslodavca; naknada je izmišljena i prodavac je često deo iste šeme." data-en="The victim buys expensive gear per a fake employer; reimbursement is fictional and the seller is often part of the scheme.">Žrtva kupuje skupu opremu prema uputstvu lažnog poslodavca; naknada je izmišljena i prodavac je često deo iste šeme.</p>
      <div class="callout" data-sr="<strong>Model:</strong> ponuda → kupovina → lažna potvrda → odlaganje → nestanak" data-en="<strong>Model:</strong> offer → purchase → fake confirmation → delay → disappearance"><strong>Model:</strong> ponuda → kupovina → lažna potvrda → odlaganje → nestanak</div>
    </section>
    <section class="card">
      <h2 data-sr="Hronološki tok (faze + grananja)" data-en="Timeline (phases + branching)">Hronološki tok (faze + grananja)</h2>
      
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 1 — Ponuda zaposlenja" data-en="Phase 1 — Employment offer">Faza 1 — Ponuda zaposlenja</h3>
        <p data-sr="Lažni poslodavac šalje ponudu sa listom opreme koju navodno koristi firma." data-en="A fake employer sends an offer with an equipment list the firm supposedly uses.">Lažni poslodavac šalje ponudu sa listom opreme koju navodno koristi firma.</p>
        <ul class="bullets"><li data-sr="Lista uključuje laptop, monitor, telefon ili specijalizovani softver." data-en="The list includes laptop, monitor, phone, or specialised software.">Lista uključuje laptop, monitor, telefon ili specijalizovani softver.</li><li data-sr="Tvrdi se da će firma naknaditi troškove posle kupovine." data-en="They claim the firm will reimburse costs after purchase.">Tvrdi se da će firma naknaditi troškove posle kupovine.</li><li data-sr="Kontakt nije sa zvaničnog domena." data-en="Contact is not from the official domain.">Kontakt nije sa zvaničnog domena.</li><li data-sr="Hitnost oko prvog radnog dana." data-en="Urgency about the first working day.">Hitnost oko prvog radnog dana.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta prihvata da kupi opremu uz obećanje naknade." data-en="<strong>Phase threshold:</strong> The target agrees to buy equipment with a reimbursement promise."><strong>Prag faze:</strong> Meta prihvata da kupi opremu uz obećanje naknade.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="recruitment-scam.html" data-sr="Prevara sa regrutovanjem" data-en="Recruitment scam">Prevara sa regrutovanjem</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 2 — Uputstvo za kupovinu" data-en="Phase 2 — Purchase instructions">Faza 2 — Uputstvo za kupovinu</h3>
        <p data-sr="Daju link ka prodavcu, ovlašćenom dobavljaču ili traže uplatu na određeni račun." data-en="They give a link to a seller, an authorised supplier, or ask payment to a given account.">Daju link ka prodavcu, ovlašćenom dobavljaču ili traže uplatu na određeni račun.</p>
        <ul class="bullets"><li data-sr="Prodavac je nepoznat ili je domen novoregistrovan." data-en="The seller is unknown or the domain is newly registered.">Prodavac je nepoznat ili je domen novoregistrovan.</li><li data-sr="Cene su bliske maloprodaji ali sa lažnim sajtovima." data-en="Prices are near retail but on fake sites.">Cene su bliske maloprodaji ali sa lažnim sajtovima.</li><li data-sr="Traže gotovinsku uplatu ili P2P umesto korporativne nabavke." data-en="They want cash or P2P instead of corporate procurement.">Traže gotovinsku uplatu ili P2P umesto korporativne nabavke.</li><li data-sr="Ne šalju porudžbenicu sa pečatom poslodavca." data-en="They send no purchase order with employer stamp.">Ne šalju porudžbenicu sa pečatom poslodavca.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta plaća prodavcu ili šalje novac na navedeni račun." data-en="<strong>Phase threshold:</strong> The target pays the seller or sends money to the stated account."><strong>Prag faze:</strong> Meta plaća prodavcu ili šalje novac na navedeni račun.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="fake-webshop.html" data-sr="Lažna veb prodavnica" data-en="Fake webshop">Lažna veb prodavnica</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 3 — Lažna potvrda kupovine" data-en="Phase 3 — Fake purchase confirmation">Faza 3 — Lažna potvrda kupovine</h3>
        <p data-sr="Šalju imejl koji izgleda kao potvrda ali nije sa pravog domena poslodavca." data-en="They send an email that looks like confirmation but not from the real employer domain.">Šalju imejl koji izgleda kao potvrda ali nije sa pravog domena poslodavca.</p>
        <ul class="bullets"><li data-sr="PDF ili slika umesto sistema za nabavku." data-en="A PDF or image instead of a procurement system.">PDF ili slika umesto sistema za nabavku.</li><li data-sr="Traže još jednu uplatu zbog carine ili osiguranja." data-en="Another payment is requested for customs or insurance. ">Traže još jednu uplatu zbog carine ili osiguranja.</li><li data-sr="Brojevi računa se menjaju između poruka." data-en="Account numbers change between messages.">Brojevi računa se menjaju između poruka.</li><li data-sr="Odbijaju korporativni proces refundacije." data-en="They refuse a corporate reimbursement process.">Odbijaju korporativni proces refundacije.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta plaća dodatnu naknadu ili šalje još jednu uplatu." data-en="<strong>Phase threshold:</strong> The target pays an extra fee or sends another payment."><strong>Prag faze:</strong> Meta plaća dodatnu naknadu ili šalje još jednu uplatu.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="advance-fee-fraud.html" data-sr="Uplata unapred" data-en="Advance fee fraud">Uplata unapred</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 4 — Odlaganje naknade" data-en="Phase 4 — Reimbursement delay">Faza 4 — Odlaganje naknade</h3>
        <p data-sr="Izgovori uključuju odeljenje finansija, praznike ili grešku u broju računa." data-en="Excuses include finance department delays, holidays, or an account number error.">Izgovori uključuju odeljenje finansija, praznike ili grešku u broju računa.</p>
        <ul class="bullets"><li data-sr="Svaki rok za naknadu se pomera." data-en="Every reimbursement deadline shifts.">Svaki rok za naknadu se pomera.</li><li data-sr="Traže kopiju računa pa i dalje ne isplate." data-en="They ask for receipt copies and still do not pay.">Traže kopiju računa pa i dalje ne isplate.</li><li data-sr="Pominju verifikacionu naknadu pre isplate." data-en="A verification fee before payout is mentioned.">Pominju verifikacionu naknadu pre isplate.</li><li data-sr="Komunikacija postaje retka." data-en="Communication becomes rare.">Komunikacija postaje retka.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva shvata da naknada ne stiže uprkos dokazima o kupovini." data-en="<strong>Phase threshold:</strong> The victim realises reimbursement never arrives despite purchase proof."><strong>Prag faze:</strong> Žrtva shvata da naknada ne stiže uprkos dokazima o kupovini.</div>
        
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 5 — Nestanak ili nova prevara" data-en="Phase 5 — Disappearance or new scam">Faza 5 — Nestanak ili nova prevara</h3>
        <p data-sr="Kontakt se gasi ili sledi ponuda povraćaja uz novu uplatu." data-en="Contact ends or a refund offer arrives with a new upfront fee.">Kontakt se gasi ili sledi ponuda povraćaja uz novu uplatu.</p>
        <ul class="bullets"><li data-sr="Broj i imejl više ne rade." data-en="Phone and email no longer work.">Broj i imejl više ne rade.</li><li data-sr="Isti ljudi nude pravnu pomoć za povrat." data-en="The same people offer legal help to recover funds.">Isti ljudi nude pravnu pomoć za povrat.</li><li data-sr="Traže predaju pristupa bankovnom nalogu za naknadu." data-en="They ask for bank login for reimbursement. ">Traže predaju pristupa bankovnom nalogu za naknadu.</li><li data-sr="Ponovo koriste isti obrazac pod drugim imenom poslodavca." data-en="They reuse the pattern under another employer name.">Ponovo koriste isti obrazac pod drugim imenom poslodavca.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva gubi novac i opremu koja nije isporučena ili je bezvredna." data-en="<strong>Phase threshold:</strong> The victim loses money and equipment that was not delivered or is worthless."><strong>Prag faze:</strong> Žrtva gubi novac i opremu koja nije isporučena ili je bezvredna.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="recovery-scam.html" data-sr="Prevara povraćaja" data-en="Recovery scam">Prevara povraćaja</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 6 — Zaštita i prijava" data-en="Phase 6 — Protection and reporting">Faza 6 — Zaštita i prijava</h3>
        <p data-sr="Obavesti banku, platformu oglasa i policiju; zamrzni karticu ako je moguće." data-en="Notify the bank, job platform, and police; freeze the card if possible.">Obavesti banku, platformu oglasa i policiju; zamrzni karticu ako je moguće.</p>
        <ul class="bullets"><li data-sr="Sačuvaj sve poruke, račune i bankovne izvode." data-en="Save all messages, invoices, and bank statements.">Sačuvaj sve poruke, račune i bankovne izvode.</li><li data-sr="Prijavi domen i hosting zloupotrebe ako je lažni sajt." data-en="Report domain and hosting abuse if a fake site was used.">Prijavi domen i hosting zloupotrebe ako je lažni sajt.</li><li data-sr="Kontaktiraj pravog poslodavca čije je ime korišćeno." data-en="Contact the real employer whose name was used.">Kontaktiraj pravog poslodavca čije je ime korišćeno.</li><li data-sr="Razmotri prijavu za krađu identiteta ako su predati lični podaci." data-en="Consider identity theft reporting if personal data was given.">Razmotri prijavu za krađu identiteta ako su predati lični podaci.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva dokumentuje lanac uplata i prijavljuje sve kanale." data-en="<strong>Phase threshold:</strong> The victim documents the payment chain and reports to all channels."><strong>Prag faze:</strong> Žrtva dokumentuje lanac uplata i prijavljuje sve kanale.</div>
        
      </article>
    </section>
    <section class="card">
      <h2 data-sr="Crvene zastavice" data-en="Red flags">Crvene zastavice</h2>
      <ul class="bullets"><li data-sr="Intervju je samo čet i odmah sledi link za instalaciju." data-en="Interview is chat-only and a software link follows immediately.">Intervju je samo čet i odmah sledi link za instalaciju.</li><li data-sr="Traže administratorske privilegije ili isključivanje antivirusa." data-en="They ask for administrator rights or disabling antivirus.">Traže administratorske privilegije ili isključivanje antivirusa.</li><li data-sr="Fajl nije potpisan poznatim izdavačem ili je izvršni fajl sa nepoznatog hostinga." data-en="File is not signed by a known publisher or is an executable from unknown hosting.">Fajl nije potpisan poznatim izdavačem ili je izvršni fajl sa nepoznatog hostinga.</li><li data-sr="Posao zvuči previše dobro uz minimalnu proveru kvalifikacija." data-en="Job sounds too good with minimal qualification checks.">Posao zvuči previše dobro uz minimalnu proveru kvalifikacija.</li><li data-sr="Kontakt imejl ne koristi domen poslodavca." data-en="Contact email does not use the employer domain.">Kontakt imejl ne koristi domen poslodavca.</li><li data-sr="Traže kupovinu opreme pre potpisanog ugovora o radu." data-en="They want equipment bought before a signed employment contract.">Traže kupovinu opreme pre potpisanog ugovora o radu.</li><li data-sr="Naknada se traži preko preplaćenog čeka, poklon kartice ili P2P." data-en="Reimbursement is via overpayment, gift card, or P2P only.">Naknada se traži preko preplaćenog čeka, poklon kartice ili P2P.</li><li data-sr="Odbijaju video poziv sa kamerom lica." data-en="They refuse a video call showing their face.">Odbijaju video poziv sa kamerom lica.</li><li data-sr="Hitno traže odluku u roku od nekoliko sati." data-en="They demand a decision within a few hours.">Hitno traže odluku u roku od nekoliko sati.</li><li data-sr="Posle uplate kontakt prestaje ili traže još jednu uplatu." data-en="After payment contact stops or another fee appears.">Posle uplate kontakt prestaje ili traže još jednu uplatu.</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Provere: 8 brzih provera" data-en="Checks: 8 quick checks">Provere: 8 brzih provera</h2>
      <ul class="bullets"><li data-sr="Da li poslodavac potvrđuje poziciju na zvaničnom kanalu?" data-en="Does the employer confirm the role on an official channel?">Da li poslodavac potvrđuje poziciju na zvaničnom kanalu?</li><li data-sr="Da li URL preuzimanja pripada domenu kompanije?" data-en="Does the download URL belong to the company domain?">Da li URL preuzimanja pripada domenu kompanije?</li><li data-sr="Da li potpis softvera možeš proveriti u operativnom sistemu?" data-en="Can you verify the software signature in the operating system?">Da li potpis softvera možeš proveriti u operativnom sistemu?</li><li data-sr="Da li bi pravi HR tražio instalaciju pre potpisanog ugovora?" data-en="Would real HR demand installation before a signed contract?">Da li bi pravi HR tražio instalaciju pre potpisanog ugovora?</li><li data-sr="Da li možeš zatražiti video intervju sa zvaničnim HR?" data-en="Can you request a video interview with official HR?">Da li možeš zatražiti video intervju sa zvaničnim HR?</li><li data-sr="Da li naknada za opremu ide samo preko sumnjivog naloga ili kartice?" data-en="Does equipment reimbursement route only through a suspicious account or card?">Da li naknada za opremu ide samo preko sumnjivog naloga ili kartice?</li><li data-sr="Da li postoji pisani sporazum o naknadi troškova pre kupovine?" data-en="Is there a written expense agreement before purchase?">Da li postoji pisani sporazum o naknadi troškova pre kupovine?</li><li data-sr="Da li oglas platforme odgovara stvarnoj objavi poslodavca?" data-en="Does the platform listing match the employer's real posting?">Da li oglas platforme odgovara stvarnoj objavi poslodavca?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Checklista: 12 pitanja" data-en="Checklist: 12 questions">Checklista: 12 pitanja</h2>
      <ul class="bullets"><li data-sr="Da li sam nezavisno proverio identitet pre bilo kakve uplate?" data-en="Have I independently verified identity before any payment?">Da li sam nezavisno proverio identitet pre bilo kakve uplate?</li><li data-sr="Da li sam razgovarao sa nekim od poverenja?" data-en="Have I spoken to someone I trust?">Da li sam razgovarao sa nekim od poverenja?</li><li data-sr="Da li postoji pritisak za odluku istog dana?" data-en="Is there same-day decision pressure?">Da li postoji pritisak za odluku istog dana?</li><li data-sr="Da li je plaćanje traženo na način koji je teško otkazati?" data-en="Is payment requested in a hard-to-reverse way?">Da li je plaćanje traženo na način koji je teško otkazati?</li><li data-sr="Da li dokumenti imaju očigledne greške ili generičke šablone?" data-en="Do documents have obvious errors or generic templates?">Da li dokumenti imaju očigledne greške ili generičke šablone?</li><li data-sr="Da li mogu da sačekam 24 sata pre uplate?" data-en="Can I wait 24 hours before paying?">Da li mogu da sačekam 24 sata pre uplate?</li><li data-sr="Da li znam tačnu adresu i pravni subjekt primaoca?" data-en="Do I know the exact address and legal entity of the recipient?">Da li znam tačnu adresu i pravni subjekt primaoca?</li><li data-sr="Da li je cena daleko ispod tržišne bez razloga?" data-en="Is the price far below market with no explanation?">Da li je cena daleko ispod tržišne bez razloga?</li><li data-sr="Da li su svi učesnici stranci bez prethodnog konteksta?" data-en="Are all participants strangers with no prior context?">Da li su svi učesnici stranci bez prethodnog konteksta?</li><li data-sr="Da li osećam stid ili strah da pitam za pauzu?" data-en="Do I feel shame or fear to ask for a pause?">Da li osećam stid ili strah da pitam za pauzu?</li><li data-sr="Da li bih savetovao prijatelju da prihvati isti scenario?" data-en="Would I advise a friend to accept the same scenario?">Da li bih savetovao prijatelju da prihvati isti scenario?</li><li data-sr="Da li postoji alternativa preko zvaničnog portala ili poziva službi?" data-en="Is there an alternative via an official portal or service call?">Da li postoji alternativa preko zvaničnog portala ili poziva službi?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Ako sumnja krene: redosled poteza" data-en="If suspicion starts: order of steps">Ako sumnja krene: redosled poteza</h2>
      <ol class="steps">
        
        <li data-sr="Ne instaliraj softver i ne daj daljinski pristup tokom intervjua." data-en="Do not install software or grant remote access during an interview.">Ne instaliraj softver i ne daj daljinski pristup tokom intervjua.</li>
        <li data-sr="Potvrdi posao direktno kod poslodavca preko zvaničnog kontakta sa sajta ili HR linije." data-en="Confirm the job directly with the employer via official website or HR line contact.">Potvrdi posao direktno kod poslodavca preko zvaničnog kontakta sa sajta ili HR linije.</li>
        <li data-sr="Sačuvaj poruke, linkove i imejl adrese za prijavu." data-en="Save messages, links, and email addresses for reporting.">Sačuvaj poruke, linkove i imejl adrese za prijavu.</li>
        <li data-sr="Obrisi preuzeti fajl ako sumnjaš i pokreni antimalver sken." data-en="Delete any downloaded file if suspicious and run an antimalware scan.">Obrisi preuzeti fajl ako sumnjaš i pokreni antimalver sken.</li>
        <li data-sr="Prijavi lažni oglas platformi i policiji ili nacionalnoj liniji za cyber kriminal." data-en="Report the fake listing to the platform and to police or a national cybercrime line.">Prijavi lažni oglas platformi i policiji ili nacionalnoj liniji za cyber kriminal.</li>
      </ol>
    </section>
    <section class="card">
      <h2 data-sr="Ako pokušavaš da pomogneš nekome" data-en="If you are trying to help someone">Ako pokušavaš da pomogneš nekome</h2>
      <div class="grid-2">
        <div class="phase">
          <div class="label" data-sr="Pitanja koja pomažu" data-en="Helpful questions">Pitanja koja pomažu</div>
          <ul class="bullets">
            <li data-sr="Da li je osoba već platila ili pustila nekoga unutra?" data-en="Has the person already paid or let someone inside?">Da li je osoba već platila ili pustila nekoga unutra?</li>
            <li data-sr="Da li postoji pritisak da se odmah odluči bez konsultacije?" data-en="Is there pressure to decide immediately without consulting anyone?">Da li postoji pritisak da se odmah odluči bez konsultacije?</li>
            <li data-sr="Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?" data-en="Did they ask for cash, vouchers, or payment to a third-party account?">Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?</li>
            <li data-sr="Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?" data-en="Can identity be verified via an official number from the agency or company website?">Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?</li>
          </ul>
        </div>
        <div class="phase">
          <div class="label" data-sr="Rečenice koje rade" data-en="Phrases that work">Rečenice koje rade</div>
          <ul class="bullets">
            <li data-sr="Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno." data-en="Let us first close the door and call the official number together.">Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno.</li>
            <li data-sr="Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja." data-en="A real agency or firm allows a pause and written appointment confirmation.">Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja.</li>
            <li data-sr="Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno." data-en="We pay nothing until identity and authority are verified independently.">Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno.</li>
            <li data-sr="Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja." data-en="If you feel street pressure, enter a shop or bank and ask staff for help.">Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja.</li>
          </ul>
        </div>
      </div>
    </section>
`
};
