window.SCAM_CONTENT = window.SCAM_CONTENT || {};

window.SCAM_CONTENT["fake-electrician-doorstep-scam"] = {
  raw_html: `
    <section class="card">
      <h2 data-sr="Uvod: Lažni električar na vratima" data-en="Introduction: Fake electrician doorstep scam">Uvod: Lažni električar na vratima</h2>
      <p data-sr="Nepozvani električar priča o opasnoj instalaciji i traži gotovinu za rad koji nije zakazan kod distributera." data-en="An uninvited electrician cites dangerous wiring and asks cash for work not scheduled with the utility.">Nepozvani električar priča o opasnoj instalaciji i traži gotovinu za rad koji nije zakazan kod distributera.</p>
      <div class="callout" data-sr="<strong>Model:</strong> kucanje → lažni autoritet → ulazak ili pritisak → uplata → nestanak" data-en="<strong>Model:</strong> knock → fake authority → entry or pressure → payment → disappearance"><strong>Model:</strong> kucanje → lažni autoritet → ulazak ili pritisak → uplata → nestanak</div>
    </section>
    <section class="card">
      <h2 data-sr="Hronološki tok (faze + grananja)" data-en="Timeline (phases + branching)">Hronološki tok (faze + grananja)</h2>
      
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 1 — Neočekivano kucanje" data-en="Phase 1 — Unexpected knock">Faza 1 — Neočekivano kucanje</h3>
        <p data-sr="Nepoznata osoba kuca i predstavlja se kao električar distributera ili hitna ekipa bez najave koju možeš proveriti kod kompanije ili institucije." data-en="A stranger knocks and presents as utility electrician or emergency crew with no notice you can verify with the company or agency.">Nepoznata osoba kuca i predstavlja se kao električar distributera ili hitna ekipa bez najave koju možeš proveriti kod kompanije ili institucije.</p>
        <ul class="bullets"><li data-sr="Nema pisma ili SMS-a sa zvaničnog kanala pre posete." data-en="There is no letter or SMS from an official channel before the visit.">Nema pisma ili SMS-a sa zvaničnog kanala pre posete.</li><li data-sr="Kartica ili uniforma deluje uverljivo na prvi pogled." data-en="A card or uniform looks convincing at first glance.">Kartica ili uniforma deluje uverljivo na prvi pogled.</li><li data-sr="Posetilac traži brz odgovor jer navodno postoji opasna instalacija ili pretnja isključenjem struje." data-en="The visitor asks for a quick answer because there is allegedly dangerous wiring or a risk of power cut-off.">Posetilac traži brz odgovor jer navodno postoji opasna instalacija ili pretnja isključenjem struje.</li><li data-sr="Predlaže da uđe odmah da proveri ili očita nešto unutra." data-en="They propose entering immediately to check or read something inside.">Predlaže da uđe odmah da proveri ili očita nešto unutra.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta započinje razgovor na vratima bez nezavisne provere." data-en="<strong>Phase threshold:</strong> The target starts a conversation at the door without independent verification."><strong>Prag faze:</strong> Meta započinje razgovor na vratima bez nezavisne provere.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="fake-gas-inspector-scam.html" data-sr="Lažni gasni inspektor" data-en="Fake gas inspector scam">Lažni gasni inspektor</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 2 — Priča o hitnosti" data-en="Phase 2 — Urgency story">Faza 2 — Priča o hitnosti</h3>
        <p data-sr="Pritiska se strah od opasne instalacije ili isključenja struje ili gubitka usluge ako ne pustiš unutra ili ne platiš odmah." data-en="Fear of dangerous wiring or power cut-off or loss of service is used if you do not let them in or pay immediately.">Pritiska se strah od opasne instalacije ili isključenja struje ili gubitka usluge ako ne pustiš unutra ili ne platiš odmah.</p>
        <ul class="bullets"><li data-sr="Rokovi su kratki i sprečavaju konsultaciju sa porodicom." data-en="Deadlines are short and block family consultation.">Rokovi su kratki i sprečavaju konsultaciju sa porodicom.</li><li data-sr="Tvrdi se da su komšije već prihvatile posetu." data-en="They claim neighbours have already accepted a visit.">Tvrdi se da su komšije već prihvatile posetu.</li><li data-sr="Može se pominjati kazna ili isključenje iz mreže." data-en="Fines or disconnection from the grid may be mentioned.">Može se pominjati kazna ili isključenje iz mreže.</li><li data-sr="Ton je zvaničan i koriste se termini koji zvuče kao procedura." data-en="The tone is official and procedure-sounding terms are used.">Ton je zvaničan i koriste se termini koji zvuče kao procedura.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta prihvata da postoji hitan problem koji zahteva akciju danas." data-en="<strong>Phase threshold:</strong> The target accepts there is an urgent problem requiring action today."><strong>Prag faze:</strong> Meta prihvata da postoji hitan problem koji zahteva akciju danas.</div>
        
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 3 — Ulazak ili pristup brojilu" data-en="Phase 3 — Entry or meter access">Faza 3 — Ulazak ili pristup brojilu</h3>
        <p data-sr="Posetilac ulazi u stan, traži pristup plakaru, brojilu ili ormaru i koristi priliku da vidi dokumenta ili vrednosti." data-en="The visitor enters, asks for access to panels, meters, or cupboards and uses the chance to see documents or valuables.">Posetilac ulazi u stan, traži pristup plakaru, brojilu ili ormaru i koristi priliku da vidi dokumenta ili vrednosti.</p>
        <ul class="bullets"><li data-sr="Traži da potpišeš potvrdu obilaska bez čitanja." data-en="They ask you to sign a visit confirmation without reading.">Traži da potpišeš potvrdu obilaska bez čitanja.</li><li data-sr="Fotografiše brojila ili lične podatke bez jasnog pravnog osnova." data-en="They photograph meters or personal data without a clear legal basis.">Fotografiše brojila ili lične podatke bez jasnog pravnog osnova.</li><li data-sr="Jedan član radi dok drugi razgovara sa tobom." data-en="One member works while another talks to you.">Jedan član radi dok drugi razgovara sa tobom.</li><li data-sr="Može se predložiti mala naknada za materijal odmah." data-en="A small fee for materials may be suggested immediately.">Može se predložiti mala naknada za materijal odmah.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta je pustila stranca unutra ili dala pristup osetljivom prostoru." data-en="<strong>Phase threshold:</strong> The target let a stranger inside or gave access to a sensitive area."><strong>Prag faze:</strong> Meta je pustila stranca unutra ili dala pristup osetljivom prostoru.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="fake-audit-inspection-scam.html" data-sr="Lažna revizija ili inspekcija" data-en="Fake audit or inspection scam">Lažna revizija ili inspekcija</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 4 — Zahtev za uplatu" data-en="Phase 4 — Payment demand">Faza 4 — Zahtev za uplatu</h3>
        <p data-sr="Traži se gotovina za delove, taksu, hitnu intervenciju ili zamenu opreme koja nije bila dogovorena pismeno." data-en="Cash is asked for parts, a fee, emergency work, or replacement equipment not agreed in writing.">Traži se gotovina za delove, taksu, hitnu intervenciju ili zamenu opreme koja nije bila dogovorena pismeno.</p>
        <ul class="bullets"><li data-sr="Uplatni podaci vode na privatno lice ili nepoznat račun." data-en="Payment details point to a private person or unknown account.">Uplatni podaci vode na privatno lice ili nepoznat račun.</li><li data-sr="Ne izdaju se faktura pre uplate ili faktura nema PIB." data-en="No invoice is issued before payment or the invoice lacks a tax ID.">Ne izdaju se faktura pre uplate ili faktura nema PIB.</li><li data-sr="Pritisak da platiš pre nego što završe posao." data-en="Pressure to pay before they finish the job.">Pritisak da platiš pre nego što završe posao.</li><li data-sr="Odbijaju karticu ili zvanični portal kompanije." data-en="They refuse a card or the company's official portal.">Odbijaju karticu ili zvanični portal kompanije.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta izdvaja novac ili potpisuje uplatni nalog." data-en="<strong>Phase threshold:</strong> The target hands over money or signs a payment order."><strong>Prag faze:</strong> Meta izdvaja novac ili potpisuje uplatni nalog.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="advance-fee-fraud.html" data-sr="Uplata unapred" data-en="Advance fee fraud">Uplata unapred</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 5 — Nestanak ili loš rad" data-en="Phase 5 — Disappearance or poor work">Faza 5 — Nestanak ili loš rad</h3>
        <p data-sr="Rad je površan, privremen ili se prekida kada je novac uzet; kontakt postaje nedostupan." data-en="Work is superficial, temporary, or stops once money is taken; contact becomes unreachable.">Rad je površan, privremen ili se prekida kada je novac uzet; kontakt postaje nedostupan.</p>
        <ul class="bullets"><li data-sr="Broj telefona se gasi ili ne javlja se na pozive." data-en="The phone number is switched off or does not answer.">Broj telefona se gasi ili ne javlja se na pozive.</li><li data-sr="Isti problem se vraća odmah posle odlaska ekipe." data-en="The same problem returns right after the crew leaves.">Isti problem se vraća odmah posle odlaska ekipe.</li><li data-sr="Nema garancije ili pisane liste urađenog posla." data-en="There is no warranty or written scope of work.">Nema garancije ili pisane liste urađenog posla.</li><li data-sr="Može se pojaviti nova ekipa koja traži dodatni avans." data-en="A new crew may appear asking for another advance.">Može se pojaviti nova ekipa koja traži dodatni avans.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva shvata da novac ili pristup nisu bili opravdani." data-en="<strong>Phase threshold:</strong> The victim realises money or access was not justified."><strong>Prag faze:</strong> Žrtva shvata da novac ili pristup nisu bili opravdani.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="home-improvement-scam.html" data-sr="Prevara sa adaptacijom stana" data-en="Home improvement scam">Prevara sa adaptacijom stana</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 6 — Prijava i prevencija" data-en="Phase 6 — Reporting and prevention">Faza 6 — Prijava i prevencija</h3>
        <p data-sr="Policija, distributer energije ili komunalno preduzeće mogu potvrditi da poseta nije bila zvanična; dokumentacija pomaže povratu i istrazi." data-en="Police or the utility can confirm the visit was not official; documentation helps recovery and investigation.">Policija, distributer energije ili komunalno preduzeće mogu potvrditi da poseta nije bila zvanična; dokumentacija pomaže povratu i istrazi.</p>
        <ul class="bullets"><li data-sr="Sačuvaj opis lica, tablica vozila i vreme posete." data-en="Save descriptions, vehicle plates, and visit time.">Sačuvaj opis lica, tablica vozila i vreme posete.</li><li data-sr="Zatraži zvanični zapis kod pravog dobavljača usluge." data-en="Request an official record from the real service provider.">Zatraži zvanični zapis kod pravog dobavljača usluge.</li><li data-sr="Obavesti komšije i zajednicu da isti tim ne obilazi druge." data-en="Alert neighbours so the same team does not visit others.">Obavesti komšije i zajednicu da isti tim ne obilazi druge.</li><li data-sr="Za budućnost: uvek proveri zakazivanje pre otvaranja vrata." data-en="For the future: always verify appointments before opening the door.">Za budućnost: uvek proveri zakazivanje pre otvaranja vrata.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva prijavljuje incident i deli upozorenje." data-en="<strong>Phase threshold:</strong> The victim reports the incident and shares a warning."><strong>Prag faze:</strong> Žrtva prijavljuje incident i deli upozorenje.</div>
        
      </article>
    </section>
    <section class="card">
      <h2 data-sr="Crvene zastavice" data-en="Red flags">Crvene zastavice</h2>
      <ul class="bullets"><li data-sr="Nepozvan posetilac traži hitan ulazak ili uplatu odmah." data-en="Unsolicited visitor demands urgent entry or immediate payment.">Nepozvan posetilac traži hitan ulazak ili uplatu odmah.</li><li data-sr="Plaćanje isključivo gotovinom na pragu." data-en="Payment only as cash on the doorstep.">Plaćanje isključivo gotovinom na pragu.</li><li data-sr="Kartica identifikacije izgleda samostalno štampana ili bez holograma." data-en="ID card looks self-printed or lacks normal security features.">Kartica identifikacije izgleda samostalno štampana ili bez holograma.</li><li data-sr="Odbijaju da sačekaju dok ti proveriš broj na zvaničnom sajtu." data-en="They refuse to wait while you verify a number on the official website.">Odbijaju da sačekaju dok ti proveriš broj na zvaničnom sajtu.</li><li data-sr="Pritisak zbog curenja, opasnosti ili kazne ako ne pustiš unutra." data-en="Pressure about a leak, danger, or penalty if you do not let them in.">Pritisak zbog curenja, opasnosti ili kazne ako ne pustiš unutra.</li><li data-sr="Nude popust ako platiš danas, bez pisanog ugovora." data-en="They offer a discount if you pay today with no written contract.">Nude popust ako platiš danas, bez pisanog ugovora.</li><li data-sr="Ne mogu da navedu broj zakazivanja koji se poklapa sa evidencijom kompanije." data-en="They cannot give an appointment number that matches company records.">Ne mogu da navedu broj zakazivanja koji se poklapa sa evidencijom kompanije.</li><li data-sr="Traže da potpišeš punomoćje ili pristup brojilu bez objašnjenja." data-en="They ask you to sign a mandate or grant meter access without explanation.">Traže da potpišeš punomoćje ili pristup brojilu bez objašnjenja.</li><li data-sr="Kombinuju tehnički žargon da zbune i ubrzaju odluku." data-en="They mix technical jargon to confuse and speed the decision.">Kombinuju tehnički žargon da zbune i ubrzaju odluku.</li><li data-sr="Više osoba dolazi ne najavljeno i menja uloge u razgovoru." data-en="Several people arrive unannounced and swap roles in the conversation.">Više osoba dolazi ne najavljeno i menja uloge u razgovoru.</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Provere: 8 brzih provera" data-en="Checks: 8 quick checks">Provere: 8 brzih provera</h2>
      <ul class="bullets"><li data-sr="Da li postoji zakazivanje koje možeš potvrditi kod kompanije?" data-en="Is there an appointment you can confirm with the company?">Da li postoji zakazivanje koje možeš potvrditi kod kompanije?</li><li data-sr="Da li broj na kartici odgovara broju na zvaničnom sajtu?" data-en="Does the card number match the number on the official website?">Da li broj na kartici odgovara broju na zvaničnom sajtu?</li><li data-sr="Da li bi prava služba tražila uplatu isključivo gotovinom na pragu?" data-en="Would a real agency demand only cash on the doorstep?">Da li bi prava služba tražila uplatu isključivo gotovinom na pragu?</li><li data-sr="Da li možeš odložiti ulazak do dolaska člana porodice ili komšije?" data-en="Can you delay entry until a family member or neighbour arrives?">Da li možeš odložiti ulazak do dolaska člana porodice ili komšije?</li><li data-sr="Da li rad zahteva dozvolu koju možeš proveriti kod nadležnog tela?" data-en="Does the work require a permit verifiable with the competent authority?">Da li rad zahteva dozvolu koju možeš proveriti kod nadležnog tela?</li><li data-sr="Da li postoji drugi stanovnik u zgradi sa istim hitnim obaveštenjem?" data-en="Is another resident in the building reporting the same urgent notice?">Da li postoji drugi stanovnik u zgradi sa istim hitnim obaveštenjem?</li><li data-sr="Da li ugovor ima jasnu adresu firme i PIB ili registarski broj?" data-en="Does the contract show a clear company address and tax or registry ID?">Da li ugovor ima jasnu adresu firme i PIB ili registarski broj?</li><li data-sr="Da li bi legitimni izvođač tražio pun avans pre bilo kakvog pisanog ugovora?" data-en="Would a legitimate contractor demand full advance before any written contract?">Da li bi legitimni izvođač tražio pun avans pre bilo kakvog pisanog ugovora?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Checklista: 12 pitanja" data-en="Checklist: 12 questions">Checklista: 12 pitanja</h2>
      <ul class="bullets"><li data-sr="Da li sam nezavisno proverio identitet pre bilo kakve uplate?" data-en="Have I independently verified identity before any payment?">Da li sam nezavisno proverio identitet pre bilo kakve uplate?</li><li data-sr="Da li sam razgovarao sa nekim od poverenja?" data-en="Have I spoken to someone I trust?">Da li sam razgovarao sa nekim od poverenja?</li><li data-sr="Da li postoji pritisak za odluku istog dana?" data-en="Is there same-day decision pressure?">Da li postoji pritisak za odluku istog dana?</li><li data-sr="Da li je plaćanje traženo na način koji je teško otkazati?" data-en="Is payment requested in a hard-to-reverse way?">Da li je plaćanje traženo na način koji je teško otkazati?</li><li data-sr="Da li dokumenti imaju očigledne greške ili generičke šablone?" data-en="Do documents have obvious errors or generic templates?">Da li dokumenti imaju očigledne greške ili generičke šablone?</li><li data-sr="Da li mogu da sačekam 24 sata pre uplate?" data-en="Can I wait 24 hours before paying?">Da li mogu da sačekam 24 sata pre uplate?</li><li data-sr="Da li znam tačnu adresu i pravni subjekt primaoca?" data-en="Do I know the exact address and legal entity of the recipient?">Da li znam tačnu adresu i pravni subjekt primaoca?</li><li data-sr="Da li je cena daleko ispod tržišne bez razloga?" data-en="Is the price far below market with no explanation?">Da li je cena daleko ispod tržišne bez razloga?</li><li data-sr="Da li su svi učesnici stranci bez prethodnog konteksta?" data-en="Are all participants strangers with no prior context?">Da li su svi učesnici stranci bez prethodnog konteksta?</li><li data-sr="Da li osećam stid ili strah da pitam za pauzu?" data-en="Do I feel shame or fear to ask for a pause?">Da li osećam stid ili strah da pitam za pauzu?</li><li data-sr="Da li bih savetovao prijatelju da prihvati isti scenario?" data-en="Would I advise a friend to accept the same scenario?">Da li bih savetovao prijatelju da prihvati isti scenario?</li><li data-sr="Da li postoji alternativa preko zvaničnog portala ili poziva službi?" data-en="Is there an alternative via an official portal or service call?">Da li postoji alternativa preko zvaničnog portala ili poziva službi?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Ako sumnja krene: redosled poteza" data-en="If suspicion starts: order of steps">Ako sumnja krene: redosled poteza</h2>
      <ol class="steps">
        
        <li data-sr="Zaključaj vrata i razgovaraj kroz interfon ili špijunku bez otvaranja." data-en="Keep the door locked and speak through the intercom or viewer without opening.">Zaključaj vrata i razgovaraj kroz interfon ili špijunku bez otvaranja.</li>
        <li data-sr="Pozovi zvanični broj kompanije ili institucije sa njihovog sajta, ne broj sa kartice posetioca." data-en="Call the official company or agency number from their website, not from the visitor's card.">Pozovi zvanični broj kompanije ili institucije sa njihovog sajta, ne broj sa kartice posetioca.</li>
        <li data-sr="Zatraži pisano obaveštenje ili ID koji možeš nezavisno proveriti pre ulaska." data-en="Ask for written notice or ID you can verify independently before entry.">Zatraži pisano obaveštenje ili ID koji možeš nezavisno proveriti pre ulaska.</li>
        <li data-sr="Ne plaćaj gotovinu na pragu i ne potpisuj ugovor pod pritiskom istog dana." data-en="Do not pay cash on the doorstep or sign a contract under same-day pressure.">Ne plaćaj gotovinu na pragu i ne potpisuj ugovor pod pritiskom istog dana.</li>
        <li data-sr="Prijavi sumnjivu posetu policiji i, gde postoji, potrošačkoj organizaciji." data-en="Report a suspicious visit to police and, where available, a consumer organisation.">Prijavi sumnjivu posetu policiji i, gde postoji, potrošačkoj organizaciji.</li>
      </ol>
    </section>
    <section class="card">
      <h2 data-sr="Ako pokušavaš da pomogneš nekome" data-en="If you are trying to help someone">Ako pokušavaš da pomogneš nekome</h2>
      <div class="grid-2">
        <div class="phase">
          <div class="label" data-sr="Pitanja koja pomažu" data-en="Helpful questions">Pitanja koja pomažu</div>
          <ul class="bullets">
            <li data-sr="Da li je osoba već platila ili pustila nekoga unutra?" data-en="Has the person already paid or let someone inside?">Da li je osoba već platila ili pustila nekoga unutra?</li>
            <li data-sr="Da li postoji pritisak da se odmah odluči bez konsultacije?" data-en="Is there pressure to decide immediately without consulting anyone?">Da li postoji pritisak da se odmah odluči bez konsultacije?</li>
            <li data-sr="Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?" data-en="Did they ask for cash, vouchers, or payment to a third-party account?">Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?</li>
            <li data-sr="Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?" data-en="Can identity be verified via an official number from the agency or company website?">Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?</li>
          </ul>
        </div>
        <div class="phase">
          <div class="label" data-sr="Rečenice koje rade" data-en="Phrases that work">Rečenice koje rade</div>
          <ul class="bullets">
            <li data-sr="Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno." data-en="Let us first close the door and call the official number together.">Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno.</li>
            <li data-sr="Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja." data-en="A real agency or firm allows a pause and written appointment confirmation.">Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja.</li>
            <li data-sr="Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno." data-en="We pay nothing until identity and authority are verified independently.">Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno.</li>
            <li data-sr="Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja." data-en="If you feel street pressure, enter a shop or bank and ask staff for help.">Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja.</li>
          </ul>
        </div>
      </div>
    </section>
`
};
