window.SCAM_CONTENT = window.SCAM_CONTENT || {};

window.SCAM_CONTENT["gem-swap-scam"] = {
  raw_html: `
    <section class="card">
      <h2 data-sr="Uvod: zamena kamena u nakitu" data-en="Introduction: gem swap scam">Uvod: zamena kamena u nakitu</h2>
      <p data-sr="Srodno uličnoj verziji čišćenja, ali i lažnim gemolozima." data-en="Related to street cleaning and fake gemologists.">Srodno uličnoj verziji čišćenja, ali i lažnim gemolozima.</p>
      <div class="callout" data-sr="<strong>Model:</strong> priča o hitnosti → rad van radnje → manipulacija → vraćanje pogrešnog." data-en="<strong>Model:</strong> urgency story → work off-premises → handling → wrong return."><strong>Model:</strong> priča o hitnosti → rad van radnje → manipulacija → vraćanje pogrešnog.</div>
    </section>
    <section class="card">
      <h2 data-sr="Hronološki tok (faze + grananja)" data-en="Timeline (phases + branching)">Hronološki tok (faze + grananja)</h2>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 1 — Inicijalni kontakt: zamena kamena u nakitu" data-en="Phase 1 — Initial contact: gem swap scam">Faza 1 — Inicijalni kontakt: zamena kamena u nakitu</h3>
        <p data-sr="Početak scene prati opis: Srodno uličnoj verziji čišćenja, ali i lažnim gemolozima." data-en="The opening matches the pattern: Related to street cleaning and fake gemologists.">Početak scene prati opis: Srodno uličnoj verziji čišćenja, ali i lažnim gemolozima.</p>
        <ul class="bullets"><li data-sr="Kontakt deluje obično, ali žurba je već prisutna." data-en="The contact seems ordinary but hurry is already present.">Kontakt deluje obično, ali žurba je već prisutna.</li><li data-sr="Drugi ljudi mogu stajati blizu torbe, vozila ili novčanika." data-en="Others may stand near bag, vehicle, or wallet.">Drugi ljudi mogu stajati blizu torbe, vozila ili novčanika.</li><li data-sr="Ponuda se predstavlja kao jednokratna prilika ili hitnost." data-en="The offer is framed as one-time or urgent.">Ponuda se predstavlja kao jednokratna prilika ili hitnost.</li><li data-sr="Meta još uvek može da odbije bez trenutnog gubitka novca." data-en="The target can still refuse without immediate money loss.">Meta još uvek može da odbije bez trenutnog gubitka novca.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta usmeri pažnju na priču umesto na predmete koje nosi." data-en="<strong>Phase threshold:</strong> The target focuses on the story instead of what they carry."><strong>Prag faze:</strong> Meta usmeri pažnju na priču umesto na predmete koje nosi.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="distraction-theft-scam.html" data-sr="Prevara pažnjom (distraction theft)" data-en="Distraction theft scam">Prevara pažnjom (distraction theft)</a></li></ul></div>
      </article>      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 2 — Povećanje poverenja ili pritiska" data-en="Phase 2 — Building trust or pressure">Faza 2 — Povećanje poverenja ili pritiska</h3>
        <p data-sr="Prevarant dodaje detalje, lažnu legitimaciju, lažne svedoke ili tehnički žargon da smanji otpor." data-en="The fraudster adds detail, fake authority, fake witnesses, or jargon to lower resistance.">Prevarant dodaje detalje, lažnu legitimaciju, lažne svedoke ili tehnički žargon da smanji otpor.</p>
        <ul class="bullets"><li data-sr="Prikazuju se lažni dokazi, kartice, uniforme ili fotografije." data-en="Fake cards, uniforms, or photos may be shown.">Prikazuju se lažni dokazi, kartice, uniforme ili fotografije.</li><li data-sr="Ponavlja se da je sigurno jer je javno mesto." data-en="They repeat that it is safe because it is a public place.">Ponavlja se da je sigurno jer je javno mesto.</li><li data-sr="Meta se oseća glupo ako pita za pauzu." data-en="The target feels foolish asking for a pause.">Meta se oseća glupo ako pita za pauzu.</li><li data-sr="Fizički kontakt ili ulazak u lični prostor postaje češći." data-en="Physical contact or crowding becomes more common.">Fizički kontakt ili ulazak u lični prostor postaje češći.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Prihvata se nastavak razgovora umesto odlaska ka zvaničnoj proveri." data-en="<strong>Phase threshold:</strong> The target continues talk instead of moving to official verification."><strong>Prag faze:</strong> Prihvata se nastavak razgovora umesto odlaska ka zvaničnoj proveri.</div>

      </article>      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 3 — Prag novca, predmeta ili potpisa" data-en="Phase 3 — Threshold of money, item, or signature">Faza 3 — Prag novca, predmeta ili potpisa</h3>
        <p data-sr="Srodno uličnoj verziji čišćenja, ali i lažnim gemolozima." data-en="Related to street cleaning and fake gemologists.">Srodno uličnoj verziji čišćenja, ali i lažnim gemolozima.</p>
        <ul class="bullets"><li data-sr="Traži se gotovina, kartica, telefon, ključevi ili potpis." data-en="Cash, card, phone, keys, or a signature is requested.">Traži se gotovina, kartica, telefon, ključevi ili potpis.</li><li data-sr="Pritisak da se odluči odmah, bez poziva porodici." data-en="Pressure to decide now without calling family.">Pritisak da se odluči odmah, bez poziva porodici.</li><li data-sr="Član ekipe odvlači pogled ili blokira prolaz." data-en="A team member blocks view or the path.">Član ekipe odvlači pogled ili blokira prolaz.</li><li data-sr="Ovo je trenutak najvećeg rizika po vrednosti koje nosiš." data-en="This is the highest-risk moment for what you carry.">Ovo je trenutak najvećeg rizika po vrednosti koje nosiš.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta izdvaja novac, predaje vrednu stvar ili potpisuje pod pritiskom." data-en="<strong>Phase threshold:</strong> The target hands cash, a valuable item, or signs under pressure."><strong>Prag faze:</strong> Meta izdvaja novac, predaje vrednu stvar ili potpisuje pod pritiskom.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="advance-fee-fraud.html" data-sr="Uplata unapred — ako sledi serija novih taksi" data-en="Advance fee fraud — if new fees follow">Uplata unapred — ako sledi serija novih taksi</a></li><li><a href="impersonation-scam.html" data-sr="Lažno predstavljanje — ako uloga službe postaje naglašena" data-en="Impersonation — if a service role is stressed">Lažno predstavljanje — ako uloga službe postaje naglašena</a></li></ul></div>
      </article>      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 4 — Zatvaranje transakcije i nestanak dokaza" data-en="Phase 4 — Closing the transaction and losing proof">Faza 4 — Zatvaranje transakcije i nestanak dokaza</h3>
        <p data-sr="Nakon praga prevarant sklanja predmete, broji brzo ili menja scenario da nema jasnog traga." data-en="After the threshold the fraudster removes items, counts fast, or shifts the story so evidence is weak.">Nakon praga prevarant sklanja predmete, broji brzo ili menja scenario da nema jasnog traga.</p>
        <ul class="bullets"><li data-sr="Račun ili potvrda nedostaje ili je nečitljiv." data-en="A receipt is missing or unreadable.">Račun ili potvrda nedostaje ili je nečitljiv.</li><li data-sr="Broj telefona koji su dali prestaje da radi." data-en="A phone number they gave stops working.">Broj telefona koji su dali prestaje da radi.</li><li data-sr="Ljudi se razilaze u različitim pravcima." data-en="People split in different directions.">Ljudi se razilaze u različitim pravcima.</li><li data-sr="Žrtva tek kasnije proverava novčanik, robu ili račun." data-en="The victim checks wallet, goods, or bill only later.">Žrtva tek kasnije proverava novčanik, robu ili račun.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Prestaje jasna mogućnost da se na licu mesta proveri istina." data-en="<strong>Phase threshold:</strong> On-the-spot verification of truth is no longer realistic."><strong>Prag faze:</strong> Prestaje jasna mogućnost da se na licu mesta proveri istina.</div>

      </article>      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 5 — Posledice i zloupotreba" data-en="Phase 5 — Consequences and abuse">Faza 5 — Posledice i zloupotreba</h3>
        <p data-sr="Gubitak je novčan, predmetni ili podatak; kartice mogu biti zloupotrebljene ako su uzete." data-en="Loss is money, goods, or data; cards may be misused if taken.">Gubitak je novčan, predmetni ili podatak; kartice mogu biti zloupotrebljene ako su uzete.</p>
        <ul class="bullets"><li data-sr="Neovlašćene transakcije mogu uslediti ako je uzeta kartica." data-en="Unauthorized transactions may follow if a card was taken.">Neovlašćene transakcije mogu uslediti ako je uzeta kartica.</li><li data-sr="Lični dokumenti otvaraju put ka krađi identiteta." data-en="ID documents can open paths to identity theft.">Lični dokumenti otvaraju put ka krađi identiteta.</li><li data-sr="Stid otežava prijavu, posebno kod uličnih scena." data-en="Shame delays reporting, especially in street scenes.">Stid otežava prijavu, posebno kod uličnih scena.</li><li data-sr="Isti obrasci se ponavljaju na drugim lokacijama." data-en="The same patterns repeat at other locations.">Isti obrasci se ponavljaju na drugim lokacijama.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva potvrđuje štetu ili sumnju na zloupotrebu." data-en="<strong>Phase threshold:</strong> The victim confirms loss or suspected misuse."><strong>Prag faze:</strong> Žrtva potvrđuje štetu ili sumnju na zloupotrebu.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="identity-theft.html" data-sr="Krađa identiteta — ako su uzeti dokumenti" data-en="Identity theft — if documents were taken">Krađa identiteta — ako su uzeti dokumenti</a></li><li><a href="card-skimming.html" data-sr="Kartice — ako je praćena krađa kartice" data-en="Cards — if card theft followed">Kartice — ako je praćena krađa kartice</a></li></ul></div>
      </article>      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 6 — Prijava, dokumentacija i prevencija" data-en="Phase 6 — Reporting, documentation, prevention">Faza 6 — Prijava, dokumentacija i prevencija</h3>
        <p data-sr="Policija, objekat ili banka mogu zabeležiti slučaj; fotografije, vreme i opis pomažu; ubuduće koristi zvanične kanale." data-en="Police, venue, or bank can record the case; photos, time, and description help; use official channels next time.">Policija, objekat ili banka mogu zabeležiti slučaj; fotografije, vreme i opis pomažu; ubuduće koristi zvanične kanale.</p>
        <ul class="bullets"><li data-sr="Prijavi incident sa lokacijom i vremenom." data-en="Report with location and time.">Prijavi incident sa lokacijom i vremenom.</li><li data-sr="Blokiraj kartice ako su uzete ili vidljive." data-en="Block cards if they were taken or exposed.">Blokiraj kartice ako su uzete ili vidljive.</li><li data-sr="Obavesti porodicu i kolege o obrascu." data-en="Warn family and colleagues about the pattern.">Obavesti porodicu i kolege o obrascu.</li><li data-sr="Za slične ulične šeme koristi stranicu o odvlačenju pažnje kao referencu." data-en="Use the distraction theft page as a reference for similar street schemes.">Za slične ulične šeme koristi stranicu o odvlačenju pažnje kao referencu.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva aktivira zaštitu i dokumentuje slučaj." data-en="<strong>Phase threshold:</strong> The victim activates protection and documents the case."><strong>Prag faze:</strong> Žrtva aktivira zaštitu i dokumentuje slučaj.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="distraction-theft-scam.html" data-sr="Prevara pažnjom — širi okvir ulične krađe" data-en="Distraction theft — broader street theft frame">Prevara pažnjom — širi okvir ulične krađe</a></li><li><a href="marketplace-scam.html" data-sr="Marketplace prevare — ako je digitalni uvod u sastanak" data-en="Marketplace scams — if a digital lead led to a meetup">Marketplace prevare — ako je digitalni uvod u sastanak</a></li></ul></div>
      </article>
    </section>

    <section class="card">
      <h2 data-sr="Crvene zastavice" data-en="Red flags">Crvene zastavice</h2>
      <ul class="bullets"><li data-sr="Stranac forsira brzinu i izbegava zvaničnu proveru." data-en="A stranger forces speed and avoids official checks.">Stranac forsira brzinu i izbegava zvaničnu proveru.</li><li data-sr="Traže se gotovina, predmet ili potpis bez pisanog traga." data-en="Cash, an item, or a signature is wanted without a paper trail.">Traže se gotovina, predmet ili potpis bez pisanog traga.</li><li data-sr="Više osoba koordinisano prilazi ili okružuje." data-en="Several people approach or surround in a coordinated way.">Više osoba koordinisano prilazi ili okružuje.</li><li data-sr="Ponuda zvuči predobro da bi bila rutinska." data-en="The offer sounds too good to be routine.">Ponuda zvuči predobro da bi bila rutinska.</li><li data-sr="Izbegavaju se pozivi policiji, bezbednosti ili zvaničnom broju." data-en="Calls to police, security, or official numbers are discouraged.">Izbegavaju se pozivi policiji, bezbednosti ili zvaničnom broju.</li><li data-sr="Fizički kontakt sa torbom, novčanikom ili vozilom bez tvog odobrenja." data-en="Physical contact with bag, wallet, or vehicle without clear consent.">Fizički kontakt sa torbom, novčanikom ili vozilom bez tvog odobrenja.</li><li data-sr="Scenario zavisi od stida, žurbe ili straha od scene." data-en="The script depends on shame, hurry, or fear of a scene.">Scenario zavisi od stida, žurbe ili straha od scene.</li><li data-sr="Nema jasnog računa, ugovora ili identifikacije primaoca." data-en="No clear receipt, contract, or recipient identification.">Nema jasnog računa, ugovora ili identifikacije primaoca.</li><li data-sr="Nakon događaja kontakt i brojevi ne rade." data-en="After the event contact and numbers do not work.">Nakon događaja kontakt i brojevi ne rade.</li><li data-sr="Osećaš da bi pauza uništila priliku, što je tipičan znak pritiska." data-en="You feel a pause would ruin the deal, a typical pressure sign.">Osećaš da bi pauza uništila priliku, što je tipičan znak pritiska.</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Provere: 8 brzih provera" data-en="Checks: 8 quick checks">Provere: 8 brzih provera</h2>
      <ul class="bullets"><li data-sr="Da li stranac forsira brzinu i usamljenje umesto zvaničnog mesta?" data-en="Does a stranger push speed and isolation instead of an official setting?">Da li stranac forsira brzinu i usamljenje umesto zvaničnog mesta?</li><li data-sr="Da li možeš da ostaneš u javnom prostoru sa svjedocima dok razgovaraš?" data-en="Can you stay in a public space with witnesses while you talk?">Da li možeš da ostaneš u javnom prostoru sa svjedocima dok razgovaraš?</li><li data-sr="Da li bi prava služba tražila uplatu gotovinom na parkingu bez računa?" data-en="Would a real service demand cash on a parking lot with no receipt?">Da li bi prava služba tražila uplatu gotovinom na parkingu bez računa?</li><li data-sr="Da li traže da držiš ili da vidiš sadržaj novčanika na ulici?" data-en="Do they ask to hold or see the contents of your wallet in the street?">Da li traže da držiš ili da vidiš sadržaj novčanika na ulici?</li><li data-sr="Da li postoji drugi član ekipe koji se slučajno približava torbi ili vozilu?" data-en="Is there a second person who accidentally nears your bag or vehicle?">Da li postoji drugi član ekipe koji se slučajno približava torbi ili vozilu?</li><li data-sr="Da li scenario zavisi od tvoje žurbe, stida ili straha od scene?" data-en="Does the script depend on your hurry, shame, or fear of a scene?">Da li scenario zavisi od tvoje žurbe, stida ili straha od scene?</li><li data-sr="Da li možeš da pozoveš broj sa zvaničnog sajta institucije, a ne broj koji oni daju?" data-en="Can you call a number from an official website, not one they give you?">Da li možeš da pozoveš broj sa zvaničnog sajta institucije, a ne broj koji oni daju?</li><li data-sr="Da li bi prijatelj rekao da je ovo bezbedan potez u istim uslovima?" data-en="Would a friend say this is a safe move under the same conditions?">Da li bi prijatelj rekao da je ovo bezbedan potez u istim uslovima?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Checklista: 12 pitanja" data-en="Checklist: 12 questions">Checklista: 12 pitanja</h2>
      <ul class="bullets"><li data-sr="Da li sam ostao u prostoru sa kamerama ili osobljem?" data-en="Did I stay in an area with CCTV or staff?">Da li sam ostao u prostoru sa kamerama ili osobljem?</li><li data-sr="Da li sam tražio legitimaciju ili račun pre bilo kakve uplate?" data-en="Did I ask for ID or a receipt before any payment?">Da li sam tražio legitimaciju ili račun pre bilo kakve uplate?</li><li data-sr="Da li sam držao torbu i vrednosti u vidnom polju tokom celog kontakta?" data-en="Did I keep bag and valuables in sight for the whole contact?">Da li sam držao torbu i vrednosti u vidnom polju tokom celog kontakta?</li><li data-sr="Da li sam izbegao ulazak u tuđe vozilo ili slepu uličicu?" data-en="Did I avoid entering someone else's car or a blind alley?">Da li sam izbegao ulazak u tuđe vozilo ili slepu uličicu?</li><li data-sr="Da li sam odbio da pokažem ceo novčanik ili da ga predam na proveru?" data-en="Did I refuse to show my whole wallet or hand it over for a check?">Da li sam odbio da pokažem ceo novčanik ili da ga predam na proveru?</li><li data-sr="Da li sam proverio štetu na vozilu pre nego što sam prihvatio pomoć?" data-en="Did I verify vehicle damage before accepting help?">Da li sam proverio štetu na vozilu pre nego što sam prihvatio pomoć?</li><li data-sr="Da li sam fotografisao tablice, lice ili uniformu ako je bezbedno?" data-en="Did I photograph plates, face, or uniform if it was safe?">Da li sam fotografisao tablice, lice ili uniformu ako je bezbedno?</li><li data-sr="Da li sam odmah posle incidenta proverio novčanik, telefon i ključeve?" data-en="Did I check wallet, phone, and keys right after the incident?">Da li sam odmah posle incidenta proverio novčanik, telefon i ključeve?</li><li data-sr="Da li sam razumeo da žurba i javna scena često služe odvlačenju pažnje?" data-en="Did I understand that rush and public drama often serve distraction?">Da li sam razumeo da žurba i javna scena često služe odvlačenju pažnje?</li><li data-sr="Da li sam mogao da odložim odluku za 30 minuta bez gubitka prilike?" data-en="Could I delay the decision 30 minutes without losing the deal?">Da li sam mogao da odložim odluku za 30 minuta bez gubitka prilike?</li><li data-sr="Da li bih isti scenario prihvatio da mi ga neko drugi ispriča?" data-en="Would I accept the same scenario if someone else described it to me?">Da li bih isti scenario prihvatio da mi ga neko drugi ispriča?</li><li data-sr="Da li postoji zvaničan kanal (policija, parking servis, klub) koji mogu da pozovem?" data-en="Is there an official channel (police, parking operator, club) I can call?">Da li postoji zvaničan kanal (policija, parking servis, klub) koji mogu da pozovem?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Ako sumnja krene: redosled poteza" data-en="If suspicion starts: order of steps">Ako sumnja krene: redosled poteza</h2>
      <ol class="steps"><li data-sr="Prekini interakciju i ostani na mestu sa svjedocima ili uđi u objekat sa osobljem." data-en="End the interaction and stay where there are witnesses or enter a staffed building.">Prekini interakciju i ostani na mestu sa svjedocima ili uđi u objekat sa osobljem.</li><li data-sr="Ne daj novčanik, telefon ni ključeve u tuđe ruke i ne prati nepoznate u vozilo." data-en="Do not hand wallet, phone, or keys to others and do not follow strangers into a car.">Ne daj novčanik, telefon ni ključeve u tuđe ruke i ne prati nepoznate u vozilo.</li><li data-sr="Proveri torbu, džep i vozilo pre nego što potpišeš bilo šta ili platiš." data-en="Check bag, pockets, and vehicle before you sign anything or pay.">Proveri torbu, džep i vozilo pre nego što potpišeš bilo šta ili platiš.</li><li data-sr="Pozovi policiju ili bezbednost ako osećaš pritisak, izolaciju ili fizički kontakt." data-en="Call police or security if you feel pressure, isolation, or physical contact.">Pozovi policiju ili bezbednost ako osećaš pritisak, izolaciju ili fizički kontakt.</li><li data-sr="Prijavi incident sa vremenom, mestom i opisom lica ili vozila." data-en="Report the incident with time, place, and descriptions of people or vehicles.">Prijavi incident sa vremenom, mestom i opisom lica ili vozila.</li></ol>
    </section>
    <section class="card">
      <h2 data-sr="Ako pokušavaš da pomogneš nekome" data-en="If you are trying to help someone">Ako pokušavaš da pomogneš nekome</h2>
      <div class="grid-2">
        <div class="phase">
          <div class="label" data-sr="Pitanja koja pomažu" data-en="Helpful questions">Pitanja koja pomažu</div>
          <ul class="bullets"><li data-sr="Da li je osoba već predala novac, ključeve ili telefon strancu na ulici?" data-en="Have they already handed cash, keys, or a phone to a stranger in the street?">Da li je osoba već predala novac, ključeve ili telefon strancu na ulici?</li><li data-sr="Da li postoji pritisak da se odmah plati ili potpiše bez pauze?" data-en="Is there pressure to pay or sign immediately without a pause?">Da li postoji pritisak da se odmah plati ili potpiše bez pauze?</li><li data-sr="Da li su tražili da se ode na usamljeno mesto ili u nepoznato vozilo?" data-en="Were they asked to go to an isolated spot or an unknown vehicle?">Da li su tražili da se ode na usamljeno mesto ili u nepoznato vozilo?</li><li data-sr="Da li sumnja dolazi tek posle što su se odmakli od mesta događaja?" data-en="Does doubt only appear after they moved away from the scene?">Da li sumnja dolazi tek posle što su se odmakli od mesta događaja?</li></ul>
        </div>
        <div class="phase">
          <div class="label" data-sr="Rečenice koje rade" data-en="Phrases that work">Rečenice koje rade</div>
          <ul class="bullets"><li data-sr="Hajde u prodavnicu, banku ili stanicu sa osobljem i tu nastavimo razgovor." data-en="Let us continue inside a shop, bank, or staffed station.">Hajde u prodavnicu, banku ili stanicu sa osobljem i tu nastavimo razgovor.</li><li data-sr="Ne plaćamo i ne predajemo predmete dok identitet i ovlašćenje nisu provereni zvanično." data-en="We do not pay or hand over items until identity and authority are verified officially.">Ne plaćamo i ne predajemo predmete dok identitet i ovlašćenje nisu provereni zvanično.</li><li data-sr="Pozivam policiju ili bezbednost objekta da provere situaciju zajedno sa nama." data-en="I am calling police or venue security to check the situation with us.">Pozivam policiju ili bezbednost objekta da provere situaciju zajedno sa nama.</li><li data-sr="Pauza od pola sata neće pokvariti legitiman posao, ali će prekinuti uličnu šemu." data-en="A thirty-minute pause will not ruin a legitimate deal but will break a street script.">Pauza od pola sata neće pokvariti legitiman posao, ali će prekinuti uličnu šemu.</li></ul>
        </div>
      </div>
    </section>
`
};
