window.SCAM_CONTENT = window.SCAM_CONTENT || {};

window.SCAM_CONTENT["interview-software-install-scam"] = {
  raw_html: `
    <section class="card">
      <h2 data-sr="Uvod: intervju i malver" data-en="Introduction: interview and malware">Uvod: intervju i malver</h2>
      <p data-sr="Lažni regruter koristi proces koji liči na zapošljavanje da bi naterao žrtvu da instalira zlonamerni softver ili TeamViewer/AnyDesk varijantu." data-en="A fake recruiter mimics hiring to make the victim install malware or a TeamViewer-style remote tool.">Lažni regruter koristi proces koji liči na zapošljavanje da bi naterao žrtvu da instalira zlonamerni softver ili TeamViewer/AnyDesk varijantu.</p>
      <div class="callout" data-sr="<strong>Model:</strong> oglas → intervju → fajl → malver → krađa naloga" data-en="<strong>Model:</strong> ad → interview → file → malware → account theft"><strong>Model:</strong> oglas → intervju → fajl → malver → krađa naloga</div>
    </section>
    <section class="card">
      <h2 data-sr="Hronološki tok (faze + grananja)" data-en="Timeline (phases + branching)">Hronološki tok (faze + grananja)</h2>
      
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 1 — Primamljiva ponuda posla" data-en="Phase 1 — Attractive job offer">Faza 1 — Primamljiva ponuda posla</h3>
        <p data-sr="Oglas ili poruka nudi dobru platu ili udaljeni rad uz brz intervju." data-en="An ad or message offers good pay or remote work with a fast interview.">Oglas ili poruka nudi dobru platu ili udaljeni rad uz brz intervju.</p>
        <ul class="bullets"><li data-sr="Minimalna provera iskustva ili reference." data-en="Minimal experience or reference checks.">Minimalna provera iskustva ili reference.</li><li data-sr="Kontakt preko ličnog imejla ili čet aplikacije." data-en="Contact via personal email or chat app.">Kontakt preko ličnog imejla ili čet aplikacije.</li><li data-sr="Pozicija je generička (asistent, analitičar)." data-en="The role is generic (assistant, analyst).">Pozicija je generička (asistent, analitičar).</li><li data-sr="Hitnost oko sledećeg koraka u procesu." data-en="Urgency about the next step in the process.">Hitnost oko sledećeg koraka u procesu.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta odgovara na oglas i zakazuje intervju." data-en="<strong>Phase threshold:</strong> The target replies to the ad and schedules an interview."><strong>Prag faze:</strong> Meta odgovara na oglas i zakazuje intervju.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="job-scam.html" data-sr="Prevara sa poslom" data-en="Job scam">Prevara sa poslom</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 2 — Lažni intervju u četu" data-en="Phase 2 — Fake chat interview">Faza 2 — Lažni intervju u četu</h3>
        <p data-sr="Intervju je kratak, pitanja su površna i brzo sledi prijem." data-en="The interview is short, questions are shallow, and acceptance follows quickly.">Intervju je kratak, pitanja su površna i brzo sledi prijem.</p>
        <ul class="bullets"><li data-sr="Nema video poziva lica prema licu." data-en="No face-to-face video call.">Nema video poziva lica prema licu.</li><li data-sr="Isti tekstovi liče na kopiju sa drugih žrtava." data-en="The same texts look copied from other victims.">Isti tekstovi liče na kopiju sa drugih žrtava.</li><li data-sr="Traže lične podatke rano u procesu." data-en="They ask for personal data early in the process.">Traže lične podatke rano u procesu.</li><li data-sr="Ton je previše entuzijastičan za brzinu odluke." data-en="The tone is overly enthusiastic for the speed of the decision.">Ton je previše entuzijastičan za brzinu odluke.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta veruje da ima legitiman proces selekcije." data-en="<strong>Phase threshold:</strong> The target believes there is a legitimate selection process."><strong>Prag faze:</strong> Meta veruje da ima legitiman proces selekcije.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="fake-hr-scam.html" data-sr="Lažni HR" data-en="Fake HR scam">Lažni HR</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 3 — Zahtev za instalaciju softvera" data-en="Phase 3 — Software install demand">Faza 3 — Zahtev za instalaciju softvera</h3>
        <p data-sr="Šalju link ili prilog za alat za saradnju, VPN, praćenje vremena ili test okruženje." data-en="They send a link or attachment for a collaboration tool, VPN, time tracker, or test environment.">Šalju link ili prilog za alat za saradnju, VPN, praćenje vremena ili test okruženje.</p>
        <ul class="bullets"><li data-sr="Fajl nije na zvaničnom domenu poslodavca." data-en="The file is not on the employer's official domain.">Fajl nije na zvaničnom domenu poslodavca.</li><li data-sr="Traže isključivanje zaštite ili dozvolu za sve diskove." data-en="They ask to disable protection or allow all disks.">Traže isključivanje zaštite ili dozvolu za sve diskove.</li><li data-sr="Instalacija traži široke dozvole ili daljinski pristup." data-en="Installation asks for broad permissions or remote access.">Instalacija traži široke dozvole ili daljinski pristup.</li><li data-sr="Verzija softvera ne odgovara imenu kompanije." data-en="The software version does not match the company name.">Verzija softvera ne odgovara imenu kompanije.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta preuzima i pokreće nepoznat izvršni fajl ili daje daljinski pristup." data-en="<strong>Phase threshold:</strong> The target downloads and runs an unknown executable or grants remote access."><strong>Prag faze:</strong> Meta preuzima i pokreće nepoznat izvršni fajl ili daje daljinski pristup.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="tech-support-remote-access-scam.html" data-sr="Daljinski pristup kao prevara" data-en="Remote access scam">Daljinski pristup kao prevara</a></li><li><a href="malicious-app-scam.html" data-sr="Zlonamerna aplikacija" data-en="Malicious app scam">Zlonamerna aplikacija</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 4 — Kompromitacija uređaja ili naloga" data-en="Phase 4 — Device or account compromise">Faza 4 — Kompromitacija uređaja ili naloga</h3>
        <p data-sr="Malver ili RAT snima tastaturu, krade sesije ili prazni naloge." data-en="Malware or a RAT logs keystrokes, steals sessions, or empties accounts.">Malver ili RAT snima tastaturu, krade sesije ili prazni naloge.</p>
        <ul class="bullets"><li data-sr="Neočekivane transakcije ili promene lozinki." data-en="Unexpected transactions or password changes.">Neočekivane transakcije ili promene lozinki.</li><li data-sr="Zahtevi za 2FA kod tokom testa." data-en="Requests for 2FA codes during a test. ">Zahtevi za 2FA kod tokom testa.</li><li data-sr="Lažni login portali koji liče na Office ili Google." data-en="Fake login portals resembling Office or Google.">Lažni login portali koji liče na Office ili Google.</li><li data-sr="Fajlovi ili mejlovi se šalju sa tvog naloga." data-en="Files or emails are sent from your account.">Fajlovi ili mejlovi se šalju sa tvog naloga.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva vidi anomalije na nalogu ili bankovnom izvodu." data-en="<strong>Phase threshold:</strong> The victim sees anomalies on accounts or bank statements."><strong>Prag faze:</strong> Žrtva vidi anomalije na nalogu ili bankovnom izvodu.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="phishing.html" data-sr="Fišing" data-en="Phishing">Fišing</a></li><li><a href="account-takeover.html" data-sr="Preuzimanje naloga" data-en="Account takeover">Preuzimanje naloga</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 5 — Eskalacija ili gubitak kontakta" data-en="Phase 5 — Escalation or loss of contact">Faza 5 — Eskalacija ili gubitak kontakta</h3>
        <p data-sr="Traže još jedan alat ili instalaciju; zatim kontakt prestaje kada je cilj postignut." data-en="They ask for another tool or install; then contact stops once the goal is reached.">Traže još jedan alat ili instalaciju; zatim kontakt prestaje kada je cilj postignut.</p>
        <ul class="bullets"><li data-sr="Drugi paket softvera sa istim obrascom." data-en="A second software package with the same pattern.">Drugi paket softvera sa istim obrascom.</li><li data-sr="Lažni IT koji traži da potvrdiš kod sa telefona." data-en="Fake IT asks you to confirm a phone code.">Lažni IT koji traži da potvrdiš kod sa telefona.</li><li data-sr="Blokiraju te kada pitaš za ugovor o radu." data-en="They block you when you ask for an employment contract.">Blokiraju te kada pitaš za ugovor o radu.</li><li data-sr="Posao nikad ne počinje uprkos instalaciji." data-en="The job never starts despite installation.">Posao nikad ne počinje uprkos instalaciji.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva shvata da posao ne postoji ili da je uređaj kompromitovan." data-en="<strong>Phase threshold:</strong> The victim realises the job does not exist or the device is compromised."><strong>Prag faze:</strong> Žrtva shvata da posao ne postoji ili da je uređaj kompromitovan.</div>
        
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 6 — Oporavak i prijava" data-en="Phase 6 — Recovery and reporting">Faza 6 — Oporavak i prijava</h3>
        <p data-sr="Izoluj uređaj, promeni lozinke sa drugog uređaja, obavesti banku i prijavi malver." data-en="Isolate the device, change passwords from another machine, notify the bank, and report malware.">Izoluj uređaj, promeni lozinke sa drugog uređaja, obavesti banku i prijavi malver.</p>
        <ul class="bullets"><li data-sr="Prekinuti mrežnu vezu i pokrenuti sken iz bezbednog režima ako je potrebno." data-en="Disconnect from the network and scan from safe mode if needed.">Prekinuti mrežnu vezu i pokrenuti sken iz bezbednog režima ako je potrebno.</li><li data-sr="Obavestiti poslodavca čije je ime zloupotrebljeno." data-en="Notify the employer whose name was misused.">Obavestiti poslodavca čije je ime zloupotrebljeno.</li><li data-sr="Sačuvati heševe fajlova i logove za istragu." data-en="Save file hashes and logs for investigation.">Sačuvati heševe fajlova i logove za istragu.</li><li data-sr="Razmotriti reinstalaciju sistema ako je integritet sumnjiv." data-en="Consider OS reinstall if integrity is doubtful.">Razmotriti reinstalaciju sistema ako je integritet sumnjiv.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva preduzima korake sanacije i dokumentuje incident." data-en="<strong>Phase threshold:</strong> The victim takes remediation steps and documents the incident."><strong>Prag faze:</strong> Žrtva preduzima korake sanacije i dokumentuje incident.</div>
        
      </article>
    </section>
    <section class="card">
      <h2 data-sr="Crvene zastavice" data-en="Red flags">Crvene zastavice</h2>
      <ul class="bullets"><li data-sr="Intervju je samo čet i odmah sledi link za instalaciju." data-en="Interview is chat-only and a software link follows immediately.">Intervju je samo čet i odmah sledi link za instalaciju.</li><li data-sr="Traže administratorske privilegije ili isključivanje antivirusa." data-en="They ask for administrator rights or disabling antivirus.">Traže administratorske privilegije ili isključivanje antivirusa.</li><li data-sr="Fajl nije potpisan poznatim izdavačem ili je izvršni fajl sa nepoznatog hostinga." data-en="File is not signed by a known publisher or is an executable from unknown hosting.">Fajl nije potpisan poznatim izdavačem ili je izvršni fajl sa nepoznatog hostinga.</li><li data-sr="Posao zvuči previše dobro uz minimalnu proveru kvalifikacija." data-en="Job sounds too good with minimal qualification checks.">Posao zvuči previše dobro uz minimalnu proveru kvalifikacija.</li><li data-sr="Kontakt imejl ne koristi domen poslodavca." data-en="Contact email does not use the employer domain.">Kontakt imejl ne koristi domen poslodavca.</li><li data-sr="Traže kupovinu opreme pre potpisanog ugovora o radu." data-en="They want equipment bought before a signed employment contract.">Traže kupovinu opreme pre potpisanog ugovora o radu.</li><li data-sr="Naknada se traži preko preplaćenog čeka, poklon kartice ili P2P." data-en="Reimbursement is via overpayment, gift card, or P2P only.">Naknada se traži preko preplaćenog čeka, poklon kartice ili P2P.</li><li data-sr="Odbijaju video poziv sa kamerom lica." data-en="They refuse a video call showing their face.">Odbijaju video poziv sa kamerom lica.</li><li data-sr="Hitno traže odluku u roku od nekoliko sati." data-en="They demand a decision within a few hours.">Hitno traže odluku u roku od nekoliko sati.</li><li data-sr="Posle uplate kontakt prestaje ili traže još jednu uplatu." data-en="After payment contact stops or another fee appears.">Posle uplate kontakt prestaje ili traže još jednu uplatu.</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Provere: 8 brzih provera" data-en="Checks: 8 quick checks">Provere: 8 brzih provera</h2>
      <ul class="bullets"><li data-sr="Da li poslodavac potvrđuje poziciju na zvaničnom kanalu?" data-en="Does the employer confirm the role on an official channel?">Da li poslodavac potvrđuje poziciju na zvaničnom kanalu?</li><li data-sr="Da li URL preuzimanja pripada domenu kompanije?" data-en="Does the download URL belong to the company domain?">Da li URL preuzimanja pripada domenu kompanije?</li><li data-sr="Da li potpis softvera možeš proveriti u operativnom sistemu?" data-en="Can you verify the software signature in the operating system?">Da li potpis softvera možeš proveriti u operativnom sistemu?</li><li data-sr="Da li bi pravi HR tražio instalaciju pre potpisanog ugovora?" data-en="Would real HR demand installation before a signed contract?">Da li bi pravi HR tražio instalaciju pre potpisanog ugovora?</li><li data-sr="Da li možeš zatražiti video intervju sa zvaničnim HR?" data-en="Can you request a video interview with official HR?">Da li možeš zatražiti video intervju sa zvaničnim HR?</li><li data-sr="Da li naknada za opremu ide samo preko sumnjivog naloga ili kartice?" data-en="Does equipment reimbursement route only through a suspicious account or card?">Da li naknada za opremu ide samo preko sumnjivog naloga ili kartice?</li><li data-sr="Da li postoji pisani sporazum o naknadi troškova pre kupovine?" data-en="Is there a written expense agreement before purchase?">Da li postoji pisani sporazum o naknadi troškova pre kupovine?</li><li data-sr="Da li oglas platforme odgovara stvarnoj objavi poslodavca?" data-en="Does the platform listing match the employer's real posting?">Da li oglas platforme odgovara stvarnoj objavi poslodavca?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Checklista: 12 pitanja" data-en="Checklist: 12 questions">Checklista: 12 pitanja</h2>
      <ul class="bullets"><li data-sr="Da li sam nezavisno proverio identitet pre bilo kakve uplate?" data-en="Have I independently verified identity before any payment?">Da li sam nezavisno proverio identitet pre bilo kakve uplate?</li><li data-sr="Da li sam razgovarao sa nekim od poverenja?" data-en="Have I spoken to someone I trust?">Da li sam razgovarao sa nekim od poverenja?</li><li data-sr="Da li postoji pritisak za odluku istog dana?" data-en="Is there same-day decision pressure?">Da li postoji pritisak za odluku istog dana?</li><li data-sr="Da li je plaćanje traženo na način koji je teško otkazati?" data-en="Is payment requested in a hard-to-reverse way?">Da li je plaćanje traženo na način koji je teško otkazati?</li><li data-sr="Da li dokumenti imaju očigledne greške ili generičke šablone?" data-en="Do documents have obvious errors or generic templates?">Da li dokumenti imaju očigledne greške ili generičke šablone?</li><li data-sr="Da li mogu da sačekam 24 sata pre uplate?" data-en="Can I wait 24 hours before paying?">Da li mogu da sačekam 24 sata pre uplate?</li><li data-sr="Da li znam tačnu adresu i pravni subjekt primaoca?" data-en="Do I know the exact address and legal entity of the recipient?">Da li znam tačnu adresu i pravni subjekt primaoca?</li><li data-sr="Da li je cena daleko ispod tržišne bez razloga?" data-en="Is the price far below market with no explanation?">Da li je cena daleko ispod tržišne bez razloga?</li><li data-sr="Da li su svi učesnici stranci bez prethodnog konteksta?" data-en="Are all participants strangers with no prior context?">Da li su svi učesnici stranci bez prethodnog konteksta?</li><li data-sr="Da li osećam stid ili strah da pitam za pauzu?" data-en="Do I feel shame or fear to ask for a pause?">Da li osećam stid ili strah da pitam za pauzu?</li><li data-sr="Da li bih savetovao prijatelju da prihvati isti scenario?" data-en="Would I advise a friend to accept the same scenario?">Da li bih savetovao prijatelju da prihvati isti scenario?</li><li data-sr="Da li postoji alternativa preko zvaničnog portala ili poziva službi?" data-en="Is there an alternative via an official portal or service call?">Da li postoji alternativa preko zvaničnog portala ili poziva službi?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Ako sumnja krene: redosled poteza" data-en="If suspicion starts: order of steps">Ako sumnja krene: redosled poteza</h2>
      <ol class="steps">
        
        <li data-sr="Ne instaliraj softver i ne daj daljinski pristup tokom intervjua." data-en="Do not install software or grant remote access during an interview.">Ne instaliraj softver i ne daj daljinski pristup tokom intervjua.</li>
        <li data-sr="Potvrdi posao direktno kod poslodavca preko zvaničnog kontakta sa sajta ili HR linije." data-en="Confirm the job directly with the employer via official website or HR line contact.">Potvrdi posao direktno kod poslodavca preko zvaničnog kontakta sa sajta ili HR linije.</li>
        <li data-sr="Sačuvaj poruke, linkove i imejl adrese za prijavu." data-en="Save messages, links, and email addresses for reporting.">Sačuvaj poruke, linkove i imejl adrese za prijavu.</li>
        <li data-sr="Obrisi preuzeti fajl ako sumnjaš i pokreni antimalver sken." data-en="Delete any downloaded file if suspicious and run an antimalware scan.">Obrisi preuzeti fajl ako sumnjaš i pokreni antimalver sken.</li>
        <li data-sr="Prijavi lažni oglas platformi i policiji ili nacionalnoj liniji za cyber kriminal." data-en="Report the fake listing to the platform and to police or a national cybercrime line.">Prijavi lažni oglas platformi i policiji ili nacionalnoj liniji za cyber kriminal.</li>
      </ol>
    </section>
    <section class="card">
      <h2 data-sr="Ako pokušavaš da pomogneš nekome" data-en="If you are trying to help someone">Ako pokušavaš da pomogneš nekome</h2>
      <div class="grid-2">
        <div class="phase">
          <div class="label" data-sr="Pitanja koja pomažu" data-en="Helpful questions">Pitanja koja pomažu</div>
          <ul class="bullets">
            <li data-sr="Da li je osoba već platila ili pustila nekoga unutra?" data-en="Has the person already paid or let someone inside?">Da li je osoba već platila ili pustila nekoga unutra?</li>
            <li data-sr="Da li postoji pritisak da se odmah odluči bez konsultacije?" data-en="Is there pressure to decide immediately without consulting anyone?">Da li postoji pritisak da se odmah odluči bez konsultacije?</li>
            <li data-sr="Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?" data-en="Did they ask for cash, vouchers, or payment to a third-party account?">Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?</li>
            <li data-sr="Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?" data-en="Can identity be verified via an official number from the agency or company website?">Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?</li>
          </ul>
        </div>
        <div class="phase">
          <div class="label" data-sr="Rečenice koje rade" data-en="Phrases that work">Rečenice koje rade</div>
          <ul class="bullets">
            <li data-sr="Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno." data-en="Let us first close the door and call the official number together.">Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno.</li>
            <li data-sr="Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja." data-en="A real agency or firm allows a pause and written appointment confirmation.">Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja.</li>
            <li data-sr="Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno." data-en="We pay nothing until identity and authority are verified independently.">Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno.</li>
            <li data-sr="Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja." data-en="If you feel street pressure, enter a shop or bank and ask staff for help.">Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja.</li>
          </ul>
        </div>
      </div>
    </section>
`
};
