const L = (sr, en) => ({ sr, en });
const ST = [
  "Proveri poslodavca na zvaničnom sajtu i pozovi broj sa liste kontakata, ne iz poruke.",
  "Verify the employer on the official site and call the number from the contact list, not from the message."
];
const HS = "Kandidat žuri zbog prilike. Zajednička provera kroz zvanični careers sajt ili javni telefon kompanije smanjuje otpor.";
const HE = "The candidate rushes because of the opportunity. Checking together via the official careers site or company public phone lowers resistance.";

module.exports = [
  {
    slug: "mystery-shopper-scam",
    title_sr: "Prevara sa tajnim kupcem (mystery shopper)",
    title_en: "Mystery shopper scam",
    hero_sr: "Ponuda tajnog kupca → kupovina kartica ili depozit → nema povraćaja.",
    hero_en: "Secret shopper offer → card purchases or deposit → no reimbursement.",
    meta_sr: "Lažni mystery shopper: lažni ček, kupovina kartica, depozit. Provera poslodavca i kanala plaćanja.",
    meta_en: "Fake mystery shopper: fake check, gift cards, deposit. Verify employer and payment channel.",
    summary_sr: "Ponuda tajnog kupca traži kupovinu poklon-kartica ili depozit uz obećanje povraćaja. Eskalacija dodaje korake dok novac ne ode. Signal: uplata pre ugovora i pre provere firme.",
    summary_en: "A secret-shopper offer asks for gift cards or a deposit with reimbursement promised. Escalation adds steps until the money is gone. Signal: payment before a contract and employer check.",
    subtitle_sr: "Tajni kupac kao maska: kartice, čekovi ili depozit pre pravog posla.",
    subtitle_en: "Secret shopper as a cover: cards, checks, or a deposit before real work.",
    i1sr: "Prevarant nudi plaćeno „tajno kupovanje“ ili ocenjivanje usluga. Uputstva traže kupovinu poklon-kartica, slanje fotografija kodova ili uplatu radi „verifikacije naloga“.",
    i1en: "The fraudster offers paid secret shopping or service ratings. Instructions ask you to buy gift cards, send photos of codes, or pay to verify an account.",
    i2sr: "Pravi programi postoje, ali ne traže da kupuješ kartice za treća lica ili da šalješ novac nepoznatim primaocima pre ugovora.",
    i2en: "Real programs exist, but they do not ask you to buy cards for strangers or send money to unknown recipients before a contract.",
    model_sr: "oglasi → brzi zadatak → prag (kartice ili uplata) → obećani povraćaj ne stiže.",
    model_en: "ads → quick task → threshold (cards or payment) → promised reimbursement never arrives.",
    model_body: "oglasi → brzi zadatak → prag (kartice ili uplata) → obećani povraćaj ne stiže.",
    gsr: "Koristi se želja za lakim zaradom i kratkim zadacima. Lažni poslodavac kontroliše tok dok žrtva finansira kartice ili depozit.",
    gen: "It exploits the wish for easy money and short tasks. The fake employer controls the flow while the victim funds cards or a deposit.",
    left: [
      L("Plaćanje za obilazak prodavnica ili ocenu usluge zvuči jednostavno.", "Paid store visits or service ratings sound simple."),
      L("Brz dogovor bez formalnog intervjua u kancelariji.", "Fast arrangement without a formal office interview."),
      L("Obećanje povraćaja troškova posle slanja dokaza.", "A promise to reimburse costs after you send proof."),
      L("Poruke sa uputstvima korak po korak i rokovima.", "Messages with step-by-step instructions and deadlines.")
    ],
    right: [
      L("Kupovina poklon-kartica i slanje kodova trećem licu.", "Buying gift cards and sending codes to a third party."),
      L("Mobilni depozit lažnog čeka i prenos „viška“ pre nego što banka stornira.", "Mobile deposit of a fake check and transferring the overage before the bank reverses it."),
      L("Bilo koja uplata pre potpisanog ugovora sa proverljivim poslodavcem.", "Any payment before a signed contract with a verifiable employer."),
      L("Zahtev da ne pričaš sa bankom o svrhi uplate.", "A request not to tell the bank the purpose of the payment.")
    ],
    p3sr: "Uvodi se kupovina kartica, depozit ili „taksa za isplatu“ pre navodnog povraćaja.",
    p3en: "Gift card buying, a deposit, or a payout fee is introduced before alleged reimbursement.",
    r10sr: "Lažni mystery shopper traži kupovinu kartica ili slanje kodova trećem licu.",
    r10en: "The fake mystery shopper asks for gift cards or sending codes to a third party.",
    stepMidSr: "Proveri ime firme na zvaničnom sajtu i pozovi objavljeni HR broj.",
    stepMidEn: "Verify the company name on the official site and call the published HR number.",
    hisr: "Žrtva veruje da je posao legitimna evaluacija. Zajednička provera oglasa i zvaničnog sajta smanjuje otpor.",
    hien: "The victim believes the job is legitimate evaluation. Checking the ad and official site together lowers resistance."
  },
  {
    slug: "employment-visa-job-scam",
    title_sr: "Prevara sa radnom vizom i poslom u inostranstvu",
    title_en: "Employment visa job scam",
    hero_sr: "Ponuda posla u inostranstvu → naknade za vizu i agenciju → nema radne dozvole.",
    hero_en: "Abroad job offer → visa and agency fees → no work permit.",
    meta_sr: "Lažna radna viza: agencijske takse, prevod, medicina. Provera ambasade i poslodavca.",
    meta_en: "Fake work visa: agency fees, translation, medical. Verify embassy and employer.",
    summary_sr: "Nude se posao i pomoć oko radne vize uz seriju naknada za agenciju, prevod i administraciju. Eskalacija traje dok novac ne ode. Signal: uplata pre potpisanog ugovora i pre zvaničnog viza-procesa.",
    summary_en: "A job and visa help are offered with a series of agency, translation, and admin fees. Escalation lasts until the money is gone. Signal: payment before a signed contract and official visa steps.",
    subtitle_sr: "Inostranstvo kao mamac: takse za vizu i papire bez pravog angažmana.",
    subtitle_en: "Abroad as bait: visa and paperwork fees without a real engagement.",
    i1sr: "Kandidat dobija ponudu posla u drugoj državi uz obećanje da agencija reši vizu i smeštaj. Brzo se uvode troškovi za registraciju, prevod i medicinski pregled.",
    i1en: "The candidate gets a job offer abroad with a promise that an agency will handle visa and housing. Registration, translation, and medical costs appear quickly.",
    i2sr: "Pravi poslodavac i državni postupci imaju javne korake; ne završavaju se uplatom na privatni račun pre potpisanog ugovora.",
    i2en: "Real employers and state processes have public steps; they do not end with payment to a private account before a signed contract.",
    model_sr: "kontakt → ponuda → naknade za vizu i agenciju → nema potvrde ambasade.",
    model_en: "contact → offer → visa and agency fees → no embassy confirmation.",
    model_body: "kontakt → ponuda → naknade za vizu i agenciju → nema potvrde ambasade.",
    gsr: "Koristi se želja za radom u inostranstvu i složenost procedure. Novac ide pre nego što postoji proverljiva radna ponuda.",
    gen: "It exploits the wish to work abroad and process complexity. Money moves before there is a verifiable job offer.",
    left: [
      L("Visoka plata i smeštaj kao deo paketa.", "High pay and housing as part of the package."),
      L("Lažni dokumenti sa logotipom kompanije ili agencije.", "Fake documents with a company or agency logo."),
      L("Hitnost zbog „poslednjih mesta“ u programu.", "Urgency due to last spots in the program."),
      L("Komunikacija preko WhatsApp-a ili ličnog imejla.", "Communication via WhatsApp or personal email.")
    ],
    right: [
      L("Uplata na privatni račun ili Western Union umesto zvaničnog kanala.", "Payment to a private account or Western Union instead of an official channel."),
      L("Zahtev za sken pasoša i plaćanje pre intervjua u ambasadi.", "Passport scan and payment requested before an embassy interview."),
      L("Nema javnog oglasa na sajtu kompanije koju možeš sam pozvati.", "No public posting on a company site you can call yourself."),
      L("Obećanje da će vizu „rešiti“ bez tvog prisustva u konzularnom delu.", "A promise to fix the visa without your presence at consular steps.")
    ],
    p3sr: "Traže se agencijska naknada, taksa za „brzu obradu“ ili depozit za avionsku kartu pre izdavanja ugovora.",
    p3en: "An agency fee, expedite fee, or flight deposit is requested before a contract is issued.",
    r10sr: "„Radna viza“ se plaća pre potpisanog ugovora i pre provere u ambasadi.",
    r10en: "The work visa is paid for before a signed contract and before embassy verification.",
    stepMidSr: ST[0],
    stepMidEn: ST[1],
    hisr: HS,
    hien: HE
  },
  {
    slug: "hr-file-verification-phishing",
    title_sr: "Fišing „verifikacija HR fascikle“",
    title_en: "HR file verification phishing",
    hero_sr: "Lažni HR link → prijava lozinke ili dokumenta → kompromitovan nalog.",
    hero_en: "Fake HR link → password or document login → compromised account.",
    meta_sr: "Lažna HR poruka za ažuriranje fascikle: link, forma, krađa naloga. Provera domena i MFA.",
    meta_en: "Fake HR message to update a file: link, form, account theft. Verify domain and MFA.",
    summary_sr: "Imejl ili poruka glumi HR i traži potvrdu fascikle, beneficija ili ličnih podataka na lažnoj stranici. Eskalacija vodi u preuzimanje naloga ili krađu dokumenata. Signal: link van zvaničnog SSO ili domena firme.",
    summary_en: "Email or chat pretends to be HR and asks you to confirm a file, benefits, or personal data on a fake page. Escalation leads to account takeover or document theft. Signal: link outside official SSO or company domain.",
    subtitle_sr: "HR kao maska: lažna prijava i upload dokumenata.",
    subtitle_en: "HR as a cover: fake login and document upload.",
    i1sr: "Poruka tvrdi da je rok za ažuriranje ličnog dosijea, beneficija ili poreza i šalje link na formu koja liči na intranet.",
    i1en: "The message claims a deadline to update a personnel file, benefits, or taxes and sends a link to an intranet-like form.",
    i2sr: "Pravi HR obaveštava kroz poznati kanal i ne traži lozinku na stranici koja nije na domenu kompanije.",
    i2en: "Real HR notifies via a known channel and does not ask for a password on a page not on the company domain.",
    model_sr: "poruka → lažna forma → unos lozinke ili fajlova → kompromitacija.",
    model_en: "message → fake form → password or file entry → compromise.",
    model_body: "poruka → lažna forma → unos lozinke ili fajlova → kompromitacija.",
    gsr: "Koristi se rutina zaposlenih da potpisuju dokumente. Jedan klik na lažnoj prijavi daje pristup pošti i sistemima.",
    gen: "It exploits employees' routine of signing documents. One click on a fake login gives access to mail and systems.",
    left: [
      L("Imejl izgleda kao interni šablon sa logotipom.", "The email looks like an internal template with a logo."),
      L("Rok „do kraja dana“ za ažuriranje podataka.", "An end-of-day deadline to update data."),
      L("Poziv na saradnju sa IT ili HR u istoj poruci.", "IT or HR cooperation mentioned in the same message."),
      L("Link ka „sigurnom portalu“ za otpremu pasoša ili ugovora.", "A link to a secure portal to upload a passport or contract.")
    ],
    right: [
      L("Domen u linku nije isti kao zvanični sajt ili SSO.", "The link domain is not the same as the official site or SSO."),
      L("Traži se unos lozinke za mejl ili Microsoft/Google nalog.", "Password entry is requested for email or Microsoft/Google account."),
      L("Forma traži i broj kartice „za verifikaciju identiteta“.", "The form also asks for a card number for identity verification."),
      L("Zahtev za odobrenje OAuth aplikaciji sa širokim pristupom.", "Approval is requested for an OAuth app with broad access.")
    ],
    p3sr: "Otvara se lažna prijava ili upload gde unosiš lozinku, 2FA kod ili osetljive fajlove koji se odmah preuzimaju.",
    p3en: "A fake login or upload page collects your password, 2FA code, or sensitive files that are taken immediately.",
    r10sr: "HR traži lozinku mejla na stranici koja nije na domenu kompanije.",
    r10en: "HR asks for your email password on a page not on the company domain.",
    stepMidSr: "Pozovi interni IT ili HR broj sa intraneta i pročitaj im URL bez klika.",
    stepMidEn: "Call internal IT or HR from the intranet and read them the URL without clicking.",
    hisr: "Zaposleni želi da bude „redovan“. Zajedničko čitanje adrese linka otkriva lažni domen.",
    hien: "The employee wants to be compliant. Reading the link address together exposes the fake domain.",
    overlaps: [
      "phishing",
      "fake-hr-scam",
      "job-scam",
      "recruitment-scam",
      "work-from-home-scam",
      "oauth-consent-phishing"
    ],
    tags: ["posao", "fišing", "krađa podataka"]
  },
  {
    slug: "timesheet-correction-scam",
    title_sr: "Prevara sa korekcijom timesheet-a ili satnice",
    title_en: "Timesheet correction scam",
    hero_sr: "Lažni HR ili menadžer → link za „ispravku“ → krađa naloga.",
    hero_en: "Fake HR or manager → correction link → account theft.",
    meta_sr: "Lažna poruka o grešci u satnici: link, prijava, prevara. Provera kanala i domena.",
    meta_en: "Fake timesheet error message: link, login, fraud. Verify channel and domain.",
    summary_sr: "Stiže hitna poruka da ispraviš satnicu ili timesheet pre isplate. Link vodi na lažnu prijavu koja krade nalog. Eskalacija može uključiti lažnu uplatu ili zahtev za povrat. Signal: komunikacija van sistema za vreme koje već koristiš.",
    summary_en: "An urgent message asks you to fix a timesheet before payroll. The link leads to a fake login that steals the account. Escalation may include a fake payment or refund request. Signal: communication outside the time system you already use.",
    subtitle_sr: "Satnica kao hitan razlog za lažnu prijavu.",
    subtitle_en: "Timesheet as an urgent pretext for a fake login.",
    i1sr: "Poruka glavi menadžera ili HR i traži da odmah potvrdiš sate na eksternom linku jer sistem navodno pada.",
    i1en: "The message spoofs a manager or HR and asks you to confirm hours on an external link because the system allegedly fails.",
    i2sr: "Pravo ispravljanje sati ide kroz postojeći portal za vreme ili obračun koji već koristiš.",
    i2en: "Real hour corrections go through the time or payroll portal you already use.",
    model_sr: "hitna poruka → lažni link → krađa naloga → zloupotreba.",
    model_en: "urgent message → fake link → account theft → abuse.",
    model_body: "hitna poruka → lažni link → krađa naloga → zloupotreba.",
    gsr: "Koristi se strah od kašnjenja plate. Žrtva klika pre nego što proveri adresu linka.",
    gen: "It exploits fear of late pay. The victim clicks before checking the link address.",
    left: [
      L("Predmet poruke je „hitna isplata“ ili greška u sistemima.", "The subject is urgent payroll or a system error."),
      L("Lažni prikaz imena šefa ili kolege u polju From.", "A spoofed boss or colleague name in the From field."),
      L("Kratka poruka bez detalja o konkretnom mesecu u sistemu.", "A short message without specifics about the month in the system."),
      L("Link ka „backup“ portalu za zaposlene.", "A link to a backup employee portal.")
    ],
    right: [
      L("URL ne odgovara poznatom domenu za vreme i obračun.", "The URL does not match the known time and payroll domain."),
      L("Traži se ponovna prijava iako si već u sesiji.", "Re-login is requested although you are already in a session."),
      L("Zahtev za kod iz aplikacije banke ili mejla u istom toku.", "A request for a code from the bank app or email in the same flow."),
      L("Poruka stiže na lični mejl umesto na poslovni kanal.", "The message arrives on personal email instead of the work channel.")
    ],
    p3sr: "Otvara se forma koja traži korisničko ime, lozinku ili 2FA kod da bi se „sinhronizovala“ satnica.",
    p3en: "A form asks for username, password, or a 2FA code to sync the timesheet.",
    r10sr: "Ispravka timesheet-a traži prijavu na domen koji nije tvoj poslodavac.",
    r10en: "Timesheet correction asks you to log in on a domain that is not your employer.",
    stepMidSr: ST[0],
    stepMidEn: ST[1],
    hisr: HS,
    hien: HE,
    tags: ["posao", "fišing"]
  },
  {
    slug: "fake-press-accreditation-scam",
    title_sr: "Lažna medijska akreditacija",
    title_en: "Fake press accreditation scam",
    hero_sr: "Poziv na događaj → naknada za akreditaciju → nema propusnice.",
    hero_en: "Event invite → accreditation fee → no pass.",
    meta_sr: "Lažna press akreditacija: taksa, lažni sajt, nema ulaza. Provera organizatora.",
    meta_en: "Fake press accreditation: fee, fake site, no entry. Verify organizer.",
    summary_sr: "Novinar ili kreator dobija poziv da pokrije događaj uz naknadu za akreditaciju, štampu ili ID kartu. Eskalacija dodaje takse dok se ne iscrpi novac. Signal: uplata pre zvanične liste medija na sajtu organizatora.",
    summary_en: "A journalist or creator gets an invite to cover an event with a fee for accreditation, press kit, or ID card. Escalation adds fees until money runs out. Signal: payment before an official media list on the organizer site.",
    subtitle_sr: "Događaj i backstage kao mamac za unaprednu uplatu.",
    subtitle_en: "Event and backstage as bait for upfront payment.",
    i1sr: "Stiže profesionalno pismo sa logotipom festivala ili brenda i traži se brza uplata za akreditaciju ili VIP zonu.",
    i1en: "A professional letter with a festival or brand logo arrives and asks for quick payment for accreditation or a VIP zone.",
    i2sr: "Prave akreditacije idu kroz poznati medijski odnos ili javno objavljen kontakt organizatora.",
    i2en: "Real accreditation goes through known press relations or a publicly listed organizer contact.",
    model_sr: "poziv → naknada za akreditaciju → dodatne takse → nema ulaza.",
    model_en: "invite → accreditation fee → extra charges → no entry.",
    model_body: "poziv → naknada za akreditaciju → dodatne takse → nema ulaza.",
    gsr: "Koristi se želja za pristupom i strah od propustanja prilike. Novac ide pre nego što se proveri lista za medije.",
    gen: "It exploits access desire and fear of missing out. Money moves before the media list is verified.",
    left: [
      L("Poziv na veliki festival, modnu reviju ili sportski događaj.", "An invite to a big festival, fashion show, or sports event."),
      L("Lažni press pass ili šablon ugovora o ekskluzivi.", "A fake press pass or exclusivity contract template."),
      L("Hitnost jer „ostaje pet akreditacija“.", "Urgency because five accreditations remain."),
      L("Portfolio ili Instagram kao dokaz „ozbiljnosti“.", "Portfolio or Instagram as proof of seriousness.")
    ],
    right: [
      L("Organizator na sajtu nema isti kontakt ni isti događaj.", "The organizer site shows a different contact or event."),
      L("Uplata ide na privatni račun ili PayPal nepoznatog imena.", "Payment goes to a private account or PayPal under an unknown name."),
      L("Nema imena kontakt osobe koja postoji u javnom imeniku.", "No contact person name that exists in a public directory."),
      L("Zahtev za uplatu pre provere redakcije ili ugovora sa izdavačem.", "Payment requested before editorial or publisher contract check.")
    ],
    p3sr: "Traži se naknada za štampu propusnice, osiguranje na licu mesta ili „depozit za opremu“.",
    p3en: "A fee is requested for printing a pass, on-site insurance, or equipment deposit.",
    r10sr: "Medijska akreditacija se plaća pre nego što organizator potvrdi tvoj medij na zvaničnom kanalu.",
    r10en: "Press accreditation is paid before the organizer confirms your outlet on an official channel.",
    stepMidSr: "Pozovi javni broj organizatora sa sajta događaja i pitaj za isti naziv akreditacije.",
    stepMidEn: "Call the organizer's public number from the event site and ask about the same accreditation name.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "mediji"]
  },
  {
    slug: "fake-copyright-strike-removal",
    title_sr: "Lažno uklanjanje copyright strike-a ili „strike“ na platformi",
    title_en: "Fake copyright strike removal scam",
    hero_sr: "Upozorenje o kršenju → link ili uplata → krađa naloga.",
    hero_en: "Violation warning → link or payment → account theft.",
    meta_sr: "Lažni strike ili DMCA: forma, uplata, fišing. Provera u aplikaciji platforme.",
    meta_en: "Fake strike or DMCA: form, payment, phishing. Check in the platform app.",
    summary_sr: "Kreator dobija poruku da je kanal u opasnosti od brisanja i mora hitno da potvrdi autorska prava ili plati taksu. Link vodi na lažnu prijavu ili lažnu uplatu. Signal: poruka ne stiže u zvaničnom centru za pomoć platforme.",
    summary_en: "A creator is told the channel risks deletion and must urgently confirm rights or pay a fee. The link leads to a fake login or payment. Signal: the message does not appear in the platform's official help center.",
    subtitle_sr: "Strah od gubitka kanala kao okidač za fišing.",
    subtitle_en: "Fear of losing the channel as a phishing trigger.",
    i1sr: "Poruka ili imejl imitira YouTube, Instagram, TikTok ili rights holder i traži odmah da otvoriš link da ukloniš strike.",
    i1en: "A message or email imitates YouTube, Instagram, TikTok, or a rights holder and asks you to open a link now to remove a strike.",
    i2sr: "Prava upozorenja vide se u studiju kreatora ili zvaničnoj aplikaciji, ne preko eksternog četa.",
    i2en: "Real warnings appear in the creator studio or official app, not via external chat.",
    model_sr: "upozorenje → lažni link → krađa naloga ili uplata.",
    model_en: "warning → fake link → account theft or payment.",
    model_body: "upozorenje → lažni link → krađa naloga ili uplata.",
    gsr: "Koristi se strah od gubitka publike i prihoda. Brzina sprečava proveru u samoj aplikaciji.",
    gen: "It exploits fear of losing audience and revenue. Speed blocks checking inside the app itself.",
    left: [
      L("Logotip platforme i jezici koji zvuče zvanično.", "Platform logo and language that sounds official."),
      L("Pretnja trajnim banom u roku od sat vremena.", "Threat of a permanent ban within an hour."),
      L("Ponuda da platiš „brzu reviziju“ umesto čekanja.", "An offer to pay for a fast review instead of waiting."),
      L("Kontakt preko WhatsApp-a ili lažnog support naloga.", "Contact via WhatsApp or a fake support account.")
    ],
    right: [
      L("U aplikaciji platforme nema istog upozorenja.", "The same warning does not appear in the platform app."),
      L("Link vodi na domen koji nije platforma.", "The link leads to a domain that is not the platform."),
      L("Traži se lozinka ili 2FA na eksternoj stranici.", "Password or 2FA is requested on an external page."),
      L("Zahtev za kripto ili poklon-karticu da se strike „ukloni“.", "Crypto or a gift card is requested to remove the strike.")
    ],
    p3sr: "Traži se naknada za „DMCA obradu“, verifikaciju vlasništva ili depozit da se kanal otključa.",
    p3en: "A fee is requested for DMCA handling, ownership verification, or a deposit to unlock the channel.",
    r10sr: "Uklanjanje strike-a traži uplatu van zvanične monetizacije ili support stranice platforme.",
    r10en: "Strike removal asks for payment outside official monetization or platform support.",
    stepMidSr: "Otvori platformu direktno iz aplikacije i uporedi poruku sa obaveštenjima u studiju.",
    stepMidEn: "Open the platform directly from the app and compare the message with studio notifications.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "kreatori", "fišing"]
  },
  {
    slug: "publisher-literary-agent-fee",
    title_sr: "Naknada lažnog izdavača ili književnog agenta",
    title_en: "Publisher or literary agent fee scam",
    hero_sr: "Pohvala rukopisa → naknada za čitanje ili štampu → nema izdanja.",
    hero_en: "Manuscript praise → reading or print fee → no publication.",
    meta_sr: "Lažni izdavač ili agent: reading fee, vanity press. Provera ugleda i ugovora.",
    meta_en: "Fake publisher or agent: reading fee, vanity press. Verify reputation and contract.",
    summary_sr: "Autor dobija brzu pohvalu i ponudu ugovora uz naknadu za čitanje, marketing ili predtiskavanje. Eskalacija dodaje nove pakete bez distribucije. Signal: uplata pre nezavisnih referenci i pre jasnog plana distribucije.",
    summary_en: "An author gets quick praise and a contract offer with a fee for reading, marketing, or pre-printing. Escalation adds packages without distribution. Signal: payment before independent references and a clear distribution plan.",
    subtitle_sr: "Knjiga kao san: unapredne naknade bez pravog tržišta.",
    subtitle_en: "The book dream: upfront fees without a real market.",
    i1sr: "Lažni agent ili mali izdavač hvale rukopis i traže depozit da bi ga stavili „u red“ ili štampali uz garanciju koja ne postoji.",
    i1en: "A fake agent or small publisher praises the manuscript and asks for a deposit to queue it or print it with a non-existent guarantee.",
    i2sr: "Ozbiljni agenti retko naplaćuju čitanje unapred; prihod im dolazi od prodaje prava, ne od autora na početku.",
    i2en: "Serious agents rarely charge upfront reading fees; revenue comes from rights sales, not from the author at the start.",
    model_sr: "hvatanje autora → naknada → dodatni paketi → nema prodaje.",
    model_en: "hook author → fee → extra packages → no sales.",
    model_body: "hvatanje autora → naknada → dodatni paketi → nema prodaje.",
    gsr: "Koristi se želja za objavljivanjem. Autor plaća pre nego što vidi nezavisnu potvrdu o distribuciji.",
    gen: "It exploits the wish to be published. The author pays before seeing independent proof of distribution.",
    left: [
      L("Brza pohvala bez konkretne kritike odeljaka.", "Quick praise without concrete critique of sections."),
      L("Ponuda „svetske distribucije“ uz mali početni trošak.", "World distribution offer with a small starting cost."),
      L("Lažni ISBN ili lažni sajt sa stock fotografijama.", "Fake ISBN or a stock-photo website."),
      L("Poziv na plaćeni webinar o izdavaštvu.", "Invite to a paid publishing webinar.")
    ],
    right: [
      L("Nema knjiga istog izdavača u bibliotekama ili knjižarama koje možeš proveriti.", "No books from the same publisher appear in libraries or shops you can check."),
      L("Ugovor je nejasan o pravima i naknadama po prodaji.", "The contract is vague about rights and per-sale royalties."),
      L("Traži se kompletan rukopis i novac u istom koraku bez advokata.", "Full manuscript and money are requested in one step without a lawyer."),
      L("Recenzije na sajtu su generičke ili kopirane.", "Site reviews are generic or copied.")
    ],
    p3sr: "Traži se reading fee, naknada za lekturu, obavezni marketing paket ili predplata štampanja.",
    p3en: "A reading fee, editing fee, mandatory marketing package, or print prepayment is requested.",
    r10sr: "Izdavač ili agent traži novac pre nego što pokaže proverljivu prodaju drugih naslova.",
    r10en: "The publisher or agent asks for money before showing verifiable sales of other titles.",
    stepMidSr: "Pitaj dva nezavisna autora u udruženju ili biblioteci o imenu izdavača.",
    stepMidEn: "Ask two independent authors in an association or library about the publisher name.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "književnost"]
  },
  {
    slug: "virtual-assistant-payment-forwarding",
    title_sr: "Virtuelni asistent i preusmeravanje uplata (money mule)",
    title_en: "Virtual assistant payment forwarding scam",
    hero_sr: "Posao asistenta → pristup novcu ili prenos → pranje ili gubitak.",
    hero_en: "Assistant job → money access or transfer → laundering or loss.",
    meta_sr: "Lažni VA posao: primaš i šalješ novac, provizija. Pravni rizik. Provera poslodavca.",
    meta_en: "Fake VA job: receive and send money, commission. Legal risk. Verify employer.",
    summary_sr: "Nude se rad od kuće kao asistent uz zadatak da primaš uplate i prosleđuješ ih dalje uz mali procenat. Eskalacija traži više transakcija i pristup nalogu. Signal: posao je uglavnom kretanje novca, ne administracija.",
    summary_en: "Remote assistant work is offered with a task to receive payments and forward them for a small cut. Escalation seeks more transactions and account access. Signal: the job is mostly moving money, not administration.",
    subtitle_sr: "Asistent kao pokriće za mule tok.",
    subtitle_en: "Assistant work as cover for a mule flow.",
    i1sr: "Poslodavac traži da koristiš lični račun ili PayPal da „ubrzate isplate klijentima“ dok on navodno rešava devize.",
    i1en: "The employer asks you to use a personal account or PayPal to speed client payouts while they allegedly handle currency issues.",
    i2sr: "Pravi asistenti ne primaju strane uplate na lični račun radi prosleđivanja trećim licima.",
    i2en: "Real assistants do not receive foreign payments to a personal account to forward to third parties.",
    model_sr: "oglas → angažman → prenos novca → pravni rizik ili blokada naloga.",
    model_en: "ad → engagement → money transfer → legal risk or account block.",
    model_body: "oglas → angažman → prenos novca → pravni rizik ili blokada naloga.",
    gsr: "Koristi se potreba za fleksibilnim poslom. Žrtva postaje čvor u lancu prljavog novca.",
    gen: "It exploits the need for flexible work. The victim becomes a node in a dirty-money chain.",
    left: [
      L("Oglas na oglasniku ili LinkedIn-u sa visokom satnicom.", "A classified or LinkedIn ad with a high hourly rate."),
      L("Minimalan intervju i odmah poverenje sa pristupom finansijama.", "Minimal interview and immediate trust with finance access."),
      L("Obećanje provizije od 5–10% po transakciji.", "A promise of 5–10% commission per transaction."),
      L("„Probni period“ sa stvarnim transferima prvog dana.", "A trial period with real transfers on day one.")
    ],
    right: [
      L("Posao nema kalendare, dokumenta ni CRM zadataka.", "The job has no calendars, documents, or CRM tasks."),
      L("Uputstva dolaze samo oko iznosa, vremena i primaoca.", "Instructions only cover amount, time, and recipient."),
      L("Zabrana objašnjavanja banke šta radiš.", "A ban on explaining to the bank what you are doing."),
      L("Zahtev da kupuješ Bitcoin ili prepaid da „balansiraš“ račun.", "A request to buy Bitcoin or prepaid to balance the account.")
    ],
    p3sr: "Traži se prvi prenos sredstava ili povezivanje PayPal-a pre nego što potpišeš ugovor o poverljivosti.",
    p3en: "A first funds transfer or PayPal linking is requested before you sign any confidentiality agreement.",
    r10sr: "Virtuelni asistent koji radi samo prebacivanje novca trećim licima je crvena zastavica.",
    r10en: "A virtual assistant job that only forwards money to third parties is a red flag.",
    stepMidSr: ST[0],
    stepMidEn: ST[1],
    hisr: HS,
    hien: HE,
    overlaps: [
      "money-mule-recruitment",
      "job-scam",
      "recruitment-scam",
      "work-from-home-scam",
      "fake-hr-scam",
      "advance-fee-fraud"
    ]
  }
];
