const L = (sr, en) => ({ sr, en });
const ST = [
  "Proveri poslodavca na zvaničnom sajtu i pozovi broj sa liste kontakata, ne iz poruke.",
  "Verify the employer on the official site and call the number from the contact list, not from the message."
];
const HS = "Kandidat žuri zbog prilike. Zajednička provera kroz zvanični careers sajt ili javni telefon kompanije smanjuje otpor.";
const HE = "The candidate rushes because of the opportunity. Checking together via the official careers site or company public phone lowers resistance.";

module.exports = [
  {
    slug: "airline-crew-recruitment-scam",
    title_sr: "Lažni zapošljavanje avio-osoblja",
    title_en: "Airline crew recruitment scam",
    hero_sr: "Posada u avio-kompaniji → takse → nema obuke ni leta.",
    hero_en: "Airline crew → fees → no training or flight.",
    meta_sr: "Lažni pilot/kabin: agencija, uniforma, kurs. Provera avio-kompanije.",
    meta_en: "Fake pilot/cabin: agency, uniform, course. Verify the airline.",
    summary_sr: "Nude se brza šansa za posadu uz naknade za obuku, uniformu ili bezbednosnu proveru. Eskalacija dodaje korake bez leta. Signal: novac pre zvaničnog careers kanala avio-kompanije.",
    summary_en: "A fast chance to join crew is offered with fees for training, uniform, or security checks. Escalation adds steps with no flight. Signal: money before the airline's official careers channel.",
    subtitle_sr: "Uniforma i krila kao mamac za unapredne uplate.",
    subtitle_en: "Uniform and wings as bait for upfront payments.",
    i1sr: "Lažni HR avio-kompanije šalje ponudu i traži uplatu za „Cabin Crew Academy“ ili slično pre intervjua u hangaru.",
    i1en: "Fake airline HR sends an offer and asks payment for a cabin crew academy before a hangar interview.",
    i2sr: "Prave avio-kompanije objavljuju oglase na svom sajtu i ne naplaćuju obuku pre ugovora na isti način kao lažne škole.",
    i2en: "Real airlines post on their site and do not charge training like fake schools before a contract in the same way.",
    model_sr: "ponuda → taksa za obuku → nema angažmana.",
    model_en: "offer → training fee → no hire.",
    model_body: "ponuda → taksa za obuku → nema angažmana.",
    gsr: "Koristi se prestiž profesije i želja za putovanjem. Žrtva ne upoređuje sa zvaničnim oglasom.",
    gen: "It exploits profession prestige and travel desire. The victim does not compare with the official posting.",
    left: [
      L("Logo avio-kompanije na imejlu.", "Airline logo on email."),
      L("Zahtev za visinu, težinu i jezik kao kod pravog procesa.", "Height, weight, and language requests like a real process."),
      L("Hitni rok jer „otvara se baza“.", "Urgent deadline because a database opens."),
      L("Poziv na plaćeni online kurs kao uslov.", "Invite to a paid online course as a condition.")
    ],
    right: [
      L("Imejl domen nije domen avio-kompanije.", "The email domain is not the airline domain."),
      L("Nema broja leta i baze dodeljivanja u zvaničnom formatu.", "No flight number and base assignment in official format."),
      L("Škola nije povezana sa avio-kompanijom koju možeš potvrditi.", "The school is not linked to an airline you can confirm."),
      L("Traže se novčani transferi pre potpisanog angažmana.", "Money transfers are requested before a signed engagement.")
    ],
    p3sr: "Traži se uplata za medicinski paket, uniformu ili „security badge“ pre zvaničnog assessment centra.",
    p3en: "Payment is requested for a medical pack, uniform, or security badge before an official assessment centre.",
    r10sr: "Zapošljavanje posade traži novac pre careers stranice avio-kompanije koju proveravaš.",
    r10en: "Crew hiring asks for money before the airline careers page you verify.",
    stepMidSr: "Uporedi imejl sa kontaktima na zvaničnom sajtu avio-kompanije.",
    stepMidEn: "Compare the email with contacts on the airline's official site.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "avijacija"]
  },
  {
    slug: "embassy-local-hire-scam",
    title_sr: "Lažno zapošljavanje preko ambasade ili lokalnog zapošljavanja",
    title_en: "Embassy local hire scam",
    hero_sr: "Ambasada ili lokalni skaut → naknada → nema ugovora.",
    hero_en: "Embassy or local scout → fee → no contract.",
    meta_sr: "Lažni lokalni hire: taksa, lažni pečat. Ambasada ne naplaćuje posao.",
    meta_en: "Fake local hire: fee, fake stamp. Embassies do not sell jobs.",
    summary_sr: "Neko se predstavlja kao kontakt ambasade ili lokalni skaut koji može obezbediti posao za državljane; traži naknadu za listu poslodavaca ili vizu. Eskalacija dodaje takse. Signal: uplata za „pristup“ ambasadnom poslu.",
    summary_en: "Someone poses as an embassy contact or local scout who can secure jobs for nationals and asks a fee for employer lists or visa help. Escalation adds fees. Signal: payment for access to embassy-related work.",
    subtitle_sr: "Autoritet ambasade kao lažna garancija.",
    subtitle_en: "Embassy authority as a false guarantee.",
    i1sr: "Poruka tvrdi da ambasada ima program lokalnog zapošljavanja i traži depozit da bi te stavili na listu.",
    i1en: "The message claims the embassy has a local employment program and asks a deposit to put you on a list.",
    i2sr: "Ambasade ne prodaju pozicije i ne naplaćuju takve liste preko privatnih računa.",
    i2en: "Embassies do not sell positions or charge such lists via private accounts.",
    model_sr: "lažni autoritet → uplata → nema liste.",
    model_en: "fake authority → payment → no list.",
    model_body: "lažni autoritet → uplata → nema liste.",
    gsr: "Koristi se poštovanje prema diplomatskoj misiji. Žrtva ne poziva javni broj ambasade.",
    gen: "It exploits respect for a diplomatic mission. The victim does not call the embassy public number.",
    left: [
      L("Pečat i zaglavlje koji liče na zvaničan papir.", "A stamp and letterhead resembling official paper."),
      L("Jezik koji spominje „konzularni odeljak“.", "Language mentioning a consular section."),
      L("Hitnost zbog „kvote meseca“.", "Urgency due to a monthly quota."),
      L("Lažni broj telefona koji deluje kao lokalni fiksni.", "A fake phone number that looks like a local landline.")
    ],
    right: [
      L("Ambasada na svom sajtu nema taj program.", "The embassy site does not list that program."),
      L("Uplata ide na fizičko lice, ne na račun misije.", "Payment goes to an individual, not a mission account."),
      L("Konzularni telefon koji si našao na sajtu ne potvrđuje osobu iz poruke.", "The consular phone from the site does not confirm the person in the message."),
      L("Zahtev da ne zoveš ambasadu direktno.", "A request not to call the embassy directly.")
    ],
    p3sr: "Traži se taksa za „verifikaciju biometrije“, kurirsku dostavu pasoša ili hitnu obradu liste.",
    p3en: "A fee is requested for biometric verification, passport courier, or expedited list processing.",
    r10sr: "Posao preko ambasade traži novac pre nego što konzularni službenik potvrdi program.",
    r10en: "Embassy-related work asks for money before a consular officer confirms the program.",
    stepMidSr: "Pozovi broj ambasade sa zvaničnog sajta države i pitaj za isti naziv programa.",
    stepMidEn: "Call the embassy number from the official government site and ask about the same program name.",
    hisr: HS,
    hien: HE,
    overlaps: ["government-impersonation", "job-scam", "recruitment-scam", "work-from-home-scam", "fake-hr-scam", "advance-fee-fraud", "phishing"],
    tags: ["posao", "diplomatija"]
  },
  {
    slug: "security-clearance-job-scam",
    title_sr: "Posao uz lažnu bezbednosnu dozvolu ili klirans",
    title_en: "Security clearance job scam",
    hero_sr: "Tajni projekat → naknada za klirans → nema projekta.",
    hero_en: "Secret project → clearance fee → no project.",
    meta_sr: "Lažni security clearance: taksa, NDA, lažni dokument. Država ne naplaćuje to preko agenta.",
    meta_en: "Fake security clearance: fee, NDA, fake document. The state does not charge via an agent.",
    summary_sr: "Nude se poslovi uz „nacionalnu bezbednosnu proveru“ i traži se uplata agentu za ubrzanje kliransa. Dokumenti su lažni. Signal: novac pre zvanične državne procedure koja je javno opisana.",
    summary_en: "Jobs are offered with national security vetting and an agent asks payment to speed clearance. Documents are fake. Signal: money before an official state process described in public guidance.",
    subtitle_sr: "Tajnost kao razlog da se plati pre provere.",
    subtitle_en: "Secrecy as a reason to pay before verification.",
    i1sr: "Regruter tvrdi da je projekat klasifikovan i da moraš platiti „predklirans“ da bi dobio pristup objektu.",
    i1en: "The recruiter claims the project is classified and you must pay pre-clearance to access the site.",
    i2sr: "Prave bezbednosne procedure ne završavaju se uplatom na lični račun posrednika pre intervjua.",
    i2en: "Real security procedures do not end with payment to an intermediary personal account before interviews.",
    model_sr: "tajni posao → uplata za klirans → nema ugovora.",
    model_en: "secret job → clearance payment → no contract.",
    model_body: "tajni posao → uplata za klirans → nema ugovora.",
    gsr: "Koristi se poštovanje prema državnoj tajnosti. Žrtva se plaši da pita zvanični izvor.",
    gen: "It exploits respect for state secrecy. The victim fears asking an official source.",
    left: [
      L("NDA koji zabranjuje razgovor sa bilo kim.", "An NDA banning talk with anyone."),
      L("Visoka dnevnica za kratkotrajan angažman.", "High daily pay for a short engagement."),
      L("Lažni pečat „ministarstva“ na PDF-u.", "A fake ministry stamp on a PDF."),
      L("Komunikacija samo preko šifrovanog četa.", "Communication only via encrypted chat.")
    ],
    right: [
      L("Nema javnog oglasa ili tendera koji pokriva isti posao.", "No public vacancy or tender covering the same job."),
      L("Zahtev za uplatu pre bilo kakvog susreta na adresi institucije.", "Payment requested before any meeting at an institution address."),
      L("Agent nema ime koje postoji u imeniku institucije.", "The agent has no name in an institution directory."),
      L("Pritisak da ne proveravaš sa policijom ili ministarstvom.", "Pressure not to check with police or ministry.")
    ],
    p3sr: "Traži se uplata za biometriju, „level upgrade“ kliransa ili osiguranje tajnosti.",
    p3en: "Payment is requested for biometrics, clearance level upgrade, or secrecy insurance.",
    r10sr: "Bezbednosni klirans se prodaje uz unaprednu uplatu pre zvaničnog postupka.",
    r10en: "Security clearance is sold with upfront payment before an official process.",
    stepMidSr: "Kontaktiraj javnu liniju institucije koja navodno daje klirans i pitaj da li postoji taj korak.",
    stepMidEn: "Contact the public line of the institution that allegedly issues clearance and ask whether that step exists.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "bezbednost"]
  },
  {
    slug: "background-check-fee-scam",
    title_sr: "Naknada za lažnu background proveru",
    title_en: "Background check fee scam",
    hero_sr: "Posao uz „background check“ → uplata → nema izveštaja.",
    hero_en: "Job with background check → payment → no report.",
    meta_sr: "Lažna provera ličnosti: taksa, lažni izveštaj. Pravi poslodavac ne naplaćuje kandidatu unapred.",
    meta_en: "Fake vetting fee: charge, fake report. Real employers do not bill candidates upfront.",
    summary_sr: "Pre zaposlenja traži se uplata za kriminalnu proveru, kredit ili referencu preko treće strane. Izveštaj ne postoji ili je šablon. Signal: kandidat plaća proveru pre ugovora i pre poznatog provajdera.",
    summary_en: "Before hiring, payment is requested for criminal, credit, or reference checks via a third party. No real report or a template. Signal: the candidate pays before a contract and before a known provider.",
    subtitle_sr: "Provera kao usluga koja se naplaćuje žrtvi.",
    subtitle_en: "Checking as a service billed to the victim.",
    i1sr: "Link vodi na sajt koji traži karticu za „standardnu background proveru“ pre nego što vidiš ugovor.",
    i1en: "A link leads to a site that asks for a card for a standard background check before you see a contract.",
    i2sr: "Mnogi poslodavci plaćaju proveru sami ili koriste poznate provajdere sa jasnim cenovnikom.",
    i2en: "Many employers pay for checks themselves or use known providers with clear pricing.",
    model_sr: "ponuda → link za proveru → uplata → nema posla.",
    model_en: "offer → check link → payment → no job.",
    model_body: "ponuda → link za proveru → uplata → nema posla.",
    gsr: "Koristi se strah od gubitka ponude. Žrtva unosi karticu na lažnoj stranici.",
    gen: "It exploits fear of losing the offer. The victim enters a card on a fake page.",
    left: [
      L("Profesionalan izgled forme za unos podataka.", "A professional-looking data entry form."),
      L("Cena koja deluje mala u odnosu na platu.", "A price that looks small versus salary."),
      L("Garancija da ćeš proći ako nemaš zabeležbu.", "A guarantee you will pass if you have no record."),
      L("Rok od 24 sata.", "A 24-hour deadline.")
    ],
    right: [
      L("Provajder nije isti kao onaj koji poslodavac navodi na zvaničnom sajtu.", "The provider is not the one the employer lists on the official site."),
      L("Traže se i CVV i kompletan broj kartice.", "CVV and full card number are requested."),
      L("Nema potpisanog job offer-a od istog HR-a.", "No signed job offer from the same HR."),
      L("Domen sajta je nov i neregistrovan dugo.", "The site domain is new and not long registered.")
    ],
    p3sr: "Dodaje se hitna taksa za „međunarodnu bazu“ ili „Interpol proveru“.",
    p3en: "An urgent fee is added for an international database or Interpol check.",
    r10sr: "Background provera traži uplatu od kandidata pre ugovora na nepoznatom sajtu.",
    r10en: "Background check asks the candidate to pay before a contract on an unknown site.",
    stepMidSr: "Pitaj HR poslodavca koji provajder je ugovoren i uporedi URL.",
    stepMidEn: "Ask employer HR which provider is contracted and compare the URL.",
    hisr: HS,
    hien: HE
  },
  {
    slug: "certification-before-hire-scam",
    title_sr: "Obavezni sertifikat pre zaposlenja",
    title_en: "Certification before hire scam",
    hero_sr: "Posao uz obavezni kurs → skuplji nivo → nema posla.",
    hero_en: "Job with mandatory course → pricier tier → no job.",
    meta_sr: "Lažni sertifikat pre hire: online kurs, taksa. Provera da li firma traži taj sertifikat.",
    meta_en: "Fake pre-hire cert: online course, fee. Verify whether the firm requires that certificate.",
    summary_sr: "Nakon prijave traži se brz online sertifikat uz uplatu da bi se nastavio proces. Kursevi su bezvredni ili lažni. Signal: poslodavac koji ga traži ne postoji ili ne navodi taj sertifikat na zvaničnom oglasu.",
    summary_en: "After applying, a fast online certificate with a fee is required to continue. Courses are worthless or fake. Signal: the employer requesting it does not exist or does not list that certificate on the official posting.",
    subtitle_sr: "Edukacija kao dodatni sloj uplate.",
    subtitle_en: "Education as an extra payment layer.",
    i1sr: "Dobijaš listu odobrenih „akademija“ gde moraš platiti nivo bronze pre intervjua.",
    i1en: "You get a list of approved academies where you must pay bronze level before an interview.",
    i2sr: "Pravi poslodavac navodi konkretne licence koje priznaje i ne prodaje ih preko jednog linka u četu.",
    i2en: "A real employer lists specific recognised licences and does not sell them via one chat link.",
    model_sr: "ponuda → obavezni kurs → skuplji paket → nema angažmana.",
    model_en: "offer → mandatory course → pricier pack → no hire.",
    model_body: "ponuda → obavezni kurs → skuplji paket → nema angažmana.",
    gsr: "Koristi se strah da ne izgubiš mesto. Svaki nivo kursa košta više.",
    gen: "It exploits fear of losing the spot. Each course level costs more.",
    left: [
      L("Sertifikat koji možeš dobiti za sat vremena.", "A certificate you can get in an hour."),
      L("Popust ako platiš danas.", "A discount if you pay today."),
      L("Lažni logotip kompanije na diplomi.", "A fake company logo on the diploma."),
      L("„Hiring manager“ preporučuje jednu akademiju.", "A hiring manager recommends one academy.")
    ],
    right: [
      L("Isti kurs se ne pojavljuje u zahtevima na careers stranici.", "The same course does not appear in careers page requirements."),
      L("Akademija nema javnu adresu ili registraciju.", "The academy has no public address or registration."),
      L("Niko iz kompanije ne potpisuje pismo o obavezi kursa.", "No one from the company signs a letter about the course requirement."),
      L("Pritisak da kupiš zlatni paket da bi bio „prioritet“.", "Pressure to buy a gold package to be a priority.")
    ],
    p3sr: "Traži se nadoplata za „exam retake“ ili „accreditation fee“ pre zakazivanja intervjua.",
    p3en: "A top-up is requested for exam retake or accreditation fee before scheduling an interview.",
    r10sr: "Sertifikat pre zaposlenja se plaća pre nego što zvanični oglas to zahteva.",
    r10en: "A pre-hire certificate is paid before the official posting requires it.",
    stepMidSr: "Preuzmi PDF oglasa sa sajta poslodavca i uporedi zahteve sa porukom.",
    stepMidEn: "Download the vacancy PDF from the employer site and compare requirements with the message.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "obrazovanje"]
  },
  {
    slug: "training-bond-scam",
    title_sr: "Prevara sa obavezujućim ugovorom o obuci (training bond)",
    title_en: "Training bond scam",
    hero_sr: "Besplatna obuka → bond ili kazna → dug.",
    hero_en: "Free training → bond or penalty → debt.",
    meta_sr: "Lažni training bond: kazna ako odeš, prinuda. Provera advokatom.",
    meta_en: "Fake training bond: penalty if you leave, coercion. Check with a lawyer.",
    summary_sr: "Nude se obuka i posao uz ugovor da ostaneš godinu dana ili platiš veliku kaznu. Obuka je slaba, a pritisak da potpišeš odmah je jak. Signal: nejasna kazna i zabrana konsultacije sa advokatom.",
    summary_en: "Training and a job are offered with a contract to stay a year or pay a large penalty. Training is weak and signing pressure is high. Signal: vague penalty and ban on consulting a lawyer.",
    subtitle_sr: "Obuka kao zamka dugovanja.",
    subtitle_en: "Training as a debt trap.",
    i1sr: "Dokument traži potpis da ćeš platiti 5.000 EUR ako napustiš pre dve godine, uz obećanje visoke zarade.",
    i1en: "A document asks you to sign that you will pay €5,000 if you leave before two years, with a high pay promise.",
    i2sr: "Pravi bond ugovori su retki za niske pozicije i moraju biti čitljivi advokatu pre potpisa.",
    i2en: "Real bonds for entry roles are rare and must be readable by a lawyer before signing.",
    model_sr: "obuka → potpis bond-a → pritisak → dug ili rad bez plate.",
    model_en: "training → bond signature → pressure → debt or unpaid work.",
    model_body: "obuka → potpis bond-a → pritisak → dug ili rad bez plate.",
    gsr: "Koristi se nedostatak iskustva sa ugovorima. Žrtva potpisuje pod pritiskom.",
    gen: "It exploits inexperience with contracts. The victim signs under pressure.",
    left: [
      L("Obuka koja traje dan-dva uz odmah potpis.", "Training lasting a day or two with immediate signing."),
      L("Obećanje plaćene prakse koja se ne pojavi.", "A promise of paid practice that never appears."),
      L("Grupni pritisak u sali da svi potpišu.", "Group pressure in a room for everyone to sign."),
      L("Lažni broj advokata firme koji ne postoji.", "A fake company lawyer number that does not exist.")
    ],
    right: [
      L("Kazna je neproporcionalna plati koja je obećana.", "The penalty is disproportionate to promised pay."),
      L("Zabrana da poneseš ugovor kući.", "Ban on taking the contract home."),
      L("Nema jasnog opisa posla i radnog vremena.", "No clear job description and working hours."),
      L("Traže se lični podaci garanta ili roditelja.", "Guarantor or parent personal data is requested.")
    ],
    p3sr: "Traži se depozit koji se navodno vraća ako ostaneš, ali uslovi su nemogući.",
    p3en: "A deposit is requested that allegedly returns if you stay, but conditions are impossible.",
    r10sr: "Training bond sa kaznom traži se pre nego što vidiš platu na računu.",
    r10en: "A training bond with a penalty is requested before you see pay on your account.",
    stepMidSr: "Odnesi ugovor advokatu pre potpisa i ne potpisuj istog dana.",
    stepMidEn: "Take the contract to a lawyer before signing and do not sign the same day.",
    hisr: HS,
    hien: HE
  },
  {
    slug: "work-permit-medical-fee-scam",
    title_sr: "Naknada za medicinu uz radnu dozvolu",
    title_en: "Work permit medical fee scam",
    hero_sr: "Radna dozvola → obavezna klinika → previsoka uplata.",
    hero_en: "Work permit → mandatory clinic → overpriced payment.",
    meta_sr: "Lažni medicinski paket za dozvolu: jedna klinika, gotovina. Provera zvaničnog spiska.",
    meta_en: "Fake medical pack for permit: one clinic, cash. Verify official list.",
    summary_sr: "Agencija tvrdi da moraš kod određene klinike platiti skup paket da bi radna dozvola prošla. Cena je iznad tržišta ili klinika nije ovlašćena. Signal: gotovina ili transfer agentu, ne faktura zdravstvu.",
    summary_en: "An agency claims you must use a specific clinic and pay an expensive package for the work permit to pass. Price is above market or the clinic is not authorised. Signal: cash or transfer to an agent, not a health invoice.",
    subtitle_sr: "Zdravlje kao uslov koji kontroliše prevarant.",
    subtitle_en: "Health as a condition the fraudster controls.",
    i1sr: "Dobijaš uputstvo da ne možeš birati lekara i da uplatu šalješ agenciji koja „rezerviše termin“.",
    i1en: "You are told you cannot choose a doctor and must send payment to the agency that books the slot.",
    i2sr: "Zvanični vodiči za radne dozvole navode koje preglede priznaju, bez jedne nepoznate klinike kao jedine opcije.",
    i2en: "Official work permit guides list accepted exams without one unknown clinic as the only option.",
    model_sr: "dozvola → uput na kliniku → previsoka uplata → nema dokumenta.",
    model_en: "permit → clinic referral → overpayment → no document.",
    model_body: "dozvola → uput na kliniku → previsoka uplata → nema dokumenta.",
    gsr: "Koristi se strah od odbijanja dozvole. Žrtva plaća bez upoređivanja cena.",
    gen: "It exploits fear of permit denial. The victim pays without price comparison.",
    left: [
      L("Lista od jedne klinike bez alternativa.", "A list of one clinic with no alternatives."),
      L("Cena znatno iznad uobičajenog pregleda.", "A price far above a usual exam."),
      L("Hitan termin „sutra ujutru“.", "An urgent slot tomorrow morning."),
      L("Garancija da će rezultat biti „čist“.", "A guarantee the result will be clean.")
    ],
    right: [
      L("Klinika nije na zvaničnoj listi priznatih ustanova ako takva lista postoji.", "The clinic is not on an official recognised list if one exists."),
      L("Uplata ide agenciji, ne klinici.", "Payment goes to the agency, not the clinic."),
      L("Nema računa sa PIB-om ustanove.", "No invoice with the facility tax ID."),
      L("Rezultati ne stižu u roku koji zvanični proces dozvoljava.", "Results do not arrive within the official process timeline.")
    ],
    p3sr: "Traži se dodatak za „hitno štampanje“ ili kurira koji nosi rezultat ambasadi.",
    p3en: "An add-on is requested for rush printing or a courier who carries results to the embassy.",
    r10sr: "Medicinski trošak za radnu dozvolu ide preko agenta umesto direktno u zdravstvu.",
    r10en: "Medical cost for a work permit goes through an agent instead of directly to healthcare.",
    stepMidSr: "Pozovi kliniku direktno i pitaj cenu istog paketa bez agencije.",
    stepMidEn: "Call the clinic directly and ask the price for the same package without the agency.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "zdravlje"]
  },
  {
    slug: "fake-internship-stipend-scam",
    title_sr: "Lažna stipendija ili plata za praksu (internship)",
    title_en: "Fake internship stipend scam",
    hero_sr: "Praksa sa stipendijom → naknada → nema mentora.",
    hero_en: "Internship with stipend → fee → no mentor.",
    meta_sr: "Lažni internship: uplata za materijale, lažna firma. Provera kompanije i fakulteta.",
    meta_en: "Fake internship: materials fee, fake firm. Verify company and faculty.",
    summary_sr: "Studentu se nudi praksa uz stipendiju ali prvo traže uplatu za softver, uniformu ili sertifikat. Mentorski kontakt ne postoji. Signal: stipendija koja zahteva uplatu pre prvog dana u kancelariji.",
    summary_en: "A student is offered an internship with a stipend but payment is first requested for software, uniform, or certificate. No mentor contact exists. Signal: a stipend that requires payment before day one in the office.",
    subtitle_sr: "Karijerni početak kao izgovor za unaprednu uplatu.",
    subtitle_en: "Career start as a pretext for upfront payment.",
    i1sr: "Poruka sa LinkedIn-a nudi remote praksu uz 500 EUR mesečno ali traži 80 EUR za „onboarding softver“.",
    i1en: "A LinkedIn message offers remote internship with €500/month but asks €80 for onboarding software.",
    i2sr: "Prave prakse fakulteta idu kroz karijerni centar ili potpisan ugovor bez takse kandidatu.",
    i2en: "Real faculty internships go through a career centre or a signed contract without a candidate fee.",
    model_sr: "ponuda prakse → mala uplata → nema mentora.",
    model_en: "internship offer → small payment → no mentor.",
    model_body: "ponuda prakse → mala uplata → nema mentora.",
    gsr: "Koristi se želja za CV iskustvom. Student plaća pre nego što vidi kancelariju.",
    gen: "It exploits the wish for CV experience. The student pays before seeing an office.",
    left: [
      L("Obećanje remote prakse bez intervjua uživo.", "Remote internship promise without an in-person interview."),
      L("Lažni potpis mentora na imejlu.", "A fake mentor signature on email."),
      L("Zahtev za studentski indeks kao dokaz.", "Student ID requested as proof."),
      L("Garancija preporuke pisma posle mesec dana.", "A guarantee of a recommendation letter after a month.")
    ],
    right: [
      L("Kompanija nema lokaciju koju možeš posetiti ili je adresa stambena zgrada.", "The company has no visitable location or the address is a residential building."),
      L("Fakultet nema sporazum sa tom firmom.", "The faculty has no agreement with that firm."),
      L("Mentor ne postoji na LinkedIn-u ili ima prazan profil.", "The mentor does not exist on LinkedIn or has an empty profile."),
      L("Stipendija se isplaćuje tek posle više uplata „za porez“.", "The stipend pays only after more payments for tax.")
    ],
    p3sr: "Traži se uplata za „projekat“ koji navodno finansira EU ili fond, bez javnog poziva.",
    p3en: "Payment is requested for a project allegedly funded by the EU or a fund, with no public call.",
    r10sr: "Stipendija za praksu traži novac od studenta pre prvog radnog dana.",
    r10en: "An internship stipend asks the student for money before the first workday.",
    stepMidSr: "Pitaj karijerni centar fakulteta da li je firma u partnerskoj listi.",
    stepMidEn: "Ask the faculty career centre whether the firm is on the partner list.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "studenti"]
  }
];
