const L = (sr, en) => ({ sr, en });
const ST = [
  "Proveri poslodavca na zvaničnom sajtu i pozovi broj sa liste kontakata, ne iz poruke.",
  "Verify the employer on the official site and call the number from the contact list, not from the message."
];
const HS = "Kandidat žuri zbog prilike. Zajednička provera kroz zvanični careers sajt ili javni telefon kompanije smanjuje otpor.";
const HE = "The candidate rushes because of the opportunity. Checking together via the official careers site or company public phone lowers resistance.";

module.exports = [
  {
    slug: "remote-payroll-setup-scam",
    title_sr: "Lažno podešavanje udaljene plate ili payroll naloga",
    title_en: "Remote payroll setup scam",
    hero_sr: "HR traži podatke za payroll → lažna forma → krađa naloga.",
    hero_en: "HR asks for payroll details → fake form → account theft.",
    meta_sr: "Lažni payroll onboarding: bankovni podaci, PIB, lažni portal. Provera HR kanala.",
    meta_en: "Fake payroll onboarding: bank details, tax ID, fake portal. Verify HR channel.",
    summary_sr: "Novo zaposleni ili saradnik dobija poruku da unese bankovne i lične podatke na linku radi udaljenog payroll-a. Forma je lažna ili vodi u fišing. Signal: link nije na domenu kompanije ili SSO-u.",
    summary_en: "A new hire or contractor gets a message to enter bank and personal data on a link for remote payroll. The form is fake or leads to phishing. Signal: the link is not on the company domain or SSO.",
    subtitle_sr: "Isplata plate kao izgovor za osetljive podatke.",
    subtitle_en: "Payroll as a pretext for sensitive data.",
    i1sr: "Poruka glumi HR ili finansije i traži hitan unos TR, broja računa i kopije lične karte na eksternom portalu.",
    i1en: "A message pretends to be HR or finance and asks for urgent entry of tax ID, account number, and ID copy on an external portal.",
    i2sr: "Pravi onboarding koristi isti sistem koji ti je poslodavac već dao ili potpisani papir u kancelariji.",
    i2en: "Real onboarding uses the system the employer already gave you or signed paper in the office.",
    model_sr: "poruka → lažni payroll portal → krađa podataka ili novca.",
    model_en: "message → fake payroll portal → data or money theft.",
    model_body: "poruka → lažni payroll portal → krađa podataka ili novca.",
    gsr: "Koristi se početak saradnje kada žrtva još ne poznaje procese. Podaci idu pre prvog radnog dana.",
    gen: "It exploits the start of work when the victim does not know the processes yet. Data goes before the first workday.",
    left: [
      L("Čestitke na zaposlenju i link „da bi isplata krenula na vreme“.", "Congratulations on hiring and a link so pay starts on time."),
      L("Lažni PDF sa tabelom zarada.", "A fake PDF with a salary table."),
      L("Zahtev za selfie sa dokumentom „radi KYC“.", "A selfie with documents requested for KYC."),
      L("Rok do kraja dana.", "End-of-day deadline.")
    ],
    right: [
      L("Domen linka nije poslovni domen firme.", "The link domain is not the firm's business domain."),
      L("Traži se lozinka mejla ili MFA kod na toj stranici.", "Email password or MFA code is requested on that page."),
      L("Nema potpisanog ugovora koji si video uživo ili elektronski od istog HR-a.", "No contract you saw live or electronically from the same HR."),
      L("Isti tekst poruke vide i drugi bez veze sa istom firmom.", "Others with no link to the same firm received the same message text.")
    ],
    p3sr: "Traži se mali „test depozit“ da bi se verifikovao račun ili naknada za aktivaciju payroll sistema.",
    p3en: "A small test deposit is requested to verify the account or a fee to activate the payroll system.",
    r10sr: "Payroll podešavanje traži osetljive podatke na sajtu koji nije intranet ili zvanični HR domen.",
    r10en: "Payroll setup asks for sensitive data on a site that is not the intranet or official HR domain.",
    stepMidSr: ST[0],
    stepMidEn: ST[1],
    hisr: HS,
    hien: HE,
    tags: ["posao", "fišing"]
  },
  {
    slug: "freelancer-milestone-release-scam",
    title_sr: "Lažno oslobađanje milston-a na freelancing platformi",
    title_en: "Freelancer milestone release scam",
    hero_sr: "Lažni klijent van platforme → escrow prevare → nema isplate.",
    hero_en: "Off-platform fake client → escrow tricks → no payout.",
    meta_sr: "Lažni milston: uplata klijenta, naknada, lažni skrinšot. Drži se platforme.",
    meta_en: "Fake milestone: client payment, fee, fake screenshot. Stay on platform.",
    summary_sr: "Klijent predlaže rad van platforme ili traži naknadu da bi se „oslobodio“ milston pre nego što platforma isplati. Eskalacija koristi lažne potvrde uplate. Signal: novac i komunikacija van zaštićenog toka platforme.",
    summary_en: "A client proposes work off-platform or asks for a fee to release a milestone before platform payout. Escalation uses fake payment proof. Signal: money and chat outside the platform's protected flow.",
    subtitle_sr: "Milston kao tačka gde se izvlači novac van escrow-a.",
    subtitle_en: "The milestone as the point where money is pulled outside escrow.",
    i1sr: "Nakon kratkog četa klijent šalje lažan skrinšot uplate i traži da pošalješ depozit ili da skineš zaštitu milston-a.",
    i1en: "After short chat the client sends a fake payment screenshot and asks you to send a deposit or remove milestone protection.",
    i2sr: "Prava isplata ide kroz mehanizam platforme; klijent ne treba da traži dodatne transfere za oslobađanje.",
    i2en: "Real payout goes through the platform mechanism; the client should not ask for extra transfers to release funds.",
    model_sr: "kontakt → rad → lažna potvrda → prag uplate → nema novca.",
    model_en: "contact → work → fake proof → payment threshold → no money.",
    model_body: "kontakt → rad → lažna potvrda → prag uplate → nema novca.",
    gsr: "Koristi se želja da se brzo zatvori posao. Freelancer rizikuje reputaciju i novac.",
    gen: "It exploits the wish to close work quickly. The freelancer risks reputation and money.",
    left: [
      L("Ponuda brzog velikog projekta sa slabim briefom.", "A fast large project offer with a weak brief."),
      L("Molba da pređete na WhatsApp „radi brzine“.", "A request to move to WhatsApp for speed."),
      L("Lažni PDF ugovor sa pečatom.", "A fake stamped contract PDF."),
      L("Obećanje bona ili dodatnih projekata.", "A promise of a bonus or more projects.")
    ],
    right: [
      L("Zahtev da se milston odobri pre nego što platforma pokaže sredstva.", "A request to approve a milestone before the platform shows funds."),
      L("Klijent traži refund preko vanjskog naloga.", "The client asks for a refund via an external account."),
      L("Nepostojeći ID transakcije na skrinšotu.", "No real transaction ID on the screenshot."),
      L("Pritisak da prihvatiš „hitnu“ isplatu van platforme.", "Pressure to accept urgent payout off-platform.")
    ],
    p3sr: "Traži se administrativna naknada, porez ili osiguranje da bi platforma navodno pustila milston.",
    p3en: "An admin fee, tax, or insurance is requested so the platform allegedly releases the milestone.",
    r10sr: "Oslobađanje milston-a uslovljeno je uplatom van zaštite platforme.",
    r10en: "Milestone release is conditioned on payment outside platform protection.",
    stepMidSr: "Proveri stanje milston-a samo u zvaničnoj aplikaciji platforme, ne u skrinšotu.",
    stepMidEn: "Check milestone status only in the platform's official app, not in a screenshot.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "freelancing"]
  },
  {
    slug: "fake-recruiter-calendar-link",
    title_sr: "Lažni kalendar link od regrutera",
    title_en: "Fake recruiter calendar link scam",
    hero_sr: "Poziv na intervju → lažni kalendar → krađa naloga.",
    hero_en: "Interview invite → fake calendar → account theft.",
    meta_sr: "Lažni Calendly/Teams link: fišing, OAuth, malware. Provera domena.",
    meta_en: "Fake Calendly/Teams link: phishing, OAuth, malware. Verify domain.",
    summary_sr: "Regruter šalje link za zakazivanje intervjua koji vodi na kopiju poznatog servisa ili traži prijavu mejla. Cilj je token, lozinka ili preuzimanje fajla. Signal: domen linka nije zvaničan.",
    summary_en: "A recruiter sends a scheduling link that clones a known service or asks for email login. The goal is a token, password, or file download. Signal: the link domain is not official.",
    subtitle_sr: "Intervju kao pokriće za lažnu prijavu.",
    subtitle_en: "Interview as cover for a fake login.",
    i1sr: "Dobijaš profesionalnu poruku sa pozivom na video intervju i kratkim rokom; link otvara formu koja traži nalog.",
    i1en: "You get a professional message with a video interview invite and a tight deadline; the link opens a form that asks for an account.",
    i2sr: "Pravi regruteri koriste domene kompanije ili poznate alate sa URL-om koji se poklapa sa brendom.",
    i2en: "Real recruiters use company domains or known tools with URLs that match the brand.",
    model_sr: "poziv → lažni kalendar → prijava → kompromitacija.",
    model_en: "invite → fake calendar → login → compromise.",
    model_body: "poziv → lažni kalendar → prijava → kompromitacija.",
    gsr: "Koristi se žurba da se zakaže termin. Žrtva prijavljuje nalog pre provere URL-a.",
    gen: "It exploits rush to book a slot. The victim logs in before checking the URL.",
    left: [
      L("Ime kompanije i logo u poruci.", "Company name and logo in the message."),
      L("Tekst na engleskom koji deluje kao šablon.", "English text that looks like a template."),
      L("Rok „samo danas“ za slot.", "A today-only slot deadline."),
      L("Zahtev da instaliraš mali „meeting“ dodatak.", "A request to install a small meeting add-in.")
    ],
    right: [
      L("Host u linku nije calendar.google.com, outlook.com ili domen firme.", "The link host is not calendar.google.com, outlook.com, or the firm domain."),
      L("Traži se lozinka mejla na stranici trećeg lica.", "Email password is requested on a third-party page."),
      L("OAuth ekran traži čitanje pošte i kontakata.", "The OAuth screen asks to read mail and contacts."),
      L("Preuzimanje .exe ili .dmg pre sastanka.", "Download of .exe or .dmg before the meeting.")
    ],
    p3sr: "Nakon klika traže se prijava, SMS kod ili instalacija agenta „radi boljeg zvuka“.",
    p3en: "After the click, login, SMS code, or an agent install is requested for better audio.",
    r10sr: "Kalendar link za intervju vodi na domen koji ne pripada firmi ni poznatom alatu.",
    r10en: "The interview calendar link leads to a domain that belongs neither to the firm nor a known tool.",
    stepMidSr: "Uporedi URL sa zvaničnim careers stranicama i ne unosuj lozinku na kopiji.",
    stepMidEn: "Compare the URL with official careers pages and do not enter your password on a clone.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "fišing"]
  },
  {
    slug: "employment-contract-processing-fee",
    title_sr: "Naknada za „obradu ugovora o radu“",
    title_en: "Employment contract processing fee scam",
    hero_sr: "Ponuda posla → taksa za ugovor → nema angažmana.",
    hero_en: "Job offer → contract fee → no employment.",
    meta_sr: "Lažna naknada za potpis ugovora ili pečat. Pravi poslodavac ne naplaćuje to unapred.",
    meta_en: "Fake fee for signing or stamping a contract. Real employers do not charge this upfront.",
    summary_sr: "Nakon „prijema“ traže se administrativna naknada za štampu, notara ili registraciju ugovora pre prvog dana. Eskalacija dodaje nove stavke. Signal: novac pre prvog radnog dana i pre provere HR kontakta.",
    summary_en: "After acceptance, an admin fee is requested for printing, notary, or contract registration before day one. Escalation adds items. Signal: money before the first workday and HR contact check.",
    subtitle_sr: "Papirologija kao izgovor za unaprednu uplatu.",
    subtitle_en: "Paperwork as a pretext for upfront payment.",
    i1sr: "Šalju se lažni PDF ugovori sa tvojim imenom i odmah sledi uplata za „obradu i arhiviranje“.",
    i1en: "Fake PDF contracts with your name arrive and payment for processing and archiving follows immediately.",
    i2sr: "Pravi poslodavac ne traži od zaposlenog da plaća notara ili registraciju ugovora pre početka.",
    i2en: "A real employer does not ask the employee to pay notary or contract registration before start.",
    model_sr: "ponuda → lažni ugovor → naknada → nema posla.",
    model_en: "offer → fake contract → fee → no job.",
    model_body: "ponuda → lažni ugovor → naknada → nema posla.",
    gsr: "Koristi se olakšanje što si „primljen“. Novac ide pre nego što postoji radno mesto.",
    gen: "It exploits relief at being hired. Money moves before a workplace exists.",
    left: [
      L("Profesionalan izgled ugovora sa brojevima strana.", "A professional-looking multi-page contract."),
      L("Hitnost da se uplati pre isteka dana.", "Urgency to pay before the day ends."),
      L("Lažni pečat ili potpis na skeniranom PDF-u.", "A fake stamp or signature on a scanned PDF."),
      L("Obećanje da će se platiti prvog meseca nazad.", "A promise it will be refunded in the first month.")
    ],
    right: [
      L("Primalac uplate nije pravno lice poslodavca.", "The payee is not the employer legal entity."),
      L("Nema JIB/PIB i adrese koja se poklapa sa javnim registrom.", "No tax ID and address matching a public registry."),
      L("Isti tekst ugovora se pojavljuje na forumima kao primer prevare.", "The same contract text appears on forums as a scam example."),
      L("Odbijaju da potpišu pre nego što uplatiš.", "They refuse to sign before you pay.")
    ],
    p3sr: "Traže se troškovi za „HR registraciju“, osiguranje ili uniformu u istom koraku sa „obradom ugovora“.",
    p3en: "HR registration, insurance, or uniform costs are requested in the same step as contract processing.",
    r10sr: "Naknada za obradu ugovora o radu traži se pre prvog dana i pre provere poslodavca.",
    r10en: "An employment contract processing fee is requested before day one and employer verification.",
    stepMidSr: ST[0],
    stepMidEn: ST[1],
    hisr: HS,
    hien: HE
  },
  {
    slug: "visa-sponsorship-employment-scam",
    title_sr: "Lažno sponzorstvo vize za zaposlenje",
    title_en: "Visa sponsorship employment scam",
    hero_sr: "Sponzorstvo obećano → serija taksi → nema vize.",
    hero_en: "Sponsorship promised → fee series → no visa.",
    meta_sr: "Lažni sponzor posla: Certificate of Sponsorship taksa, lažni dokumenti. Provera Home Office / ambasade.",
    meta_en: "Fake job sponsorship: CoS fee, fake documents. Verify embassy or government source.",
    summary_sr: "Nude se poslodavac koji će sponzorisati vizu uz plaćanje serije administrativnih koraka. Dokumenti ne prolaze proveru ili ne postoje. Signal: novac pre zvaničnog potvrđivanja sponzora kroz državni kanal.",
    summary_en: "An employer offers visa sponsorship with a series of paid admin steps. Documents fail checks or do not exist. Signal: money before official sponsor confirmation through a government channel.",
    subtitle_sr: "Sponzor kao reč koja otvara neograničene takse.",
    subtitle_en: "Sponsorship as a word that opens endless fees.",
    i1sr: "Agencija tvrdi da ima poslodavca koji daje sponzorstvo i traži depozit za rezervaciju CoS-a ili ekvivalenta.",
    i1en: "An agency claims an employer provides sponsorship and asks a deposit to reserve a CoS or equivalent.",
    i2sr: "Pravo sponzorstvo se proverava kroz zvanični imigracioni portal ili ambasadu, ne kroz lični račun agencije.",
    i2en: "Real sponsorship is verified through an official immigration portal or embassy, not an agency personal account.",
    model_sr: "obećanje → takse → lažni papiri → nema odobrenja.",
    model_en: "promise → fees → fake papers → no approval.",
    model_body: "obećanje → takse → lažni papiri → nema odobrenja.",
    gsr: "Koristi se složenost imigracije. Žrtva plaća korake koje ne može sama proveriti bez strpljenja.",
    gen: "It exploits immigration complexity. The victim pays steps they cannot verify without patience.",
    left: [
      L("Visoka plata i smeštaj uključeni u paket.", "High pay and housing included in the package."),
      L("Lažni brojevi referenci na „sistem“ države.", "Fake reference numbers on a government system."),
      L("WhatsApp komunikacija sa „case officer“.", "WhatsApp communication with a case officer."),
      L("Lista dokumenata koja izgleda zvanično.", "A document list that looks official.")
    ],
    right: [
      L("Nema provere broja sponzora u javnom registru gde postoji.", "No sponsor number check in a public registry where one exists."),
      L("Plaćanje ide na agenciju umesto na državnu taksa koja ima javan pravilnik.", "Payment goes to an agency instead of a government fee with a public schedule."),
      L("Odbijanje da pokažu potpisani job offer koji možeš verifikovati HR brojem.", "Refusal to show a signed job offer you can verify with an HR number."),
      L("Pretnja da gubiš sponzorstvo ako ne platiš danas.", "Threat that you lose sponsorship if you do not pay today.")
    ],
    p3sr: "Traži se hitna uplata za CoS, medicinu, osiguranje ili „fast track“ bez potvrde u portalu.",
    p3en: "Urgent payment is requested for CoS, medical, insurance, or fast track without portal confirmation.",
    r10sr: "Sponzorstvo se prodaje uz uplate pre zvaničnog odobrenja kroz imigracioni sistem.",
    r10en: "Sponsorship is sold with payments before approval through the immigration system.",
    stepMidSr: "Kontaktiraj ambasadu ili imigracioni sajt države cilja i pitaj da li postoji evidencija sponzora.",
    stepMidEn: "Contact the embassy or destination immigration site and ask whether sponsor records exist.",
    hisr: HS,
    hien: HE
  },
  {
    slug: "seasonal-work-placement-scam",
    title_sr: "Prevara sa sezonskim radom i agencijom",
    title_en: "Seasonal work placement scam",
    hero_sr: "Sezonski posao → agencijska naknada → nema smeštaja ni posla.",
    hero_en: "Seasonal job → agency fee → no housing or job.",
    meta_sr: "Lažna sezonska regrutacija: taksa, lažni ugovor. Provera poslodavca i lokacije.",
    meta_en: "Fake seasonal recruitment: fee, fake contract. Verify employer and location.",
    summary_sr: "Nude se berba, skijalište ili hotel sezoni uz uplatu za agenciju, prevoz ili depozit za smeštaj. Na licu mesta nema posla. Signal: uplata pre provere da lokacija i poslodavac postoje.",
    summary_en: "Harvest, ski resort, or hotel season work is offered with payment for agency, transport, or housing deposit. There is no job on site. Signal: payment before verifying location and employer exist.",
    subtitle_sr: "Sezona kao žurba koja skida proveru.",
    subtitle_en: "Season timing as rush that skips verification.",
    i1sr: "Oglas obećava brzu zaradu u inostranstvu uz mali depozit za rezervaciju mesta u kampu ili apartmanu.",
    i1en: "An ad promises quick pay abroad with a small deposit to reserve a camp or apartment spot.",
    i2sr: "Prave sezonske ponude imaju jasnog poslodavca i adresu koja se može potvrditi telefonom.",
    i2en: "Real seasonal offers have a clear employer and address you can confirm by phone.",
    model_sr: "oglas → depozit → put → nema poslodavca.",
    model_en: "ad → deposit → travel → no employer.",
    model_body: "oglas → depozit → put → nema poslodavca.",
    gsr: "Koristi se kratko trajanje sezone i gužva oko mesta. Žrtva plaća pre nego što vidi objekat.",
    gen: "It exploits short seasons and spot scarcity. The victim pays before seeing the site.",
    left: [
      L("Fotografije smeštaja preuzete sa interneta.", "Housing photos taken from the web."),
      L("Cena koja je bolja od tržišta za istu sezonu.", "A price better than the market for the same season."),
      L("Grupni polazak autobusom sa nepoznatim organizatorom.", "Group bus departure with an unknown organizer."),
      L("Lažni potpisi „partnera“ na flajeru.", "Fake partner signatures on a flyer.")
    ],
    right: [
      L("Adresa poslodavca ne postoji na mapi ili je drugačija u pozivu.", "The employer address does not exist on the map or differs in the invite."),
      L("Niko na recepciji hotela ne zna za agenciju.", "Nobody at the hotel reception knows the agency."),
      L("Uplata ide na lično ime bez PIB-a.", "Payment goes to a personal name without a tax ID."),
      L("Zabrana direktnog kontakta sa „šefom terena“ pre uplate.", "Ban on direct contact with the site manager before payment.")
    ],
    p3sr: "Traži se dodatna taksa za radnu dozvolu, uniformu ili „lokalnu registraciju“ pre polaska.",
    p3en: "An extra fee is requested for a work permit, uniform, or local registration before departure.",
    r10sr: "Sezonski posao traži novac pre nego što potvrdiš da poslodavac postoji na adresi.",
    r10en: "Seasonal work asks for money before you confirm the employer exists at the address.",
    stepMidSr: "Pozovi hotel ili farmu direktno i pitaj da li angažuju preko te agencije.",
    stepMidEn: "Call the hotel or farm directly and ask whether they hire through that agency.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "sezona"]
  },
  {
    slug: "au-pair-placement-scam",
    title_sr: "Prevara sa au pair smeštavanjem",
    title_en: "Au pair placement scam",
    hero_sr: "Porodica ili agencija → naknada → nema viznog programa.",
    hero_en: "Family or agency → fee → no real program.",
    meta_sr: "Lažni au pair: agencijska taksa, lažna porodica. Provera programa i vize.",
    meta_en: "Fake au pair: agency fee, fake family. Verify program and visa.",
    summary_sr: "Nude se porodica u inostranstvu ili agencija koja traži uplatu za matching, vizu ili osiguranje pre susreta. Porodica ne postoji ili odbija video poziv. Signal: novac pre zvaničnog programa i pre video razgovora.",
    summary_en: "A host family abroad or an agency asks payment for matching, visa, or insurance before meeting. The family does not exist or refuses video. Signal: money before an official program and before a video call.",
    subtitle_sr: "Briga o deci kao emotivni mamac.",
    subtitle_en: "Childcare as emotional bait.",
    i1sr: "Profil porodice deluje savršeno, a agencija traži depozit da bi zakazala intervju ili pripremila dokumenta.",
    i1en: "The family profile looks perfect and the agency asks a deposit to schedule an interview or prepare documents.",
    i2sr: "Pravi programi imaju jasne korake, ugovor i često besplatan prvi kontakt sa porodicom.",
    i2en: "Real programs have clear steps, a contract, and often a free first contact with the family.",
    model_sr: "profil → depozit → lažni papiri → nema odlaska.",
    model_en: "profile → deposit → fake papers → no travel.",
    model_body: "profil → depozit → lažni papiri → nema odlaska.",
    gsr: "Koristi se želja za jeftinim putovanjem i učenjem jezika. Emocija prelazi proveru.",
    gen: "It exploits the wish for cheap travel and language learning. Emotion skips verification.",
    left: [
      L("Slike dece i kuće koje izgledaju kao stock.", "Child and house photos that look like stock images."),
      L("Porodica „žuri“ jer im treba pomoć od ponedeljka.", "The family rushes because help is needed from Monday."),
      L("Minimalan intervju preko četa bez videa.", "Minimal chat interview without video."),
      L("Obećanje da će oni pokriti avio posle uplate.", "A promise they will cover the flight after you pay.")
    ],
    right: [
      L("Odbijanje video poziva sa porodicom u istoj sobi.", "Refusal of a video call with the family in the same room."),
      L("Adresa porodice ne postoji ili je hotel.", "The family address does not exist or is a hotel."),
      L("Agencija nema registarski broj koji proveravaš u registru privrednih subjekata.", "The agency has no registry number you can verify."),
      L("Zahtev za novac pre potpisanog ugovora programa.", "Money requested before a signed program contract.")
    ],
    p3sr: "Traži se naknada za vizu, osiguranje ili „anti-abuse“ depozit koji navodno vraćaju prvog meseca.",
    p3en: "A fee is requested for visa, insurance, or an anti-abuse deposit allegedly refunded in month one.",
    r10sr: "Au pair ugovor traži uplatu pre nego što si video porodicu uživo na kameri.",
    r10en: "The au pair contract asks for payment before you saw the family live on camera.",
    stepMidSr: "Zatraži video turu kuće i razgovor sa oba roditelja odvojeno od agencije.",
    stepMidEn: "Ask for a video house tour and talk to both parents separately from the agency.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "porodica"]
  },
  {
    slug: "cruise-ship-job-scam",
    title_sr: "Prevara sa poslom na krstarenju",
    title_en: "Cruise ship job scam",
    hero_sr: "Posada na brodu → takse i dokumenta → nema ukrcaja.",
    hero_en: "Crew job → fees and documents → no embarkation.",
    meta_sr: "Lažni cruise posao: agencija, medicina, uniforma. Provera broda i kompanije.",
    meta_en: "Fake cruise job: agency, medical, uniform. Verify ship and company.",
    summary_sr: "Nude se poslovi konobara, kuvara ili animacije uz seriju uplata za agenciju, STCW ili uniformu. Boarding pass ne stiže. Signal: novac pre zvaničnog angažmana kompanije koja upravlja brodom.",
    summary_en: "Waiter, cook, or entertainment jobs are offered with a series of payments for agency, STCW, or uniform. No boarding pass arrives. Signal: money before official employment by the ship management company.",
    subtitle_sr: "More i putovanje kao san koji traži unapredne takse.",
    subtitle_en: "Sea and travel as a dream that demands upfront fees.",
    i1sr: "Lažni regruter tvrdi da ima ekskluzivni ugovor sa kompanijom broda i traži depozit za mesto u smena sistemu.",
    i1en: "A fake recruiter claims an exclusive contract with the ship company and asks a deposit for a roster spot.",
    i2sr: "Pravo zapošljavanje na brodu ide kroz poznate cruise brendove ili ovlašćene agencije sa javnim kontaktima.",
    i2en: "Real ship employment goes through known cruise brands or authorized agencies with public contacts.",
    model_sr: "ponuda → takse → lažni papiri → nema ukrcaja.",
    model_en: "offer → fees → fake papers → no embarkation.",
    model_body: "ponuda → takse → lažni papiri → nema ukrcaja.",
    gsr: "Koristi se želja za putovanjem i međunarodnom zaradom. Žrtva ne proverava brodsku kompaniju.",
    gen: "It exploits the wish to travel and earn internationally. The victim skips verifying the cruise line.",
    left: [
      L("Oglas na društvenoj mreži sa fotografijama luksuznog broda.", "A social ad with luxury ship photos."),
      L("Brz intervju i odmah lista uplata.", "Fast interview and an immediate payment list."),
      L("Lažni sertifikati sa generičkim štampom.", "Fake certificates with generic stamps."),
      L("Obećanje visokog baksisa u gotovom.", "A promise of high cash tips.")
    ],
    right: [
      L("Kompanija na dokumentu nije ista kao zvanični brend broda.", "The company on the document is not the official ship brand."),
      L("Nema imena broda i datuma krstarenja koje možeš proveriti.", "No ship name and sailing date you can verify."),
      L("Uplata ide na agenciju bez adrese kancelarije.", "Payment goes to an agency without an office address."),
      L("Zabrana kontaktiranja luke ili broda direktno.", "Ban on contacting the port or ship directly.")
    ],
    p3sr: "Traži se uplata za STCW kurs, medicinski pregled u određenoj klinici ili uniformu pre službenog offer letter-a.",
    p3en: "Payment is requested for STCW, a medical at a specific clinic, or uniform before an official offer letter.",
    r10sr: "Posao na brodu traži novac pre zvaničnog angažmana kompanije koja vodi posadu.",
    r10en: "A ship job asks for money before official employment by the crewing company.",
    stepMidSr: "Pozovi zvanični careers brodarske kompanije i pitaj da li imaju tog regrutera.",
    stepMidEn: "Call the cruise line's official careers line and ask whether that recruiter exists.",
    hisr: HS,
    hien: HE,
    tags: ["posao", "turizam"]
  }
];
</think>


<｜tool▁calls▁begin｜><｜tool▁call▁begin｜>
Read