window.SCAM_CONTENT = window.SCAM_CONTENT || {};

window.SCAM_CONTENT["street-gold-ring-scam"] = {
  raw_html: `
    <section class="card">
      <h2 data-sr="Uvod: ulična prevara sa prstenom" data-en="Introduction: street ring scam">Uvod: ulična prevara sa prstenom</h2>
      <p data-sr="Na ulici neko nalazi prsten ili nudi nakit po ceni koja deluje povoljno; predmet je često imitacija bez tržišne vrednosti." data-en="On the street someone finds a ring or offers jewellery at a price that seems good; the item is often imitation with no market value.">Na ulici neko nalazi prsten ili nudi nakit po ceni koja deluje povoljno; predmet je često imitacija bez tržišne vrednosti.</p>
      <div class="callout" data-sr="<strong>Model:</strong> nalaz ili prodaja → pohlepa → gotovina → gubitak" data-en="<strong>Model:</strong> find or sale → greed → cash → loss"><strong>Model:</strong> nalaz ili prodaja → pohlepa → gotovina → gubitak</div>
    </section>
    <section class="card">
      <h2 data-sr="Hronološki tok (faze + grananja)" data-en="Timeline (phases + branching)">Hronološki tok (faze + grananja)</h2>
      
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 1 — Pristup na ulici" data-en="Phase 1 — Street approach">Faza 1 — Pristup na ulici</h3>
        <p data-sr="Stranac pokazuje prsten ili lanac i pita da li je tvoj ili nudi prodaju uz priču o hitnom novcu." data-en="A stranger shows a ring or chain and asks if it is yours or offers a sale with a need for quick cash.">Stranac pokazuje prsten ili lanac i pita da li je tvoj ili nudi prodaju uz priču o hitnom novcu.</p>
        <ul class="bullets"><li data-sr="Scena deluje spontano ali uključuje pritisak na brzu odluku." data-en="The scene looks spontaneous but pressures a fast decision.">Scena deluje spontano ali uključuje pritisak na brzu odluku.</li><li data-sr="Tvrdi se da je predmet zlato ili da ima gravuru vrednosti." data-en="They claim gold or a valuable hallmark.">Tvrdi se da je predmet zlato ili da ima gravuru vrednosti.</li><li data-sr="Cena je daleko ispod onoga što bi koštala provera." data-en="The price is far below what verification would cost.">Cena je daleko ispod onoga što bi koštala provera.</li><li data-sr="Može postojati svjedok koji potvrđuje priču." data-en="A witness may confirm the story.">Može postojati svjedok koji potvrđuje priču.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta zaustavlja hod i sluša ponudu." data-en="<strong>Phase threshold:</strong> The target stops walking and listens to the offer."><strong>Prag faze:</strong> Meta zaustavlja hod i sluša ponudu.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="pigeon-drop-scam.html" data-sr="Pigeon drop" data-en="Pigeon drop scam">Pigeon drop</a></li><li><a href="distraction-theft-scam.html" data-sr="Distrakcija na ulici" data-en="Distraction theft">Distrakcija na ulici</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 2 — Priča o vrednosti" data-en="Phase 2 — Value story">Faza 2 — Priča o vrednosti</h3>
        <p data-sr="Objašnjavaju da ne mogu da čekaju zlatara ili da je nakit nasledstvo koje moraju brzo da prodaju." data-en="They explain they cannot wait for a jeweller or the jewellery is inheritance they must sell fast.">Objašnjavaju da ne mogu da čekaju zlatara ili da je nakit nasledstvo koje moraju brzo da prodaju.</p>
        <ul class="bullets"><li data-sr="Izbegavaju neutralnu radnju koju ti biraš." data-en="They avoid a neutral shop you choose.">Izbegavaju neutralnu radnju koju ti biraš.</li><li data-sr="Pokazuju lažnu procenu ili uplatnicu." data-en="They show a fake appraisal or receipt.">Pokazuju lažnu procenu ili uplatnicu.</li><li data-sr="Kombinuju religijske ili porodične motive da izazovu saosećanje." data-en="They mix religious or family motives for sympathy.">Kombinuju religijske ili porodične motive da izazovu saosećanje.</li><li data-sr="Nude popust ako platiš odmah." data-en="They offer a discount if you pay now.">Nude popust ako platiš odmah.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta veruje da predmet ima značajnu vrednost." data-en="<strong>Phase threshold:</strong> The target believes the item has significant value."><strong>Prag faze:</strong> Meta veruje da predmet ima značajnu vrednost.</div>
        
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 3 — Plaćanje gotovine" data-en="Phase 3 — Cash payment">Faza 3 — Plaćanje gotovine</h3>
        <p data-sr="Traže gotovinu jer ne prihvataju karticu ili jer hitno trebaju novac." data-en="They want cash because they do not take cards or need money urgently.">Traže gotovinu jer ne prihvataju karticu ili jer hitno trebaju novac.</p>
        <ul class="bullets"><li data-sr="Vode te ka bankomatu pod izgovorom." data-en="They steer you to an ATM on a pretext.">Vode te ka bankomatu pod izgovorom.</li><li data-sr="Ne daju račun sa PIB-om." data-en="They give no receipt with a tax ID.">Ne daju račun sa PIB-om.</li><li data-sr="Brzo preuzimaju novac i daju predmet u omotu." data-en="They take cash quickly and hand the item in a wrapper.">Brzo preuzimaju novac i daju predmet u omotu.</li><li data-sr="Odbijaju da prate u radnju radi zajedničke provere." data-en="They refuse to follow you to a shop for joint verification.">Odbijaju da prate u radnju radi zajedničke provere.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Meta predaje gotovinu i preuzima predmet." data-en="<strong>Phase threshold:</strong> The target hands over cash and takes the item."><strong>Prag faze:</strong> Meta predaje gotovinu i preuzima predmet.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="marketplace-scam.html" data-sr="Oglasne prevare" data-en="Marketplace scams">Oglasne prevare</a></li></ul></div>
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 4 — Otkrivanje imitacije" data-en="Phase 4 — Discovering imitation">Faza 4 — Otkrivanje imitacije</h3>
        <p data-sr="Zlatara ili kućna vaga pokazuje da je metal bezvredan ili pozlaćen." data-en="A jeweller or home scale shows the metal is worthless or plated.">Zlatara ili kućna vaga pokazuje da je metal bezvredan ili pozlaćen.</p>
        <ul class="bullets"><li data-sr="Gravura je štampana ili ne odgovara standardima." data-en="The stamp is printed or not to standard.">Gravura je štampana ili ne odgovara standardima.</li><li data-sr="Kamen je staklo ili plastika." data-en="The stone is glass or plastic.">Kamen je staklo ili plastika.</li><li data-sr="Težina ne odgovara zlatu iste zapremine." data-en="Weight does not match gold of the same volume.">Težina ne odgovara zlatu iste zapremine.</li><li data-sr="Prodavac je nestao sa iste adrese." data-en="The seller has vanished from the meeting spot.">Prodavac je nestao sa iste adrese.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva shvata da je preplaćena." data-en="<strong>Phase threshold:</strong> The victim realises they overpaid."><strong>Prag faze:</strong> Žrtva shvata da je preplaćena.</div>
        
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 5 — Nestanak prodavca" data-en="Phase 5 — Seller disappearance">Faza 5 — Nestanak prodavca</h3>
        <p data-sr="Broj ne radi, lice se ne vraća na mesto susreta, nema adrese za reklamaciju." data-en="The number does not work, the person does not return, there is no address for complaints.">Broj ne radi, lice se ne vraća na mesto susreta, nema adrese za reklamaciju.</p>
        <ul class="bullets"><li data-sr="Isti obrazac se ponavlja drugog dana na drugoj lokaciji." data-en="The same pattern repeats another day elsewhere.">Isti obrazac se ponavlja drugog dana na drugoj lokaciji.</li><li data-sr="Žrtva često ne prijavljuje zbog stida." data-en="Victims often do not report out of shame.">Žrtva često ne prijavljuje zbog stida.</li><li data-sr="Video nadzor ponekad snima predaju novca." data-en="CCTV sometimes captures the handover.">Video nadzor ponekad snima predaju novca.</li><li data-sr="Može postojati povezana ekipa za džeparenje." data-en="A linked pickpocket crew may operate nearby.">Može postojati povezana ekipa za džeparenje.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva nema kontakt ni pravni subjekt za spor." data-en="<strong>Phase threshold:</strong> The victim has no contact or legal entity for dispute."><strong>Prag faze:</strong> Žrtva nema kontakt ni pravni subjekt za spor.</div>
        
      </article>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 6 — Prijava i edukacija" data-en="Phase 6 — Reporting and education">Faza 6 — Prijava i edukacija</h3>
        <p data-sr="Policija i lokalna upozorenja pomažu; edukacija starijih smanjuje ponavljanje." data-en="Police and local alerts help; elder education reduces repeat victimisation.">Policija i lokalna upozorenja pomažu; edukacija starijih smanjuje ponavljanje.</p>
        <ul class="bullets"><li data-sr="Prijavi sa opisom, jezikom i pravcem odlaska." data-en="Report with description, language, and direction.">Prijavi sa opisom, jezikom i pravcem odlaska.</li><li data-sr="Deli upozorenje u zajednici i na društvenim mrežama." data-en="Share warnings in community and social media.">Deli upozorenje u zajednici i na društvenim mrežama.</li><li data-sr="Pravilo: ne kupuj nakit na ulici bez nezavisne provere." data-en="Rule: do not buy street jewellery without independent verification.">Pravilo: ne kupuj nakit na ulici bez nezavisne provere.</li><li data-sr="Turističke informacije često imaju listu uličnih prevara." data-en="Tourist information often lists street scam types.">Turističke informacije često imaju listu uličnih prevara.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Žrtva prijavljuje i širi preventivnu poruku." data-en="<strong>Phase threshold:</strong> The victim reports and spreads a prevention message."><strong>Prag faze:</strong> Žrtva prijavljuje i širi preventivnu poruku.</div>
        
      </article>
    </section>
    <section class="card">
      <h2 data-sr="Crvene zastavice" data-en="Red flags">Crvene zastavice</h2>
      <ul class="bullets"><li data-sr="Stranac nudi zlato ili dijamant po sumnjivo niskoj ceni na ulici." data-en="A stranger offers gold or a diamond at a suspiciously low street price.">Stranac nudi zlato ili dijamant po sumnjivo niskoj ceni na ulici.</li><li data-sr="Predmet izgleda težak, ali je verovatno pozlaćeni mesing ili plastika." data-en="The item looks heavy but is likely plated brass or plastic.">Predmet izgleda težak, ali je verovatno pozlaćeni mesing ili plastika.</li><li data-sr="Priča uključuje slučajni nalaz i brzu prodaju pre nego što vlasnik sazna." data-en="The story includes a lucky find and a quick sale before the owner notices. ">Priča uključuje slučajni nalaz i brzu prodaju pre nego što vlasnik sazna.</li><li data-sr="Pritisak da platiš odmah gotovinom bez provere u zlatari." data-en="Pressure to pay cash immediately without a jeweller check.">Pritisak da platiš odmah gotovinom bez provere u zlatari.</li><li data-sr="Odbijaju da idu sa tobom u radnju radi provere." data-en="They refuse to go with you to a shop for verification.">Odbijaju da idu sa tobom u radnju radi provere.</li><li data-sr="Dva lica se slažu oko povoljne cene da bi delovalo legitimno." data-en="Two people agree on a good price to look legitimate.">Dva lica se slažu oko povoljne cene da bi delovalo legitimno.</li><li data-sr="Nakon uplate predmet u zlatari pokazuje da nema tržišnu vrednost." data-en="After payment a jeweller shows the item has no market value.">Nakon uplate predmet u zlatari pokazuje da nema tržišnu vrednost.</li><li data-sr="Kombinuju se sa distrakcijom dok neko drugi krade torbu." data-en="Combined with distraction while someone else steals a bag.">Kombinuju se sa distrakcijom dok neko drugi krade torbu.</li><li data-sr="Koriste lažnu gravuru ili pečat koji zvuči zvanično." data-en="They use fake hallmarks or stamps that sound official.">Koriste lažnu gravuru ili pečat koji zvuči zvanično.</li><li data-sr="Isti obrazac se ponavlja na turističkim mestima i stanicama." data-en="The same pattern repeats at tourist spots and stations.">Isti obrazac se ponavlja na turističkim mestima i stanicama.</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Provere: 8 brzih provera" data-en="Checks: 8 quick checks">Provere: 8 brzih provera</h2>
      <ul class="bullets"><li data-sr="Da li je cena ispod one za proveru autentičnosti u zlatari?" data-en="Is the price below what a jeweller would charge to verify authenticity?">Da li je cena ispod one za proveru autentičnosti u zlatari?</li><li data-sr="Da li prodavac odbija neutralnu radnju za test?" data-en="Does the seller refuse a neutral shop for testing?">Da li prodavac odbija neutralnu radnju za test?</li><li data-sr="Da li scenario uključuje slučajni nalaz i brzu prodaju?" data-en="Does the scenario include a lucky find and quick sale?">Da li scenario uključuje slučajni nalaz i brzu prodaju?</li><li data-sr="Da li traže gotovinu odmah bez računa?" data-en="Do they want cash immediately with no receipt?">Da li traže gotovinu odmah bez računa?</li><li data-sr="Da li bi pravi vlasnik zlata prodao ga na ulici ispod tržišne cene?" data-en="Would a real gold owner sell far below market on the street?">Da li bi pravi vlasnik zlata prodao ga na ulici ispod tržišne cene?</li><li data-sr="Da li osećaš pritisak da ne pričaš sa drugima o kupovini?" data-en="Do you feel pressured not to tell others about the purchase?">Da li osećaš pritisak da ne pričaš sa drugima o kupovini?</li><li data-sr="Da li su dva stranca saglasni previše brzo oko tvoje koristi?" data-en="Do two strangers agree too quickly about your benefit?">Da li su dva stranca saglasni previše brzo oko tvoje koristi?</li><li data-sr="Da li možeš jednostavno otiši bez kupovine?" data-en="Can you simply walk away without buying?">Da li možeš jednostavno otiši bez kupovine?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Checklista: 12 pitanja" data-en="Checklist: 12 questions">Checklista: 12 pitanja</h2>
      <ul class="bullets"><li data-sr="Da li sam nezavisno proverio identitet pre bilo kakve uplate?" data-en="Have I independently verified identity before any payment?">Da li sam nezavisno proverio identitet pre bilo kakve uplate?</li><li data-sr="Da li sam razgovarao sa nekim od poverenja?" data-en="Have I spoken to someone I trust?">Da li sam razgovarao sa nekim od poverenja?</li><li data-sr="Da li postoji pritisak za odluku istog dana?" data-en="Is there same-day decision pressure?">Da li postoji pritisak za odluku istog dana?</li><li data-sr="Da li je plaćanje traženo na način koji je teško otkazati?" data-en="Is payment requested in a hard-to-reverse way?">Da li je plaćanje traženo na način koji je teško otkazati?</li><li data-sr="Da li dokumenti imaju očigledne greške ili generičke šablone?" data-en="Do documents have obvious errors or generic templates?">Da li dokumenti imaju očigledne greške ili generičke šablone?</li><li data-sr="Da li mogu da sačekam 24 sata pre uplate?" data-en="Can I wait 24 hours before paying?">Da li mogu da sačekam 24 sata pre uplate?</li><li data-sr="Da li znam tačnu adresu i pravni subjekt primaoca?" data-en="Do I know the exact address and legal entity of the recipient?">Da li znam tačnu adresu i pravni subjekt primaoca?</li><li data-sr="Da li je cena daleko ispod tržišne bez razloga?" data-en="Is the price far below market with no explanation?">Da li je cena daleko ispod tržišne bez razloga?</li><li data-sr="Da li su svi učesnici stranci bez prethodnog konteksta?" data-en="Are all participants strangers with no prior context?">Da li su svi učesnici stranci bez prethodnog konteksta?</li><li data-sr="Da li osećam stid ili strah da pitam za pauzu?" data-en="Do I feel shame or fear to ask for a pause?">Da li osećam stid ili strah da pitam za pauzu?</li><li data-sr="Da li bih savetovao prijatelju da prihvati isti scenario?" data-en="Would I advise a friend to accept the same scenario?">Da li bih savetovao prijatelju da prihvati isti scenario?</li><li data-sr="Da li postoji alternativa preko zvaničnog portala ili poziva službi?" data-en="Is there an alternative via an official portal or service call?">Da li postoji alternativa preko zvaničnog portala ili poziva službi?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Ako sumnja krene: redosled poteza" data-en="If suspicion starts: order of steps">Ako sumnja krene: redosled poteza</h2>
      <ol class="steps">
        
        <li data-sr="Prekini interakciju i udalji se ka zatvorenom javnom mestu sa osobljem." data-en="End the interaction and move toward a staffed indoor public place.">Prekini interakciju i udalji se ka zatvorenom javnom mestu sa osobljem.</li>
        <li data-sr="Drži torbu i novčanik pred sobom i ne daj telefon strancu da pozove." data-en="Keep bag and wallet in front of you and do not give your phone to a stranger to call.">Drži torbu i novčanik pred sobom i ne daj telefon strancu da pozove.</li>
        <li data-sr="Ne izvlači novac na ulici i ne pokazuj sadržaj novčanika." data-en="Do not withdraw or display cash on the street.">Ne izvlači novac na ulici i ne pokazuj sadržaj novčanika.</li>
        <li data-sr="Ako sumnjaš, uđi u banku ili prodavnicu i zamoli da pozovu policiju." data-en="If unsure, enter a bank or shop and ask staff to call police.">Ako sumnjaš, uđi u banku ili prodavnicu i zamoli da pozovu policiju.</li>
        <li data-sr="Prijavi incident policiji sa opisom lica i pravca odlaska." data-en="Report the incident to police with a description and direction of travel.">Prijavi incident policiji sa opisom lica i pravca odlaska.</li>
      </ol>
    </section>
    <section class="card">
      <h2 data-sr="Ako pokušavaš da pomogneš nekome" data-en="If you are trying to help someone">Ako pokušavaš da pomogneš nekome</h2>
      <div class="grid-2">
        <div class="phase">
          <div class="label" data-sr="Pitanja koja pomažu" data-en="Helpful questions">Pitanja koja pomažu</div>
          <ul class="bullets">
            <li data-sr="Da li je osoba već platila ili pustila nekoga unutra?" data-en="Has the person already paid or let someone inside?">Da li je osoba već platila ili pustila nekoga unutra?</li>
            <li data-sr="Da li postoji pritisak da se odmah odluči bez konsultacije?" data-en="Is there pressure to decide immediately without consulting anyone?">Da li postoji pritisak da se odmah odluči bez konsultacije?</li>
            <li data-sr="Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?" data-en="Did they ask for cash, vouchers, or payment to a third-party account?">Da li su tražili gotovinu, vaučere ili uplatu na tuđi račun?</li>
            <li data-sr="Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?" data-en="Can identity be verified via an official number from the agency or company website?">Da li se identitet može proveriti preko zvaničnog broja sa sajta institucije ili firme?</li>
          </ul>
        </div>
        <div class="phase">
          <div class="label" data-sr="Rečenice koje rade" data-en="Phrases that work">Rečenice koje rade</div>
          <ul class="bullets">
            <li data-sr="Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno." data-en="Let us first close the door and call the official number together.">Hajde da prvo zatvorimo vrata i pozovemo zvanični broj zajedno.</li>
            <li data-sr="Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja." data-en="A real agency or firm allows a pause and written appointment confirmation.">Prava služba ili firma dozvoljava pauzu i pišan potvrdu zakazivanja.</li>
            <li data-sr="Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno." data-en="We pay nothing until identity and authority are verified independently.">Ne plaćamo ništa dok identitet i ovlašćenje nisu provereni nezavisno.</li>
            <li data-sr="Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja." data-en="If you feel street pressure, enter a shop or bank and ask staff for help.">Ako osećaš pritisak na ulici, uđi u prodavnicu ili banku i traži pomoć osoblja.</li>
          </ul>
        </div>
      </div>
    </section>
`
};
