window.SCAM_CONTENT = window.SCAM_CONTENT || {};

window.SCAM_CONTENT["tow-truck-scam"] = {
  raw_html: `
    <section class="card">
      <h2 data-sr="Uvod: lažni ili pretenciozni šlep" data-en="Introduction: bogus or predatory towing">Uvod: lažni ili pretenciozni šlep</h2>
      <p data-sr="Nakon kvara, udesa ili parkiranja, pojavi se šlep koji traži odmah gotovinu, skrivene takse ili prevoz do nepoznatog servisa. Cilj je da platiš pre dogovora ili da odustaneš od prava na pravu cenu." data-en="After a breakdown, crash, or parking issue, a tow appears demanding immediate cash, hidden fees, or transport to an unknown garage. The goal is payment before terms or surrender of fair pricing.">Nakon kvara, udesa ili parkiranja, pojavi se šlep koji traži odmah gotovinu, skrivene takse ili prevoz do nepoznatog servisa. Cilj je da platiš pre dogovora ili da odustaneš od prava na pravu cenu.</p>
      <div class="callout" data-sr="<strong>Model:</strong> kontakt → hitnost → vezivanje vozila → cena i uslovi → pritisak za gotovinu → odlazak." data-en="<strong>Model:</strong> contact → urgency → hooking the vehicle → price and terms → cash pressure → departure."><strong>Model:</strong> kontakt → hitnost → vezivanje vozila → cena i uslovi → pritisak za gotovinu → odlazak.</div>
    </section>
    <section class="card">
      <h2 data-sr="Hronološki tok (faze + grananja)" data-en="Timeline (phases + branching)">Hronološki tok (faze + grananja)</h2>
      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 1 — Pojava pomoći na mestu" data-en="Phase 1 — Help appears on scene">Faza 1 — Pojava pomoći na mestu</h3>
        <p data-sr="Vozilo je zaustavljeno ili parkirano sporno; neko nudi šlep ili već vuče bez jasnog dogovora o ceni." data-en="Your vehicle is stopped or parked in a dispute; someone offers a tow or already hooks up without a clear price.">Vozilo je zaustavljeno ili parkirano sporno; neko nudi šlep ili već vuče bez jasnog dogovora o ceni.</p>
        <ul class="bullets"><li data-sr="Kamion dolazi brzo kao da je slučajno u blizini." data-en="The truck arrives quickly as if coincidentally nearby.">Kamion dolazi brzo kao da je slučajno u blizini.</li><li data-sr="Govor je žuran i sugeriše da će policija ili parking odmah kažnjavati." data-en="Talk is rushed and suggests police or parking will punish immediately.">Govor je žuran i sugeriše da će policija ili parking odmah kažnjavati.</li><li data-sr="Cena se izgovara usput ili na kraju." data-en="Price is mentioned in passing or at the end.">Cena se izgovara usput ili na kraju.</li><li data-sr="Traže gotovinu pre otpustanja vozila ili pre potpisa." data-en="They want cash before releasing the vehicle or before you sign.">Traže gotovinu pre otpustanja vozila ili pre potpisa.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Prihvataš da nepoznato lice preuzme kontrolu nad vozilom bez pisanog dogovora." data-en="<strong>Phase threshold:</strong> You let a stranger take control of the vehicle without a written agreement."><strong>Prag faze:</strong> Prihvataš da nepoznato lice preuzme kontrolu nad vozilom bez pisanog dogovora.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="distraction-theft-scam.html" data-sr="Prevara pažnjom — paralelna krađa dok si fokusiran na šlep" data-en="Distraction theft — parallel theft while you focus on the tow">Prevara pažnjom — paralelna krađa dok si fokusiran na šlep</a></li><li><a href="fake-roadside-assistance-scam.html" data-sr="Lažna pomoć na putu — srodna priča o hitnoj intervenciji" data-en="Fake roadside assistance — related urgent help story">Lažna pomoć na putu — srodna priča o hitnoj intervenciji</a></li></ul></div>
      </article>      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 2 — Veza za vozilo i uskraćivanje informacija" data-en="Phase 2 — Hooking up and withholding info">Faza 2 — Veza za vozilo i uskraćivanje informacija</h3>
        <p data-sr="Vozilo se vezuje ili blokira dok ti još uvek nisu dati jasni uslovi, kilometri ili adresa servisa." data-en="The car is hooked or blocked while clear terms, mileage, or garage address are still missing.">Vozilo se vezuje ili blokira dok ti još uvek nisu dati jasni uslovi, kilometri ili adresa servisa.</p>
        <ul class="bullets"><li data-sr="Ne daju pisanu procenu ili ugovor na tvom jeziku." data-en="They give no written estimate or contract in a form you understand.">Ne daju pisanu procenu ili ugovor na tvom jeziku.</li><li data-sr="Izbegavaju pitanje gde tačno vozi vozilo." data-en="They dodge the question of exactly where the car goes.">Izbegavaju pitanje gde tačno vozi vozilo.</li><li data-sr="Tvrdi se da je jedino slobodno mesto njihov servis." data-en="They claim their yard is the only available slot.">Tvrdi se da je jedino slobodno mesto njihov servis.</li><li data-sr="Ponašanje je agresivno prema tvojoj sumnji." data-en="They turn aggressive when you hesitate.">Ponašanje je agresivno prema tvojoj sumnji.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Dozvoljavaš vezivanje ili pomeranje vozila bez potpune informacije." data-en="<strong>Phase threshold:</strong> You allow hook-up or movement without full information."><strong>Prag faze:</strong> Dozvoljavaš vezivanje ili pomeranje vozila bez potpune informacije.</div>

      </article>      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 3 — Cena koja raste i skrivene stavke" data-en="Phase 3 — Rising price and hidden items">Faza 3 — Cena koja raste i skrivene stavke</h3>
        <p data-sr="Osnovna cena se uvećava zbog noćnog, hitnog, skladišta, kilometara ili administracije." data-en="Base price grows with night, emergency, storage, mileage, or admin fees.">Osnovna cena se uvećava zbog noćnog, hitnog, skladišta, kilometara ili administracije.</p>
        <ul class="bullets"><li data-sr="Svaka rečenica dodaje novu stavku na račun." data-en="Each round of talk adds a new line to the bill.">Svaka rečenica dodaje novu stavku na račun.</li><li data-sr="Pritisak da potpišeš blanko ili nečitljiv papir." data-en="Pressure to sign a blank or unreadable paper.">Pritisak da potpišeš blanko ili nečitljiv papir.</li><li data-sr="Odbijaju karticu i traže samo keš." data-en="They refuse card and insist on cash only.">Odbijaju karticu i traže samo keš.</li><li data-sr="Preti se zadržavanjem vozila ili dodatnim danima skladišta." data-en="They threaten holding the car or extra storage days.">Preti se zadržavanjem vozila ili dodatnim danima skladišta.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Prihvataš iznos ili potpis pod pritiskom da bi dobio vozilo nazad." data-en="<strong>Phase threshold:</strong> You accept a fee or signature under pressure to get the vehicle back."><strong>Prag faze:</strong> Prihvataš iznos ili potpis pod pritiskom da bi dobio vozilo nazad.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="advance-fee-fraud.html" data-sr="Uplata unapred — širi obrazac novih taksi" data-en="Advance fee fraud — broader pattern of new fees">Uplata unapred — širi obrazac novih taksi</a></li></ul></div>
      </article>      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 4 — Preusmeravanje na njihov servis" data-en="Phase 4 — Routing to their garage">Faza 4 — Preusmeravanje na njihov servis</h3>
        <p data-sr="Vozilo završi u servisu ili placu gde se dodatno naplaćuje ulaz, otključavanje ili pregled." data-en="The car ends at a yard where entry, unlock, or inspection fees stack up.">Vozilo završi u servisu ili placu gde se dodatno naplaćuje ulaz, otključavanje ili pregled.</p>
        <ul class="bullets"><li data-sr="Lokacija je daleko od tvog izbora ili od kuće." data-en="The location is far from your choice or home.">Lokacija je daleko od tvog izbora ili od kuće.</li><li data-sr="Isti ljudi pominju mehaničara koji odmah traži avans." data-en="The same people mention a mechanic who wants an advance immediately.">Isti ljudi pominju mehaničara koji odmah traži avans.</li><li data-sr="Otežavaju preuzimanje vozila bez dodatne uplate." data-en="They make pickup hard without another payment.">Otežavaju preuzimanje vozila bez dodatne uplate.</li><li data-sr="Ne prikazuju licencu ili firmu na zahtev." data-en="They fail to show a licence or company name on request.">Ne prikazuju licencu ili firmu na zahtev.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Plaćaš dodatno da bi fizički preuzeo vozilo sa njihovog placa." data-en="<strong>Phase threshold:</strong> You pay extra to physically collect the car from their lot."><strong>Prag faze:</strong> Plaćaš dodatno da bi fizički preuzeo vozilo sa njihovog placa.</div>
        <div class="branch"><p><strong data-sr="Grananja u ovoj fazi" data-en="Branching in this phase">Grananja u ovoj fazi</strong></p><ul class="bullets"><li><a href="fake-mechanic-inspection-scam.html" data-sr="Lažni mehaničar — nastavak uz lažni pregled" data-en="Fake mechanic — follow-on with a fake inspection">Lažni mehaničar — nastavak uz lažni pregled</a></li></ul></div>
      </article>      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 5 — Zatvaranje i odlazak ekipe" data-en="Phase 5 — Crew closes and leaves">Faza 5 — Zatvaranje i odlazak ekipe</h3>
        <p data-sr="Nakon uplate, komunikacija se skraćuje, brojevi ne odgovaraju ili se tvrdi da je sve završeno po zakonu." data-en="After payment, communication shortens, numbers stop working, or they claim it is legal and closed.">Nakon uplate, komunikacija se skraćuje, brojevi ne odgovaraju ili se tvrdi da je sve završeno po zakonu.</p>
        <ul class="bullets"><li data-sr="Račun je nejasan ili ga nema." data-en="The receipt is vague or missing.">Račun je nejasan ili ga nema.</li><li data-sr="Isti model se ponavlja na drugim mestima u gradu." data-en="The same pattern repeats at other city spots.">Isti model se ponavlja na drugim mestima u gradu.</li><li data-sr="Žrtva kasno shvata da je cena bila mnogo iznad tržišne." data-en="The victim realizes late the price was far above market.">Žrtva kasno shvata da je cena bila mnogo iznad tržišne.</li><li data-sr="Ponekad sledi žalba potrošačkoj ili policiji." data-en="Sometimes a consumer or police complaint follows.">Ponekad sledi žalba potrošačkoj ili policiji.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Prestaješ da imaš jasan kanal za reklamaciju ili povrat." data-en="<strong>Phase threshold:</strong> You no longer have a clear channel to dispute or recover fees."><strong>Prag faze:</strong> Prestaješ da imaš jasan kanal za reklamaciju ili povrat.</div>

      </article>      <article class="phase">
        <h3 class="phase-title" data-sr="Faza 6 — Prijava, dokumentacija i prevencija" data-en="Phase 6 — Reporting, documentation, prevention">Faza 6 — Prijava, dokumentacija i prevencija</h3>
        <p data-sr="Čuvanje tablica, fotografija, vremena i papira pomaže prijavi; ubuduće se koristi samo poznata asistencija ili policijski broj." data-en="Saving plates, photos, time, and papers helps reporting; later use only known assistance or police channels.">Čuvanje tablica, fotografija, vremena i papira pomaže prijavi; ubuduće se koristi samo poznata asistencija ili policijski broj.</p>
        <ul class="bullets"><li data-sr="Pozovi policiju na licu mesta ako je moguće." data-en="Call police on scene if possible.">Pozovi policiju na licu mesta ako je moguće.</li><li data-sr="Traži pisanu procenu pre vezivanja vozila." data-en="Ask for a written estimate before hook-up.">Traži pisanu procenu pre vezivanja vozila.</li><li data-sr="Uporedi cenu sa drugim šlep službama pre odluke." data-en="Compare pricing with other tow services before deciding.">Uporedi cenu sa drugim šlep službama pre odluke.</li><li data-sr="Obavesti osiguranje ako je udes u pitanju." data-en="Notify your insurer if a crash is involved.">Obavesti osiguranje ako je udes u pitanju.</li></ul>
        <div class="callout" data-sr="<strong>Prag faze:</strong> Dokumentuješ slučaj i deliš upozorenje u mreži vozača." data-en="<strong>Phase threshold:</strong> You document the case and warn your driver network."><strong>Prag faze:</strong> Dokumentuješ slučaj i deliš upozorenje u mreži vozača.</div>

      </article>
    </section>

    <section class="card">
      <h2 data-sr="Crvene zastavice" data-en="Red flags">Crvene zastavice</h2>
      <ul class="bullets"><li data-sr="Šlep stiže pre nego što si ti pozvao bilo koju službu." data-en="A tow arrives before you called any service.">Šlep stiže pre nego što si ti pozvao bilo koju službu.</li><li data-sr="Cena se menja posle vezivanja vozila." data-en="Price changes after the vehicle is hooked.">Cena se menja posle vezivanja vozila.</li><li data-sr="Traže isključivo gotovinu bez fiskalnog ili jasnog računa." data-en="They demand cash only with no clear fiscal receipt.">Traže isključivo gotovinu bez fiskalnog ili jasnog računa.</li><li data-sr="Ne pokazuju naziv firme, adresu ili dozvolu na zahtev." data-en="They do not show company name, address, or licence on request.">Ne pokazuju naziv firme, adresu ili dozvolu na zahtev.</li><li data-sr="Ponašanje je preteće ako pitaš za pauzu ili drugu ponudu." data-en="They turn threatening if you ask for a pause or another quote.">Ponašanje je preteće ako pitaš za pauzu ili drugu ponudu.</li><li data-sr="Vozilo se vuče ka servisu koji si ne izabrao." data-en="The car is towed to a garage you did not choose.">Vozilo se vuče ka servisu koji si ne izabrao.</li><li data-sr="Izbegavaju kontakt sa policijom ili osiguranjem." data-en="They avoid contact with police or insurance.">Izbegavaju kontakt sa policijom ili osiguranjem.</li><li data-sr="Tvrdi se da moraš odmah potpisati obavezni papir." data-en="They say you must sign an obligatory paper immediately.">Tvrdi se da moraš odmah potpisati obavezni papir.</li><li data-sr="Dva ili više ljudi pritiska da prihvatiš bez čitanja." data-en="Two or more people pressure you to accept without reading.">Dva ili više ljudi pritiska da prihvatiš bez čitanja.</li><li data-sr="Nakon uplate teško je dobiti vozilo ili ključeve istog dana." data-en="After payment it is hard to get the car or keys the same day.">Nakon uplate teško je dobiti vozilo ili ključeve istog dana.</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Provere: 8 brzih provera" data-en="Checks: 8 quick checks">Provere: 8 brzih provera</h2>
      <ul class="bullets"><li data-sr="Da li stranac forsira brzinu i usamljenje umesto zvaničnog mesta?" data-en="Does a stranger push speed and isolation instead of an official setting?">Da li stranac forsira brzinu i usamljenje umesto zvaničnog mesta?</li><li data-sr="Da li možeš da ostaneš u javnom prostoru sa svjedocima dok razgovaraš?" data-en="Can you stay in a public space with witnesses while you talk?">Da li možeš da ostaneš u javnom prostoru sa svjedocima dok razgovaraš?</li><li data-sr="Da li bi prava služba tražila uplatu gotovinom na parkingu bez računa?" data-en="Would a real service demand cash on a parking lot with no receipt?">Da li bi prava služba tražila uplatu gotovinom na parkingu bez računa?</li><li data-sr="Da li traže da držiš ili da vidiš sadržaj novčanika na ulici?" data-en="Do they ask to hold or see the contents of your wallet in the street?">Da li traže da držiš ili da vidiš sadržaj novčanika na ulici?</li><li data-sr="Da li postoji drugi član ekipe koji se slučajno približava torbi ili vozilu?" data-en="Is there a second person who accidentally nears your bag or vehicle?">Da li postoji drugi član ekipe koji se slučajno približava torbi ili vozilu?</li><li data-sr="Da li scenario zavisi od tvoje žurbe, stida ili straha od scene?" data-en="Does the script depend on your hurry, shame, or fear of a scene?">Da li scenario zavisi od tvoje žurbe, stida ili straha od scene?</li><li data-sr="Da li možeš da pozoveš broj sa zvaničnog sajta institucije, a ne broj koji oni daju?" data-en="Can you call a number from an official website, not one they give you?">Da li možeš da pozoveš broj sa zvaničnog sajta institucije, a ne broj koji oni daju?</li><li data-sr="Da li bi prijatelj rekao da je ovo bezbedan potez u istim uslovima?" data-en="Would a friend say this is a safe move under the same conditions?">Da li bi prijatelj rekao da je ovo bezbedan potez u istim uslovima?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Checklista: 12 pitanja" data-en="Checklist: 12 questions">Checklista: 12 pitanja</h2>
      <ul class="bullets"><li data-sr="Da li sam ostao u prostoru sa kamerama ili osobljem?" data-en="Did I stay in an area with CCTV or staff?">Da li sam ostao u prostoru sa kamerama ili osobljem?</li><li data-sr="Da li sam tražio legitimaciju ili račun pre bilo kakve uplate?" data-en="Did I ask for ID or a receipt before any payment?">Da li sam tražio legitimaciju ili račun pre bilo kakve uplate?</li><li data-sr="Da li sam držao torbu i vrednosti u vidnom polju tokom celog kontakta?" data-en="Did I keep bag and valuables in sight for the whole contact?">Da li sam držao torbu i vrednosti u vidnom polju tokom celog kontakta?</li><li data-sr="Da li sam izbegao ulazak u tuđe vozilo ili slepu uličicu?" data-en="Did I avoid entering someone else's car or a blind alley?">Da li sam izbegao ulazak u tuđe vozilo ili slepu uličicu?</li><li data-sr="Da li sam odbio da pokažem ceo novčanik ili da ga predam na proveru?" data-en="Did I refuse to show my whole wallet or hand it over for a check?">Da li sam odbio da pokažem ceo novčanik ili da ga predam na proveru?</li><li data-sr="Da li sam proverio štetu na vozilu pre nego što sam prihvatio pomoć?" data-en="Did I verify vehicle damage before accepting help?">Da li sam proverio štetu na vozilu pre nego što sam prihvatio pomoć?</li><li data-sr="Da li sam fotografisao tablice, lice ili uniformu ako je bezbedno?" data-en="Did I photograph plates, face, or uniform if it was safe?">Da li sam fotografisao tablice, lice ili uniformu ako je bezbedno?</li><li data-sr="Da li sam odmah posle incidenta proverio novčanik, telefon i ključeve?" data-en="Did I check wallet, phone, and keys right after the incident?">Da li sam odmah posle incidenta proverio novčanik, telefon i ključeve?</li><li data-sr="Da li sam razumeo da žurba i javna scena često služe odvlačenju pažnje?" data-en="Did I understand that rush and public drama often serve distraction?">Da li sam razumeo da žurba i javna scena često služe odvlačenju pažnje?</li><li data-sr="Da li sam mogao da odložim odluku za 30 minuta bez gubitka prilike?" data-en="Could I delay the decision 30 minutes without losing the deal?">Da li sam mogao da odložim odluku za 30 minuta bez gubitka prilike?</li><li data-sr="Da li bih isti scenario prihvatio da mi ga neko drugi ispriča?" data-en="Would I accept the same scenario if someone else described it to me?">Da li bih isti scenario prihvatio da mi ga neko drugi ispriča?</li><li data-sr="Da li postoji zvaničan kanal (policija, parking servis, klub) koji mogu da pozovem?" data-en="Is there an official channel (police, parking operator, club) I can call?">Da li postoji zvaničan kanal (policija, parking servis, klub) koji mogu da pozovem?</li></ul>
    </section>
    <section class="card">
      <h2 data-sr="Ako sumnja krene: redosled poteza" data-en="If suspicion starts: order of steps">Ako sumnja krene: redosled poteza</h2>
      <ol class="steps"><li data-sr="Prekini interakciju i ostani na mestu sa svjedocima ili uđi u objekat sa osobljem." data-en="End the interaction and stay where there are witnesses or enter a staffed building.">Prekini interakciju i ostani na mestu sa svjedocima ili uđi u objekat sa osobljem.</li><li data-sr="Ne daj novčanik, telefon ni ključeve u tuđe ruke i ne prati nepoznate u vozilo." data-en="Do not hand wallet, phone, or keys to others and do not follow strangers into a car.">Ne daj novčanik, telefon ni ključeve u tuđe ruke i ne prati nepoznate u vozilo.</li><li data-sr="Proveri torbu, džep i vozilo pre nego što potpišeš bilo šta ili platiš." data-en="Check bag, pockets, and vehicle before you sign anything or pay.">Proveri torbu, džep i vozilo pre nego što potpišeš bilo šta ili platiš.</li><li data-sr="Pozovi policiju ili bezbednost ako osećaš pritisak, izolaciju ili fizički kontakt." data-en="Call police or security if you feel pressure, isolation, or physical contact.">Pozovi policiju ili bezbednost ako osećaš pritisak, izolaciju ili fizički kontakt.</li><li data-sr="Prijavi incident sa vremenom, mestom i opisom lica ili vozila." data-en="Report the incident with time, place, and descriptions of people or vehicles.">Prijavi incident sa vremenom, mestom i opisom lica ili vozila.</li></ol>
    </section>
    <section class="card">
      <h2 data-sr="Ako pokušavaš da pomogneš nekome" data-en="If you are trying to help someone">Ako pokušavaš da pomogneš nekome</h2>
      <div class="grid-2">
        <div class="phase">
          <div class="label" data-sr="Pitanja koja pomažu" data-en="Helpful questions">Pitanja koja pomažu</div>
          <ul class="bullets"><li data-sr="Da li je osoba već predala novac, ključeve ili telefon strancu na ulici?" data-en="Have they already handed cash, keys, or a phone to a stranger in the street?">Da li je osoba već predala novac, ključeve ili telefon strancu na ulici?</li><li data-sr="Da li postoji pritisak da se odmah plati ili potpiše bez pauze?" data-en="Is there pressure to pay or sign immediately without a pause?">Da li postoji pritisak da se odmah plati ili potpiše bez pauze?</li><li data-sr="Da li su tražili da se ode na usamljeno mesto ili u nepoznato vozilo?" data-en="Were they asked to go to an isolated spot or an unknown vehicle?">Da li su tražili da se ode na usamljeno mesto ili u nepoznato vozilo?</li><li data-sr="Da li sumnja dolazi tek posle što su se odmakli od mesta događaja?" data-en="Does doubt only appear after they moved away from the scene?">Da li sumnja dolazi tek posle što su se odmakli od mesta događaja?</li></ul>
        </div>
        <div class="phase">
          <div class="label" data-sr="Rečenice koje rade" data-en="Phrases that work">Rečenice koje rade</div>
          <ul class="bullets"><li data-sr="Hajde u prodavnicu, banku ili stanicu sa osobljem i tu nastavimo razgovor." data-en="Let us continue inside a shop, bank, or staffed station.">Hajde u prodavnicu, banku ili stanicu sa osobljem i tu nastavimo razgovor.</li><li data-sr="Ne plaćamo i ne predajemo predmete dok identitet i ovlašćenje nisu provereni zvanično." data-en="We do not pay or hand over items until identity and authority are verified officially.">Ne plaćamo i ne predajemo predmete dok identitet i ovlašćenje nisu provereni zvanično.</li><li data-sr="Pozivam policiju ili bezbednost objekta da provere situaciju zajedno sa nama." data-en="I am calling police or venue security to check the situation with us.">Pozivam policiju ili bezbednost objekta da provere situaciju zajedno sa nama.</li><li data-sr="Pauza od pola sata neće pokvariti legitiman posao, ali će prekinuti uličnu šemu." data-en="A thirty-minute pause will not ruin a legitimate deal but will break a street script.">Pauza od pola sata neće pokvariti legitiman posao, ali će prekinuti uličnu šemu.</li></ul>
        </div>
      </div>
    </section>
`
};
